- README.md
- bin/vue-init
- package.json
> Use download-git-repo to support bitbucket also

- README.md
- bin/vue-init
- package.json
> Add --clone flag to download from private repos

- README.md
- bin/vue-init
- package.json
> Metalsmith and inquirer

- CONTRIBUTING.md
We might be able to redirect template issues to their repos.
> Contributing guide.

- bin/vue-list
> Compatible with github API error message

- bin/vue-init
- lib/check-version.js
- lib/vue2-version-warn.js
- package.json
Don't yet warn for `webpack` template since 2.0 version is not yet released.
/cc @chrisvfritz
> Warn user about Vue 2.x template.

- bin/vue-init
- package.json
also `webpack` template now supports Vue 2.0.
> Remove checkDistBranch

- issue_template.md
> Encourage English

- lib/ask.js
It would allow [this](https://github.com/Akryum/vue-share-components/blob/dev/meta.js#L22)
> Default gets the data as argument

- bin/vue-build
- docs/build.md
Introducing watch mode:
```bash
$ vue build Counter.vue --watch
```
Like the default development mode but remove HMR support and uses a real file system `compiler.watch`
> Add watch mode

- bin/vue-build
- docs/build.md
Check out the [updated docs](https://github.com/EGOIST-robot/vue-cli/blob/feat-run/docs/build.md#runwebpackconfig-options).
> Support custom run process

- README.md
- lib/generate.js
Also solves https://github.com/vuejs/vue-cli/issues/265
> Add `complete` option

- lib/eval.js
Although has no impact on the rest of the code, my eye was blinking when I saw it ;)
> Fix function name typo

- bin/vue-init
Node 4 does not support destructuring.
> Fix node 4 compatibility.

- .github/COMMIT_CONVENTION.md
- .github/CONTRIBUTING.md
- docs/Plugin.md
I fixed two broken links and made some spelling corrections.
> fix(docs): Fixed broken links

- docs/Plugin.md
change `prompt.js` to `prompts.js`
> fix: correct filename

- packages/@vue/cli-plugin-unit-jest/generator/template/test/unit/HelloWorld.spec.js
- packages/@vue/cli-plugin-unit-mocha/generator/template/test/unit/HelloWorld.spec.js
Replace `Hello.vue` by `HelloWorld.vue`
> Jest template: fix the name of the tested file 

- packages/@vue/cli-service/lib/Service.js
Small typo I noticed while going through the source code
> Fix comment typo

- packages/@vue/cli-service/lib/commands/build/index.js
Small typo.
Please let me know whether direct PRs like these are welcomed of if you'd rather have these submitted as issues instead.
> Fix typo in error message

- README.md
> chore: update status from alpha to beta

- packages/@vue/cli-service/lib/PluginAPI.js
> Fix typo's in comments

- packages/@vue/cli/lib/add.js
- packages/@vue/cli/lib/invoke.js
- packages/@vue/cli/lib/util/module.js
> feat: allow 'vue add' to work with plugins without a generator

- packages/@vue/cli-service/__tests__/Service.spec.js
- packages/@vue/cli-service/lib/Service.js
> fix(cli-service): should not add a leading slash to baseUrl when it is absolute

- packages/@vue/cli-plugin-unit-jest/generator/index.js
- packages/@vue/cli-plugin-unit-jest/package.json
Fixed an issue when try to import static files.
more information in below link:
https://github.com/facebook/jest/issues/2663
> fix: Syntax Error with asset files

- packages/@vue/cli/package.json
> fix(dependencies): add deepmerge dependencies

- packages/@vue/cli-plugin-e2e-nightwatch/README.md
I wonder if someone should create a spellcheck test suite for README files...
> Fixed typo

- packages/@vue/cli-service/generator/template/src/components/HelloWorld.vue
Just a small fix of a broken link
> Fix vue-loader broken link

- packages/@vue/cli-plugin-unit-jest/generator/template/tests/unit/HelloWorld.spec.js
- packages/@vue/cli-plugin-unit-mocha/generator/template/tests/unit/HelloWorld.spec.js
see https://github.com/vuejs/vue-test-utils/releases/tag/v1.0.0-beta.16 in Features
> shallow to shallowMount

- packages/@vue/cli-plugin-e2e-nightwatch/README.md
> Update e2e-nightwatch installation command documentation

- packages/@vue/cli-plugin-eslint/lint.js
@Akryum would you mind seeing if this addresses your concerns? Due to the comment I left on the issue, this solution feels a bit 'hacky'
> feat(lint): pass cli arguments to linter (#1255)

- packages/@vue/cli-service/lib/Service.js
When build and watch are used together.
> fix(mode): default to development

- package.json
The last working version on windows was 2.8.3 (before promisses).
2.9.* versions don't work on win , but work in linux.
The problem is inquirer module.
> make it working on windows again

- docs/guide/deployment.md
Just tested that guy with `Vue CLI v3.0.0-beta.16`, see the result here: https://clorichel.gitlab.io/vue-cli-gitlab-pages
Notes:
- public repository is https://gitlab.com/clorichel/vue-cli-gitlab-pages
- vue init commit: [8316b3fa](https://gitlab.com/clorichel/vue-cli-gitlab-pages/commit/8316b3fac72d014d3b79d1086aec1e1108e8325b)
- adding the files as per the documentation in this PR: [07f3a847](https://gitlab.com/clorichel/vue-cli-gitlab-pages/commit/07f3a84723bf0044c6d39b836991c1af94031f63)
- the related pipeline: https://gitlab.com/clorichel/vue-cli-gitlab-pages/pipelines/23582346
- the full job output: https://gitlab.com/clorichel/vue-cli-gitlab-pages/-/jobs/73894914
> provided the GitLab Pages platform guide

- packages/@vue/cli-service/lib/Service.js
Fix https://github.com/vuejs/vue-cli/issues/1698
> fix: Fixed a bug that caused mode to be ignored if run together with watch

- packages/@vue/cli-ui/apollo-server/connectors/dependencies.js
- packages/@vue/cli-ui/apollo-server/connectors/folders.js
- packages/@vue/cli-ui/apollo-server/connectors/plugins.js
- packages/@vue/cli-ui/apollo-server/connectors/views.js
- packages/@vue/cli-ui/apollo-server/schema/dependency.js
- packages/@vue/cli-ui/apollo-server/schema/plugin.js
- packages/@vue/cli-ui/apollo-server/util/resolve-path.js
- packages/@vue/cli-ui/locales/en.json
- packages/@vue/cli-ui/package.json
- packages/@vue/cli-ui/src/App.vue
- packages/@vue/cli-ui/src/components/InstantSearchPagination.vue
- packages/@vue/cli-ui/src/components/NpmPackageSearch.vue
- packages/@vue/cli-ui/src/components/PackageSearchItem.vue
- packages/@vue/cli-ui/src/components/ProjectDependencyItem.vue
- packages/@vue/cli-ui/src/components/ProjectPluginItem.vue
- packages/@vue/cli-ui/src/graphql/dependencies.gql
- packages/@vue/cli-ui/src/graphql/dependenciesUpdate.gql
- packages/@vue/cli-ui/src/graphql/dependencyDetails.gql
- packages/@vue/cli-ui/src/graphql/dependencyFragment.gql
- packages/@vue/cli-ui/src/graphql/dependencyInstall.gql
- packages/@vue/cli-ui/src/graphql/dependencyUninstall.gql
- packages/@vue/cli-ui/src/graphql/dependencyUpdate.gql
- packages/@vue/cli-ui/src/plugins.js
- packages/@vue/cli-ui/src/router.js
- packages/@vue/cli-ui/src/style/main.styl
- packages/@vue/cli-ui/src/views/ProjectDependencies.vue
- packages/@vue/cli-ui/src/views/ProjectHome.vue
- packages/@vue/cli-ui/src/views/ProjectPluginsAdd.vue
- yarn.lock
Manage non- vue-cli packages in your project
> Dependencies view

- packages/@vue/cli-service/lib/config/app.js
> fix: default html template, closes #1679

- docs/config/README.md
> Document lintOnSave: 'error' option

- docs/config/README.md
trying to cover #1753 with this explanation
> assetsDir is ignored when using custom filenames

- packages/@vue/cli/__tests__/Generator.spec.js
- packages/@vue/cli/lib/util/configTransforms.js
> Create .browserslistrc file when user chose "separate config files"

- packages/@vue/cli-service/lib/commands/build/demo-lib-js.html
- packages/@vue/cli-service/lib/commands/build/demo-lib.html
- packages/@vue/cli-service/lib/commands/build/demo-wc.html
https://github.com/vuejs/vue-cli/issues/1765#issuecomment-403433720
> fix(build): add charset to demo pages, fix #1765

- packages/@vue/cli-plugin-pwa/README.md
- packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
added options (please view README.md for more info) to have a better control over the favicons and app icons generation.
> added options and updated readme

- docs/config/README.md
> Fix typo: directory → directly

- packages/@vue/cli-ui/apollo-server/api/PluginApi.js
> fix(ui): #1876

- packages/@vue/cli/lib/util/fetchRemotePreset.js
> fix: clear tmpdir before cloning remote preset, fix #1878

- packages/@vue/cli-service/lib/commands/serve.js
> fix(dev-server): pass 2nd argument to devServer.before

- packages/@vue/cli-service/lib/config/app.js
https://github.com/vuejs/vue-cli/commit/625d541715e232140e53814fd914090f6f5b5041#diff-6d88578c42f9707c5dba663061d43393
> fix: avoid hash collisions

- packages/@vue/cli-service/lib/Service.js
- packages/@vue/cli-service/lib/config/base.js
- packages/@vue/cli-service/lib/config/css.js
- packages/@vue/cli-service/lib/config/prod.js
- packages/@vue/cli-service/lib/options.js
Add a switch for enabling file name hashing or not.
> feat: add filename hashing switch

- docs/guide/deployment.md
Updated the deployment doc to also feature now.sh
> Added Now deployment

- packages/@vue/cli/lib/promptModules/router.js
> fix: escape code shown in webpage

- packages/@vue/cli-plugin-typescript/package.json
- yarn.lock
bump fork-ts-checker-webpack-plugin to v0.4.4
fix #1104
> fix(typescript): prevent compilation error when using src attribute on sfc

- packages/@vue/cli-service/lib/util/resolveLoaderError.js
> docs: fix typo, without is misspelled withotu

- docs/zh/dev-guide/ui-api.md
Ref: https://gist.github.com/Jinjiang/71758a20fa330528c81960c1eea10d05#file-docs-zh-diff-L398:L923
/ping @Justineo
> docs(zh): updated ui-api.md

- package.json
- packages/@vue/cli-plugin-eslint/generator.js
- packages/@vue/cli-plugin-typescript/generator/index.js
- packages/@vue/cli-ui/package.json
- yarn.lock
> fix: upgrade lint-staged to v7.2.2

- docs/guide/deployment.md
Updated the public folder name to match the description on the Firebase section
> docs: update deployment.md

- docs/guide/deployment.md
Seems like this was copy pasted from the vuepress docs and wasn't updated.
> docs: Fix deploy.sh example with correct commands

- packages/@vue/cli-service/lib/config/dev.js
> fix: fix hmr compatibility with worker-loader

- packages/@vue/cli/lib/util/shouldUseTaobao.js
> [polish] word mistake

- packages/@vue/cli-plugin-babel/index.js
fixed the path of package.json in @vue/babel-preset-app
> fix require('@vue/babel-preset-app').version return undefined bug

- packages/@vue/cli-ui/locales/en.json
> Spelling Issues in en.json

- packages/@vue/cli/bin/vue.js
- packages/@vue/cli/lib/add.js
- packages/@vue/cli/lib/invoke.js
> feat: support for `--registry` option in `vue add` & `vue invoke` commands

- packages/@vue/cli-service/lib/commands/build/setPublicPath.js
This fixes [issues 2813](https://github.com/vuejs/vue-cli/issues/2813)
> fix(cli-service): fix path RegEx error

- packages/@vue/cli/bin/vue.js
I think the comment is wrong. It's not about the --no-git flag, but about the --git.
Is that right?
> Fixing the comment about forcing git

- packages/@vue/cli-ui/apollo-server/connectors/plugins.js
> fix: typo in plugin invoke notification

- docs/guide/mode-and-env.md
> docs: added a code sample for computed env variables declaration

- packages/@vue/cli-plugin-eslint/__tests__/eslintGenerator.spec.js
- packages/@vue/cli-plugin-eslint/__tests__/eslintPlugin.spec.js
- packages/@vue/cli-plugin-eslint/lint.js
> fix: fix eslint cwd confusion during onCreateComplete hook execution

- docs/zh/guide/creating-a-project.md
update windows warning, in order to be consistent with other docs
> docs(zh): supply windows warning

- packages/@vue/cli-ui/apollo-server/connectors/projects.js
- packages/@vue/cli-ui/src/util/folders.js
fixes #3140 & enforces package.json [name property rules](https://docs.npmjs.com/files/package.json#name)
> fix(vue-ui): enforce package.json npm rules

- packages/@vue/cli-service/lib/commands/build/demo-lib-js.html
- packages/@vue/cli-service/lib/commands/build/demo-lib.html
- packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js
when  extract css disabled , there is no css file in output path;
so i update the template  file.
> chore: ignore html link tag when css extract is false

- docs/guide/cli-service.md
https://github.com/vuejs/vue-cli/issues/3031
> doc: fix #3031(en)

- docs/zh/guide/cli-service.md
https://github.com/vuejs/vue-cli/issues/3031
> doc: fix #3031

- packages/@vue/cli-service/__tests__/multiPage.spec.js
Add test case for https://github.com/vuejs/vue-cli/pull/3181, it was merged just before I pushed to original branch....😂
> test(cli-service): add test for multi page history api fallback

- docs/guide/plugins-and-presets.md
add self-hosted repos example for remote presets.
> docs: add self-hosted repos example for remote presets.

- packages/@vue/cli-service/__tests__/Service.spec.js
- packages/@vue/cli-service/lib/Service.js
- packages/@vue/cli-service/types/ProjectOptions.d.ts
- packages/@vue/cli-service/types/index.d.ts
> feat: allow vue.config.js to return a function

- package.json
- packages/@vue/cli-service-global/__tests__/globalService.spec.js
- packages/@vue/cli-service-global/index.js
> feat: warn if run instant prototyping in a project directory

- packages/@vue/cli-service/lib/util/prepareProxy.js
> fix: proxy should warn when array is passed.

- packages/@vue/cli-service/lib/config/base.js
> feat: support pug as html template

- docs/dev-guide/plugin-dev.md
Hi 👋 ,
A tiny typo fix for-> Vue UI integration(# ui-integration).
thanks
Ramona 🐳
> Fix typo in plugin-dev.md

- docs/guide/installation.md
I had npm give me very weird error messages until I preprended `sudo`. It said something like unexpected end of JSON parsing druing installing some random package. `sudo` fixed that.
> Mention admin privileges as a install requirement

- packages/@vue/cli/lib/util/__tests__/extendJSConfig.spec.js
- packages/@vue/cli/lib/util/extendJSConfig.js
> feat: do not write undefined fields to config files

- packages/@vue/cli-ui/apollo-server/util/command.js
- packages/@vue/cli/lib/add.js
- packages/@vue/cli/lib/invoke.js
> fix vue add/invoke bug when user does not have yarn installed

- packages/@vue/cli-plugin-unit-jest/generator/index.js
> fix: jest typeahead config

- packages/@vue/cli-service/lib/commands/inspect.js
- packages/@vue/cli-service/package.json
- yarn.lock
> feat: syntax highlight inspect output

- packages/@vue/cli-service/package.json
See https://github.com/webpack-contrib/css-loader/blob/bc16c3db953dbf4d711753fbb0cc60253def6916/CHANGELOG.md#200-2018-12-07
> feat!: upgrade css-loader to v2

- packages/@vue/cli/lib/Creator.js
> feat: should support `bare` option in `preset.json`

- packages/@vue/cli-service/package.json
> chore: upgrade webpack-dev-server to 3.4.1

- packages/@vue/cli-service/lib/commands/serve.js
I changed `none` to `silent`, so the server can work fine.
> hotfix for #4016

- packages/@vue/cli-service/lib/config/dev.js
> fix: fix dev mode compatibility with workers

- packages/@vue/cli-plugin-typescript/prompts.js
- packages/@vue/cli/lib/promptModules/typescript.js
> docs: add description of babel plugin usage in TS plugin prompt

- docs/zh/guide/mode-and-env.md
> type error; sercet => secret

- packages/@vue/cli-service/package.json
> chore: upgrade default-gateway to 5.0.2

- .github/ISSUE_TEMPLATE.md
This mentions Issue Helper application explicitely as the required entry
point for issue submission.
Thanks!
> docs: Update issue template naming Issue Helper

- packages/@vue/cli-plugin-eslint/index.js
> fix: fix eslint path resolution in `vue serve`

- packages/@vue/cli/lib/promptModules/linter.js
> chore: deprecate tslint

- packages/@vue/cli-plugin-eslint/generator/index.js
if use typescript,add ts file check to lint-staged
fix #3947
> fix(eslint-generator): add ts file check to lint-staged

- packages/@vue/cli-plugin-typescript/generator/convert.js
fixes https://github.com/vuejs/vue-cli/issues/2676#issuecomment-514163315
> fix: fix typo in typescript generator, convertAllFiles -> convertJsToTs

- docs/guide/deployment.md
This is a follow-up PR to https://github.com/vuejs/vue-cli/pull/4412 and links the link that I forgot to link previously... 😄
> Link ZEIT Now deployment example

- docs/config/README.md
You are able to pass a number to this configuration option to set the amount of workers, but it was not documented. Hopefully this change will help save someone else some headache!
> Update parallel config description

- packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js
- packages/@vue/cli-service/lib/commands/build/resolveWcConfig.js
> fix: merge custom `externals` config correctly, supports array

- packages/@vue/cli-service/generator/index.js
> feat: bump default less-loader version

- packages/@vue/cli-shared-utils/__tests__/pluginResolution.spec.js
- packages/@vue/cli-shared-utils/lib/pluginResolution.js
> fix(pluginResolution): support dots in scope names

- docs/zh/guide/build-targets.md
> docs(zh): update build-targets.md

- packages/@vue/cli/__tests__/Upgrader.spec.js
- packages/@vue/cli/lib/Upgrader.js
> fix(upgrade): correctly update version range in package.json

- packages/@vue/cli-plugin-eslint/migrator/index.js
- packages/@vue/cli/__tests__/Upgrader.spec.js
> feat: implement a migrator to auto add eslint to deps

- docs/guide/css.md
- docs/zh/guide/css.md
- packages/@vue/cli-service/__tests__/css.spec.js
- packages/@vue/cli-service/generator/index.js
- packages/@vue/cli-service/lib/config/css.js
- packages/@vue/cli-service/package.json
- packages/@vue/cli-shared-utils/lib/spinner.js
- yarn.lock
> Support sass-loader v8

- packages/@vue/cli-plugin-e2e-nightwatch/__tests__/nightwatchPlugin.spec.js
- packages/@vue/cli-plugin-e2e-nightwatch/index.js
> fix: fix nightwatch cli option (`--url`) handling

- .eslintignore
- packages/@vue/cli-plugin-babel/codemods/__testfixtures__/customConfig.input.js
- packages/@vue/cli-plugin-babel/codemods/__testfixtures__/customConfig.output.js
- packages/@vue/cli-plugin-babel/codemods/__testfixtures__/default.input.js
- packages/@vue/cli-plugin-babel/codemods/__testfixtures__/default.output.js
- packages/@vue/cli-plugin-babel/codemods/__testfixtures__/require.input.js
- packages/@vue/cli-plugin-babel/codemods/__testfixtures__/require.output.js
- packages/@vue/cli-plugin-babel/codemods/__testfixtures__/templateLiteral.input.js
- packages/@vue/cli-plugin-babel/codemods/__testfixtures__/templateLiteral.output.js
- packages/@vue/cli-plugin-babel/codemods/__tests__/usePluginPreset.spec.js
- packages/@vue/cli-plugin-babel/codemods/usePluginPreset.js
- packages/@vue/cli-plugin-babel/migrator/index.js
- packages/@vue/cli-plugin-babel/package.json
See https://github.com/vuejs/vue-cli/pull/4533
> feat(babel): transform preset names in the plugin migrator

- packages/@vue/cli/lib/util/ProjectPackageManager.js
> Revert "feat: allow custom packageManager other than npm/yarn/pnpm"

- packages/@vue/cli/lib/Upgrader.js
> fix(upgrade-all): avoid accidentally writing outdated package.json back

- packages/@vue/cli-service/generator/template/_gitignore
> feat: add webdriver log files to gitignore

- packages/@vue/cli-service/package.json
> fix: fix ie11 compatibility when css.extract set to true

- docs/guide/build-targets.md
I really needed this tip and luckily got it from this awesome community in a github issue.
This definitely needs to be in the docs aswell:
https://github.com/vuejs/vue-cli/issues/2304#issuecomment-414702510
> missing documentation for building with vuex

- packages/@vue/cli-plugin-babel/migrator/index.js
> fix: Corrected typo in babel migrator

- packages/@vue/cli-service/generator/index.js
- packages/@vue/cli-service/generator/router.js
- packages/@vue/cli-service/generator/vuex.js
- packages/@vue/cli-service/package.json
> fix: allow v3 cli to invoke vuex & router plugin from inside cli-service

- docs/migrating-from-v3/README.md
> Fix link to eslint PR

- packages/@vue/cli-service/generator/router.js
> fix: fix a typo that caused router failed to install in older versions

- packages/@vue/cli-ui/ui-defaults/suggestions.js
> fix(ui): "add router" button should not require prompt in terminal

- docs/guide/cli-service.md
> Document serve command default entry value

- docs/.vuepress/config.js
Add a link to https://awesomejs.dev/for/vue-cli/
> Add 'Browse plugins' link to header

- docs/guide/cli-service.md
Added complete required entries for lint-staged to work
> Update doc section on Git Hooks

- packages/@vue/babel-preset-app/index.js
> fix: typo atfer

- packages/@vue/cli/lib/Upgrader.js
> fix: invalid version error when modules not installed

- packages/@vue/cli-plugin-typescript/__tests__/tsPluginBabel.spec.js
- packages/@vue/cli-plugin-typescript/index.js
> fix: fix tsx compilation

- packages/@vue/cli-plugin-babel/index.js
> fix: do not throw when babel config contains ignore/include/exclude

- docs/config/README.md
> fix: typo errors

- packages/@vue/cli/bin/vue.js
> refactor: use inline approach

- docs/dev-guide/ui-api.md
> docs: his -> their

- packages/@vue/cli-plugin-unit-jest/README.md
Refs
- https://jestjs.io/docs/en/troubleshooting
- https://jestjs.io/docs/en/cli.html#runinband
I only tested on macOS.
> Update debugging instructions

- docs/core-plugins/pwa.md
I think this is the correct PR 🤒 
#4925
> docs: update example code

- packages/@vue/cli-service-global/package.json
> build: fix link to homepage

- docs/zh/guide/css.md
> docs(zh): Sync Chinese translation

- packages/@vue/cli-service-global/index.js
> feat(cli-service-global): to know if the  build has finished

- packages/@vue/cli-ui-addon-webpack/src/components/WebpackDashboard.vue
- packages/@vue/cli-ui-addon-widgets/src/components/NewsItem.vue
- packages/@vue/cli-ui-addon-widgets/src/components/NewsItemDetails.vue
Added rel="noopener noreferrer" to external links
> Added rel="noopener noreferrer" to external links

- docs/migrating-from-v3/README.md
> Fix a typo in migration guide

- docs/guide/prototyping.md
Close https://github.com/vuejs/vue-cli/issues/5050
> Mention that Vue CLI should be installed in Prototyping guide

- docs/guide/webpack.md
> Add a demo for multiple loaders

- packages/@vue/cli/lib/util/ProjectPackageManager.js
This PR also fixes compatibility with Yarn 2
> refactor: use env variables to set registry for package managers

- packages/@vue/cli-plugin-unit-jest/generator/index.js
- packages/@vue/cli-plugin-unit-mocha/__tests__/mochaGenerator.spec.js
- packages/@vue/cli-plugin-unit-mocha/generator/index.js
> fix applyESLint when eslint plugin is added after unit test plugins

- docs/zh/guide/webpack.md
English version already merged https://github.com/vuejs/vue-cli/pull/5076/files
> Add a demo for multiple loaders (Chinese doc)

- package.json
- packages/@vue/cli-plugin-typescript/generator/index.js
- packages/@vue/cli-plugin-typescript/package.json
- packages/@vue/cli-ui/package.json
- yarn.lock
> feat: upgrade to typescript@~3.7.5

- docs/guide/browser-compatibility.md
the same with [https://github.com/vuejs/vue-cli/pull/4940](https://github.com/vuejs/vue-cli/pull/4940)
> docs(en): update polyfill import according to core-js 3 docs

- packages/@vue/cli/lib/promptModules/__tests__/e2e.spec.js
- packages/@vue/cli/lib/promptModules/e2e.js
> chore: Minor typographical fix

- docs/zh/guide/deployment.md
> docs(zh): Update now 404 url

- packages/@vue/cli/__tests__/Creator.spec.js
> Minor typographical fix

- packages/@vue/cli-service-global/lib/globalConfigPlugin.js
> fix(cli-service-global): fix no-debugger rule config

- packages/@vue/cli/lib/util/getPkg.js
> Improve package.json not found error 

- packages/@vue/cli-shared-utils/lib/env.js
> fix false positive of `hasProjectNpm`

- packages/@vue/cli-service/generator/index.js
- packages/@vue/cli-ui-addon-webpack/package.json
- packages/@vue/cli-ui-addon-widgets/.browserslistrc
- packages/@vue/cli-ui/package.json
> feat: add "not dead" to the default browserslist query

- packages/@vue/cli-service/lib/commands/build/index.js
See https://github.com/yarnpkg/berry/issues/964#issuecomment-587425891
> fix: spawn scripts with node, fix modern mode with Yarn 2 (Berry)

- docs/guide/deployment.md
> Make Heroku resource link accessible

- packages/@vue/cli-plugin-eslint/migrator/index.js
> fix(eslint-migrator): fix local eslint major version detection

- docs/dev-guide/plugin-dev.md
> Fix linking to npmjs.com

- docs/zh/guide/css.md
update chinese verion code  with english version
- [ x ] Docs
- [ x ] No
> docs: Update css.md

- packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js
> fix(cli-service): fix polyfill injection when overriding `entry` with the CLI option

- packages/@vue/cli-plugin-pwa/README.md
- packages/@vue/cli-ui/locales/en.json
Thank @ascott18 for noticing this (https://github.com/vuejs/vue-cli/pull/3042#issuecomment-642252854)
> docs: add documentation for `manifestCrossorigin`

- packages/@vue/cli-plugin-typescript/vue-compiler-sfc-shim.js
> fix: should return the parse result in the compiler-sfc-shim

- packages/@vue/cli-shared-utils/lib/request.js
- packages/@vue/cli-shared-utils/package.json
#5220 
drop-in replacements: replace request-promise-native with util.promisify.
> refactor: replace request-promise-native with util.promisify

- packages/@vue/cli-shared-utils/lib/logger.js
- packages/@vue/cli-shared-utils/lib/spinner.js
- packages/@vue/cli/lib/util/ProjectPackageManager.js
> chore: improve error message when get metadata failed

- packages/@vue/cli-plugin-typescript/package.json
- packages/@vue/cli-service/lib/config/base.js
- packages/@vue/cli-service/package.json
- yarn.lock
Note: no tests were added for this feature. I'd like to add tests after adding generator templates for Vue 3 projects.
> feat: detect and compile Vue 3 projects

- docs/zh/dev-guide/plugin-dev.md
> docs(zh): change line to lines in plugin-dev.md

- packages/@vue/cli-plugin-pwa/README.md
> corrected typo

- docs/zh/config/README.md
> Fix wrong a hash

- packages/@vue/babel-preset-app/README.md
Extend the docs to state explicitly, where the browserslist config file is considered. #5487
> docs: extend the docs of babel-preset-app browserslist

- docs/config/README.md
> docs: publicPath mistake of config reference

- packages/@vue/cli-service/lib/commands/serve.js
> refactor(cli-service): webpack `devtool` option

- packages/@vue/cli/lib/promptModules/__tests__/e2e.spec.js
- packages/@vue/cli/lib/promptModules/e2e.js
> fix(e2e): shouldn't install webdrivers for unchecked browsers on creation

- docs/zh/guide/deployment.md
> docs: add cloudbase deploy doc

- packages/@vue/cli/lib/promptModules/typescript.js
> chore: default to non-class components for Vue 3 TS projects

- packages/@vue/cli-service/types/cli-service-test.ts
> chore: update type definition

- packages/@vue/cli-plugin-typescript/generator/template/src/App.vue
> fix: only replace App.vue when there's no router plugin

- docs/config/README.md
- docs/core-plugins/babel.md
- docs/core-plugins/typescript.md
- packages/@vue/cli-plugin-babel/README.md
- packages/@vue/cli-plugin-typescript/README.md
Closes https://github.com/vuejs/vue-cli/issues/5723
> docs: add thread-loader warnings

- packages/@vue/cli-plugin-typescript/generator/template-vue3/src/App.vue
Follow up of #5771
Fixes #5795
Fixes #5796
> fix: fix Vue 3 + TS + Router template

- docs/zh/guide/deployment.md
> docs: update cloudbase deploy doc

- packages/@vue/cli-ui/locales/en.json
Fixed typo
Fixed a small typo in the `vue-cli guide` in `CSS settings` section
> Docs: Update en.json

- docs/zh/guide/build-targets.md
add the translated part of using vuex.
There is a part missing a translated page.
中文页面有一处缺失。
> In build-targets.md add "using vuex"

- docs/guide/deployment.md
The flow for creating static sites in the Render dashboard was recently simplified, as reflected in these changes. See https://render.com/docs/deploy-vue-js.
> Update Render deployment guide

- packages/@vue/cli-plugin-eslint/eslintDeps.js
> fix(generator): upgrade to prettier v2

- packages/@vue/cli-service/lib/commands/build/demo-lib-js.html
- packages/@vue/cli-service/lib/commands/build/demo-lib.html
- packages/@vue/cli-service/lib/commands/build/demo-wc.html
> fix(cli-service): html template add html5 doctype declaration

- docs/zh/guide/cli-service.md
> update Chinese doc: add entry default value

- docs/config/README.md
> docs: add devServer.inline in config reference

- docs/migrations/migrate-from-v4.md
- packages/@vue/cli-plugin-e2e-cypress/package.json
> feat: update cypress to v6

- docs/migrations/migrate-from-v4.md
- packages/@vue/cli-plugin-e2e-webdriverio/generator/index.js
- packages/@vue/cli-plugin-e2e-webdriverio/package.json
- packages/@vue/cli-plugin-typescript/package.json
- packages/@vue/cli-plugin-unit-mocha/generator/index.js
- packages/@vue/cli-plugin-unit-mocha/package.json
> feat!: update mocha to v8

- docs/migrations/migrate-from-v4.md
- package.json
- packages/@vue/cli-plugin-typescript/package.json
- packages/@vue/cli-plugin-unit-jest/generator/index.js
- packages/@vue/cli-ui/package.json
> chore!: update typescript-related dependencies

- docs/guide/cli-service.md
- docs/ru/guide/cli-service.md
- docs/zh/guide/cli-service.md
- package.json
- packages/@vue/cli-plugin-eslint/__tests__/eslintGenerator.spec.js
- packages/@vue/cli-plugin-eslint/__tests__/eslintPlugin.spec.js
- packages/@vue/cli-plugin-eslint/generator/index.js
- packages/@vue/cli-service/migrator/index.js
- packages/@vue/cli-ui/package.json
> feat: bump lint-staged to v10

- packages/@vue/cli-plugin-babel/package.json
- packages/@vue/cli-plugin-e2e-cypress/package.json
- packages/@vue/cli-plugin-e2e-nightwatch/package.json
- packages/@vue/cli-plugin-eslint/package.json
- packages/@vue/cli-plugin-pwa/package.json
- packages/@vue/cli-plugin-router/package.json
- packages/@vue/cli-plugin-typescript/package.json
- packages/@vue/cli-plugin-unit-jest/package.json
- packages/@vue/cli-plugin-unit-mocha/package.json
- packages/@vue/cli-plugin-vuex/package.json
> chore!: prepare for v5 peer dependencies, drop v4 prereleases

- packages/@vue/cli-service/__tests__/cssPreprocessors.spec.js
- packages/@vue/cli-service/lib/config/css.js
- packages/@vue/cli-service/lib/config/prod.js
- packages/@vue/cli-service/package.json
- packages/@vue/cli-ui/index.js
- yarn.lock
> refactor!: replace optimize-cssnano-plugin with css-minimizer-webpack-plugin

- packages/@vue/cli/lib/util/ProjectPackageManager.js
> fix: fix cypress mirror url for cypress version > 3

- docs/guide/deployment.md
I took this configuration from Netlify's [File-based configuration](https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file) documentation. 
The build command and publish directory could also be defined in this config file.
> Easier Netlify setup

- docs/guide/deployment.md
Corrected 'fo' to 'of' and 'wit' to 'with' on line 180
> Fixed some typos on deployment.md

- docs/zh/config/README.md
The `publicPath` positioning is invalid
> docs(zh): fix `publicPath` hash

- packages/@vue/cli-plugin-unit-mocha/setup.js
See https://github.com/vuejs/vue-next/pull/2943
> fix(mocha): workaround the ShadowRoot issue in Vue 3.0.5

- packages/@vue/cli-plugin-pwa/README.md
- packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
Solves: https://github.com/vuejs/vue-cli/issues/5791
> Support svg favicon

- docs/guide/css.md
> docs: fix minor typo

- docs/zh/dev-guide/plugin-dev.md
> fix code demo

- docs/config/README.md
- docs/ru/config/README.md
- docs/zh/config/README.md
Add JSDoc: `@type` for better editor support.
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html
Relates to https://github.com/vuejs/vue-cli/issues/2138
> docs(config): @type ProjectOptions

- packages/@vue/cli/lib/Generator.js
> fix(create): write the lint-staged config to its own file (close #6298)

- packages/@vue/cli-plugin-e2e-webdriverio/migrator/index.js
- packages/@vue/cli-plugin-typescript/generator/template/tsconfig.json
> fix(webdriverio): add `expect-webdriverio` to tsconfig

- packages/@vue/cli-service/__tests__/build.spec.js
- packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js
> fix: fix `build --dest` option

- packages/@vue/cli-service/package.json
- yarn.lock
> fix: use cssnano v5.0.0-rc.1, work around a npm 6 hoisting bug

- packages/@vue/cli-service/lib/config/app.js
[Related bug](https://github.com/vuejs/vue-cli/issues/6281)
> bugfix: Do not display an error message on empty public folder

- packages/@vue/cli-service/__tests__/generator.spec.js
> chore: remove more await

- packages/@vue/cli-service/lib/commands/build/demo-lib.html
- packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js
> fix(build): demo-lib.html compatible Vue 3

- packages/@vue/cli/lib/promptModules/__tests__/unit.spec.js
- packages/@vue/cli/lib/promptModules/unit.js
> chore: de-prioritize "Mocha + Chai" option as it requires webpack 4 for now

- packages/@vue/cli-service/generator/index.js
- packages/@vue/cli-service/generator/template/jsconfig.json
Providing `jsconfig.json` for improve development experience with `Vetur` and `@VueDX`.
https://github.com/vuejs/vue-cli/issues/6064#issuecomment-733543301
> feat(cli-service): provide jsconfig.json in no-ts template

- docs/guide/deployment.md
> Fix master to main in heroku deployment

- packages/@vue/cli-ui/ui-defaults/config.js
> fix(ui): fix publicPath documentation link

- packages/@vue/cli-plugin-unit-jest/migrator/index.js
> fix: fix jest migrator dependency merging

- packages/@vue/babel-preset-app/index.js
> fix(v4): fix modern mode optional chaining syntax tranpilation

- packages/@vue/cli-service/lib/config/app.js
Add it for use-cases like https://github.com/jantimon/html-webpack-plugin/tree/main/examples/custom-insertion-position
> Feature: add "tags" part to htmlWebpackPlugin

- packages/@vue/cli-plugin-unit-mocha/index.js
> fix(mocha): set mode to `none` to avoid DefinePlugin conflict

- packages/@vue/cli-service/lib/config/assets.js
I hope support this new image format in vue-cli config by default. Can help a lot of developers to improve performance
> feat(cli-service): add support new image format avif

- packages/@vue/cli-plugin-unit-mocha/index.js
> fix(mocha): do not ignore JavaScript tests when TypeScript plugin is installed

- packages/@vue/cli/bin/vue.js
> Fix command description typo

- packages/@vue/cli-service/lib/config/base.js
See discussions at https://github.com/vuejs/vue-loader/issues/1435
> fix: mark `sideEffects: true` for styles in Vue components

- docs/zh/dev-guide/plugin-dev.md
> fix(docs): the plugin-dev in zh has a regexp lose the end /

- packages/@vue/cli-ui/apollo-server/connectors/locales.js
- packages/@vue/cli-ui/package.json
- yarn.lock
> fix(ui): stop depending on the `watch` package

- docs/guide/deployment.md
> Fix typo in deployment guide

- docs/zh/guide/README.md
> docs: Update README.md

- docs/migrations/migrate-from-v4.md
> docs: recommend SFC playground and StackBlitz for instant prototyping

- docs/migrations/migrate-from-v4.md
- packages/@vue/cli-plugin-e2e-cypress/generator/index.js
- packages/@vue/cli-plugin-e2e-cypress/migrator/index.js
- packages/@vue/cli-plugin-e2e-cypress/package.json
- yarn.lock
I thought it was already landed. Turns out not yet.
> feat!: update cypress to 8.3 and require it to be a peer dependency

- packages/@vue/cli-service/lib/config/app.js
use `info` option to skip minimization of public dir
fix https://github.com/vuejs/vue-cli/issues/6699
> fix(cli-service): skip minimization of public dir

- packages/@vue/cli-plugin-router/generator/template-vue3/src/App.vue
- packages/@vue/cli-plugin-router/generator/template/src/App.vue
> fix: improve accessibility of the navigation elements

- packages/@vue/cli-plugin-e2e-cypress/generator/template/tests/e2e/specs/test.js
> fix: Update cypress api link to the latest

- packages/@vue/cli-service/lib/commands/build/formatStats.js
Same style as [Angular CLI](https://github.com/angular/angular-cli/blob/d18469eb3f09f9d38c6c2c52027eb2f6a5c50c9b/packages/angular_devkit/build_angular/src/webpack/utils/stats.ts#L207)
> feat: add build stats hash support
