README.md, bin/vue-init
I used this to prepare my custom template https://github.com/zigomir/vue-starter-kit which is fork of official `webpack` with `vuex`.
=> Load template from fs if directory exists.

README.md, bin/vue-init
Fixes #5. 
Example `meta.json`
```json
{
"schema": {
"name": {
"type": "string",
"required": true,
"label": "Project name"
},
"description": {
"type": "string",
"required": true,
"label": "Project description",
"default": "A Vue.js project"
},
"author": {
"type": "string",
"label": "Author"
},
"private": {
"type": "boolean",
"default": true
},
"preprocessor": {
"label": "CSS Preprocessor",
"type": "checkbox",
"choices": [
"less",
"sass"
]
}
}
}
```
example `package.json`
```json
{
"name": "{{ name }}",
"description": "{{ description }}",
"author": "{{ author }}",
{{#private}}
"private": true,
{{/private}}
"scripts": {
"watchify": "watchify -vd -p browserify-hmr -e src/main.js -o dist/build.js",
"serve": "http-server -c 1 -a localhost",
"dev": "npm-run-all --parallel watchify serve", …
```
=> Multi choice.

lib/ask.js, lib/options.js, package.json, test/e2e/test.js
Hi :wave: 
I try to add a `validation` to check package name is [invalid or not](https://docs.npmjs.com/files/package.json#name) in `vue init`.
=> Add validation for package name in vue init	

README.md, lib/check-version.js, package.json
Forces upgrade to a minimum node version that's compatible with metalsmith. Resolves #81.
=> enforce minimum node version 4.x

.eslintrc, lib/generate.js, test/e2e/test.js
Fixes #86.
Although I was thinking we might rather do this
```js
var data = extend({}, metalsmith.metadata(), { destDirName: name })
```
and also update https://github.com/vuejs-templates/webpack/blob/dist/meta.json to use `destDirName` inside `completeMessage`.
=> Wrong directory name

package.json
This pull request allows windows users to run the tests.
```bash
ENV=prop command
```
doesn't work in windows. Introducing [`cross-env`](https://github.com/kentcdodds/cross-env) as a dependency fixes this.
=> allow tests to be run on windows

README.md, lib/generate.js, lib/options.js, test/e2e/mock-metadata-repo-js/meta.js, test/e2e/mock-metadata-repo-js/template/readme.md, test/e2e/test.js
I took a stab at #93. This PR allows a `meta.js` to be defined as a metadata file and additionally allows you to define handlebars helpers like this:
```js
// meta.js
helpers: {
lowercase: str => str.toLowerCase()
}
}
```
I also tried to document `meta.js` but i'm not sure if this is the best way. Let me know!
=> register handlebars helpers

bin/vue-init, package.json, test/e2e/test.js
Otherwise it would fail inside checkDistBranch function which expects
body to be an array.
Also fix linters and test.
=> Support for official templates to specify specific branch.

bin/vue-init
No need to check for forward slash when checking if path is local.
Fixes #104.
=> Windows fix for local templates.

lib/options.js, test/e2e/test.js
Possibly fix #140
The error happens when we use `meta.js` for a local template because the relative path for `require(...)` is relative to `__dirname`, not `process.cwd()`
=> Fix 'Cannot find module' error of meta.js when using local template

README.md, lib/generate.js, test/e2e/mock-meta-json/meta.json, test/e2e/mock-metadata-repo-js/meta.js, test/e2e/test.js
- users can generate more friendly `completeMessage`
- document `destDirName`
closes #125
=> Add and document `inPlace` property.

README.md
I had to do some hunting through packages and source code to figure out how to pull down the older 1.0 template. After figuring it out I thought it would be helpful to add the details to the readme. 
Merge if you see fit and thank you for creating this tool :)
=> Adds detail to the readme on installing a specific template version

package.json
Adds GitLab support, custom host support and fixes.
=> Upgrade download-git-repo to 0.2.1

package.json
`yarn` will link bin files in `package.json`.
This should fix #205 and #193.
Besides, due to `yarn` cached installed packages, if you have installed `vue-cli` before, please remove them from `.yarn-cache` and re-install it again.
=> Fix bin not exist when installed via yarn

bin/vue-init
Windows users have trouble using local templates when the the previous solution only checked for slash and not backslash or `path.sep`. With this new approach mac, linux and windows users can also use relative paths to the template:
``` shell
vue init ./myTemplate projectName
```
or
``` shell
vue init ../myTemplatesFolder/myTemplate projectName
```
Tested on Mac osx with node 6.2.2 both from local build and globally installed build, as well as Windows 8 with node 6.7.0 from local build.
=> Better local template handling with Windows compatability

README.md, lib/generate.js, test/e2e/mock-template-repo/meta.json, test/e2e/mock-template-repo/template/src/skip-one.vue, test/e2e/mock-template-repo/template/src/skip-two.vue, test/e2e/test.js
=> add skipInterpolation option to specify files that should skip rendering

lib/git-user.js
=> Escape string in git config user.name

lib/warnings.js
There are two problems (IMHO at least) with the current 2.x "warning":
* It's not an error per se, more like an information, so I changed the color to green instead of red.
* Grammar.
Since both happen in one line, I decided to merge them into one commit.
=> Minor improvements for 2.x warning

README.md
Closes #243
The `#` character has a special meaning in ZSH requiring the use of surrounding quotes
=> Add quotes around webpack#1.0

lib/options.js, test/e2e/mock-metadata-repo-js/meta.js, test/e2e/test.js
I see the #73 ,The add the validation for package name , it is really nice , but it will be overwritten the user custom validate function , so , I fix it.
=> add the package name custom validate to take effect

bin/vue-build, docs/build.md
example:
```js
filename: {
js: 'index.js',
css: 'style.css'
}
}
```
=> Support custom filenames

bin/vue-build, docs/build.md, package.json, yarn.lock
It's very common to put a `favicon.ico` in dist folder, adding a `copy-webpack-plugin` would make it easier and work out of the box since the main idea of `vue build` is `zero-config`. Everything in `./static` folder will be copied to `./dist`
=> Copy static folder

bin/vue-build, docs/build.md
To make it work with vue-play, we need to change the webpack config in config.js to something like:
```js
entry: {
app: './play/app.js',
preview: './play/preview.js'
},
// add hmr client to these entries
hmrEntries: ['app', 'preview'],
// produce html files for these entries
html: [
{title: 'Vue-Play Panel', chunks: ['app']},
{title: 'Vue-Play Preview', chunks: ['preview'], filename: 'preview.html'}
]
}
```
And this PR allows:
- `options.entry` to be undefined if using `--config`
- `options.html` can be an array
- use `options.hmrEntries` to add hmr client
=> Make it work with vue-play

README.md, appveyor.yml, bin/vue-init, lib/local-path.js, package.json, test/e2e/test.js, yarn.lock
Fixes #300 and #283.
Thanks @ajanes93 for opening a PR. Also thanks to @likun7981 for providing regex.
Only thing wrong in regex imho was assumption that windows drive letter can be of any length and thus `bitbucket:username/rep` was treated as local template. I fixed this in this PR and also added some tests.
I'm aware that running these tests on Windows won't pass because of `isAbsolute` used, but CircleCi runes on *nix so... I'm open to any suggestions.
@egoist what do you think?
=> Extract local path logic and add tests.

lib/generate.js, test/e2e/mock-error/meta.js, test/e2e/mock-error/template/readme.md, test/e2e/test.js
When handlebars gives an error, it doesn't contain the filename that is actually producing the error.
Should help solve problems like #401 
Instead of 
```
Parse error on line 21
```
We now have
```
[readme.md] Parse error on line 21
```
@egoist @zigomir Feel free to modify how the filename is included in the error message
=> Add filename when in handlebars errors

lib/ask.js, test/e2e/test.js
This fixes #382.
It checks if the answer type is `string`, and if it is, `replace`s `"` with `\"`, so it can be parsed as valid JSON.
=> Escape double quotes in string prompts

README.md, lib/generate.js, test/e2e/mock-metalsmith-custom-before-after/meta.js, test/e2e/mock-metalsmith-custom-before-after/template/readme.md, test/e2e/mock-metalsmith-custom/meta.js, test/e2e/mock-metalsmith-custom/template/readme.md, test/e2e/test.js
=> Add support for metalsmith builder hooks

bin/vue-init, package.json, yarn.lock
Remove the currently cached template when we are doing a download and generate.  
This helps to resolve #403 where using the --clone flag with private repos fails when the cached template directory already exists.
It also helps resolve #409 where init results in a template that is outdated.
=> clean cached template in downloadandgenerate

bin/vue-build
Closes #422 
This makes it easier to combine with the official webpack template
=> Add an alias from '@' to src

docs/build.md
=> salvage docs

README.md
The codebase is being modernized and the cli no longer works with node 4. 8 being stable, I think it's safe to drop support for version 4
=> docs: drop support for node 4

packages/@vue/babel-preset-app/index.js, packages/@vue/cli-service/lib/options.js
This fixes a typo in setting babel env options and in a comment.
=> fix typo {mdoule => module}

packages/@vue/cli/bin/vue.js
vue -h 
```
serve a .js or vue file in development mode with zero config
```
to
```
serve a .js or .vue file in development mode with zero config
```
Added a point, same to description of build command.
=> fix:misspell

packages/@vue/cli-service/lib/config/uglifyOptions.js
According to [this issue](https://github.com/mishoo/UglifyJS2/issues/1753), if we do not add the line of `mangle safari 10`, it will cause vue pages become blank page on iOS 10.
=> compatible with safari 10

packages/@vue/cli/lib/inspect.js
Use `basedir` to specify the initial search path for resolving the CLI service, since `cwd` is not a valid option property.
=> fix(inspect): correct usage of `resolve`

packages/@vue/cli-plugin-pwa/README.md, packages/@vue/cli-plugin-pwa/index.js, packages/@vue/cli-plugin-pwa/package.json
R: @yyx990803 & co.
See #717 for context.
Open question: should I also add something to the `README.md` for the template explaining which configuration options are supported, and how they map to the Workbox options? If so, is there an example of another template that has this written up in the format you're looking for?
=> feat: Use the Workbox webpack plugin in pwa template

package.json, packages/@vue/cli/lib/util/getVersions.js, packages/@vue/cli/lib/util/installDeps.js, packages/@vue/cli/lib/util/request.js, packages/@vue/cli/package.json, scripts/syncDeps.js
Closes #785
Axios has a [known issue](https://github.com/axios/axios/issues/658)
that causes requests to hang when accessing an HTTPS resource via a
proxy served over HTTP.  This changes out the axios dependency for the
[request](https://github.com/request/request) library. In order to keep
`async/await` conventions easy, I also dropped in the
[request-promise-native](https://github.com/request/request-promise-native)
dependency.
=> fix(request): Change axios lib for request

packages/@vue/cli-service/lib/config/base.js
I have EOT (upper cased) fonts in my project, which currently cause the compilation process to fail with vue-cli 3 alpha 11. This PR fixes the problem.
=> Add missing "EOT" (upper case) font extension.

docs/plugin-dev.md
Project options are specified in the `"vue"` field and not `"vue-cli"`
=> package.json project options

packages/@vue/babel-preset-app/index.js
Because if you set `useBuiltIns` to false we'll always fallback to `'usage'`.
=> Allow setting `useBuiltIns` to be `false`.

packages/@vue/cli-service/generator/template/public/index.html
Add some default content that can be seen by browsers where JavaScript
is disabled. See:
https://developers.google.com/web/tools/lighthouse/audits/no-js
Closes #854
=> Add default <noscript> content

packages/@vue/cli-plugin-unit-jest/generator/index.js
=> Remove map coverage.

docs/cli-service.md
Certainly not required, but knowing the `changeOrigin` option is available straight from your docs (as opposed to http-proxy-middleware's docs) might save devs some time.
=> Might be useful

packages/@vue/cli-plugin-e2e-cypress/generator/template/test/e2e/specs/test.js, packages/@vue/cli-plugin-e2e-cypress/index.js, packages/@vue/cli-plugin-e2e-cypress/package.json
The major version bump in Cypress doesn't include any configuration-related breaking changes. [See here](https://docs.cypress.io/guides/references/changelog.html#2-0-0) for details.
=> Upgrade cypress and properly set base url (resolve #847)

packages/@vue/cli-plugin-pwa/package.json, yarn.lock
This PR is twofold:
- Upgrade workbox-webpack-plugin to the latest released version of 3.0.0-beta.1
- Declare a more relaxed dependency on the workbox-webpack-plugin in order to avoid issues like #893 
Closes #893
=> feat(cli-plugin-pwa): Upgrade workbox-webpack-plugin to 3.0.0-beta.1

docs/webpack.md
It's no problem if this doesn't make it in, but I thought an example of modifying a loader's options might be useful for the Webpack configuration page.
=> chainWebpack & merge example of modifying loader options

packages/@vue/cli-service/lib/config/base.js
Just a small typo in the naming of a webpack-chain plugin option:
`firendly-errors` => `friendly-errors`
=> Fix typo in plugin name

packages/@vue/cli/bin/vue.js
resolves #849.
I read quick through the dependency `commander.js`'s README and source code, finding that it hasn't implemented this yet. Here is a workaround, but I am not sure if it has a side effect.
=> Output help information on unknown CLI commands

docs/env.md, packages/@vue/cli-service/lib/commands/build/index.js
Hiyya!
I ran into a need to use development environment variables in a build (specifically, needing to use a development API server on our development app server). Eventually I connected the dots, but thought it would be useful to add to the docs.
Additionally, even when running in development mode, the "Building for.." message was hard coded to display "production", added in the `arg.mode` variable.
Let me know if you have any questions! First PR really with an open source project :)
=> Add docs build mode env

packages/@vue/cli-service/lib/commands/serve.js
(#828)Webpack dev client could not work when server is behind NAT network.
This is because localUrlForBrowser is not equal to server's public url.
Now, without passing localUrlForBrowser to dev client, the dev client tries to connect to browser's window.location.
=> fix(request): dev server behind NAT network

docs/css.md, packages/@vue/cli-service/__tests__/css.spec.js, packages/@vue/cli-service/lib/config/css.js, packages/@vue/cli-service/lib/options.js, packages/@vue/cli-service/lib/webpack/CSSLoaderResolver.js
Changed the vue config to take a user input option for CSS module localIdentName and default back to initial localIdentName ([name]_[local]__[hash:base64:5])
=> feat(cli-service): Add CSS Module localIdentName to vue config

packages/@vue/cli-plugin-typescript/generator/index.js
There was one more typo with the "test" folder regarding
e2e. It was preventing cypress from running properly.
=> fix(TypeScript e2e): end to end test(s) folder

packages/@vue/cli/lib/create.js
=> fix(cli): creating project in current directory

packages/@vue/cli-plugin-pwa/index.js
This PR fixes https://github.com/vuejs/vue-cli/issues/891.
=> fix(cli-plugin-pwa): Set cacheid in GenerateSW mode only

packages/@vue/cli-shared-utils/lib/logger.js, packages/@vue/cli/lib/Creator.js, packages/@vue/cli/lib/Generator.js, packages/@vue/cli/lib/GeneratorAPI.js, packages/@vue/cli/lib/invoke.js, packages/@vue/cli/lib/util/pluginResolution.js
Fix #832 
Generator code example:
```js
api.exitLog('Test')
api.exitLog()
api.exitLog('Test', 'info')
api.exitLog()
api.exitLog('Test', 'done')
api.exitLog()
api.exitLog('Test', 'warn')
api.exitLog()
api.exitLog('Test', 'error')
```
=> Feat exit message

packages/@vue/cli-test-utils/launchPuppeteer.js, packages/@vue/cli-test-utils/package.json
This prevent download two version of Puppeteer. I can not run test properly even without this change, so I do not know if this can break anything.
=> Use same Puppeteer like in main package.json

packages/@vue/cli-service/lib/util/prepareProxy.js
We have a use case where I want to override `onProxyReq` within `vue.config.js`.
=> Allow user to define onProxyReq

packages/@vue/cli-plugin-typescript/generator/template/tsconfig.json
This gives you
1. Babel's downleveling for ESNext-style constructs if enabled.
2. The ability to use `import()` expressions.
=> Use `esnext` targets for downleveling and modules.

packages/@vue/cli/lib/invoke.js
Using `vue invoke` was breaking all binary files because of encoding issues
issue #1037
=> fix(invoke): issue #1037 invoke binary files

packages/@vue/cli-ui/src/views/ProjectPluginsAdd.vue
Both `keywords` and `computedKeywords` work, but `computedKeywords` will make sure this only matches for those with the correct name, not all with that keyword. 
Thanks!
cc @Akryum
=> chore(UI): use computedKeywords to filter the search

packages/@vue/babel-preset-app/index.js
Adding option `decoratorsLegacy: true` in `@babel/preset-stage-2` for fixing this error :
```
Module build failed: Error: [BABEL] /path/to/project/src/main.js: The new decorators proposal is not supported yet. You must pass the `"decoratorsLegacy": true` option to @babel/preset-stage-2 (While processing: "/path/to/node_modules/@vue/babel-preset-app/index.js$1")
```
=> Fixing "The new decorators proposal is not supported yet."

packages/@vue/cli-plugin-pwa/README.md
If these options aren't set, HtmlPwaPlugin will use the default Vue colors for populating index.html, which wasn't otherwise obvious to me as I had already set them in manifest.json. Thanks!
=> Document themeColor and msTileColor in @vue/cli-plugin-pwa

docs/webpack.md
Added an example how to replace an existing Base Loader with a new Loader to the webpack docs.
=> Update Webpack.md: example how to replace an existing base loader

packages/@vue/cli-plugin-e2e-cypress/generator/template/tests/e2e/specs/test.js
The Cypress initial test visits Cypress's sample app, Kitchen Sink.  It seems for the initial Vue app, it should visit the app root url (or home/main/first page?).
=> Update Cypress test.js test it block description

packages/@vue/cli-plugin-e2e-nightwatch/index.js
Hi,
This allow to run e2e with a custom config file `vue-cli-service e2e --config nightwatch.config.js` instead of using the internal Nightwatch config.
My use-cases is using e2e nightwatch with a custom integration like [nightwatch-cucumber](https://github.com/mucsi96/nightwatch-cucumber) which seems not working with the default behavior.
```js
// nightwatch.config.js
require('nightwatch-cucumber')({}) // is ignored when using the internal Nightwatch config.
...
}
```
Thanks!
=> feat(e2e nightwatch): allow setting cli `config` option.

docs/webpack.md
Even though this should have been obvious I had a bit of trouble figuring this out today so I figured I'd update the docs to help others.  
I wasn't sure if it made sense to leave the original generic example in place or remove it... so I left it in place and added example below.   I'm more than happy to update as necessary based on feedback.
Thanks
=> Minor doc change:  Show example in Advanced Webpack config section

packages/@vue/cli-test-utils/package.json, packages/@vue/cli-test-utils/serveWithPuppeteer.js
fix "Protocol error (Page.navigate): Cannot navigate to invalid URL undefined" error when running test in vscode terminal(zsh)
=> test: fix "Protocol error" error when running test in vscode terminal

packages/@vue/cli-plugin-typescript/__tests__/tsGenerator.spec.js, packages/@vue/cli-plugin-typescript/generator/template/tsconfig.json
Using the TypeScript plugin without any unit testing plugin.
will generate an invalid JSON file.
See the trailing comma ?
``` json
"types": [
"node",
]
```
=> fix(tsconfig.json): Typescript Plugin generating invalid json

packages/@vue/cli/__tests__/invoke.spec.js, packages/@vue/cli/lib/Generator.js, packages/@vue/cli/lib/util/writeFileTree.js
If a plugin is used within the vue create command,
It will be able to delete and rename files.
This is enabling the same tools for invoking 3rd party plugins.
#1048 is solved in this PR
=> feat(invoke): allow invoke to replace/rename/delete files

packages/@vue/cli-plugin-babel/README.md, packages/@vue/cli-plugin-babel/index.js, packages/@vue/cli-plugin-typescript/README.md, packages/@vue/cli-plugin-typescript/index.js
Commit 64b45157 changed the test directory but this change was not applied to the babel and typescript plugins.
=> Fix(typescript, babel) - Fix tests path for babel and typescript plugins

packages/@vue/cli-service/lib/config/prod.js
Add [name] to file name build output. This makes chunk name configurable with 
`/* webpackChunkName: "xyz" */`
=> fix: Add name to chunk file output (#1167)

packages/@vue/cli-service/lib/util/prepareProxy.js
In the current version of vue-cli, one is able to use the `onProxyReq` callback to modify the request. This is useful for adding things such as client IDs and secrets for OAuth when one can't keep them secure client-side.
```js
target: process.env.PROXY_URL,
onProxyReq(proxyReq, req, res) {
console.log(proxyReq, req, res)
if (req.path == '/oauth/token') {
req.body.client_id = process.env.CLIENT_ID
req.body.client_secret = process.env.CLIENT_SECRET
}
},
}
```
The currently tagged beta 6 doesn't use a user-provided `onProxyReq` callback. The dev branch does, but it does not pass all the parameters to it: 
```js
onProxyReq (proxyReq) {
if (usersOnProxyReq) {
usersOnProxyReq(proxyReq)
}
// ...
},
```
It would be ideal if we could keep this functionality. :-)
=> Pass all parameters to onProxyReq in proxy configuration

packages/@vue/cli-test-utils/assertPromptModule.js, packages/@vue/cli/bin/vue.js, packages/@vue/cli/lib/Creator.js, packages/@vue/cli/lib/promptModules/__tests__/babel.spec.js, packages/@vue/cli/lib/promptModules/__tests__/cssPreprocessors.spec.js, packages/@vue/cli/lib/promptModules/__tests__/e2e.spec.js, packages/@vue/cli/lib/promptModules/__tests__/linter.spec.js, packages/@vue/cli/lib/promptModules/__tests__/pwa.spec.js, packages/@vue/cli/lib/promptModules/__tests__/router.spec.js, packages/@vue/cli/lib/promptModules/__tests__/typescript.spec.js, packages/@vue/cli/lib/promptModules/__tests__/unit.spec.js, packages/@vue/cli/lib/promptModules/__tests__/vuex.spec.js
I was not sure how to write a test for this feature, but I have tested it manually. Any input on how to write the test would be appreciated
=> Support custom initial commit message

packages/@vue/cli-service/lib/commands/inspect.js, packages/@vue/cli/bin/vue.js, packages/@vue/cli/lib/inspect.js
-v or --verbose can be used to output full function definitions. fixes #1157
=> add a --verbose flag to inspect command

packages/@vue/cli-service/lib/commands/build/resolveWcConfig.js, packages/@vue/cli-service/lib/commands/build/resolveWcEntry.js
fixes #1146
Fixes issue that prevented single entry wc builds from honoring the `--name` argument.
The build process would just use the entry file name for the component name when registering the component previously
=> feat(build): honor custom component name for single file wc builds

packages/@vue/cli/__tests__/Generator.spec.js, packages/@vue/cli/lib/util/mergeDeps.js
npm supports multiple "version" strings when declaring deps in your
`package.json`. This PR is an attempt to support some of these other
formats in a plugin specification, while retaining the smart version
merging. If a semver range can be extracted, it will be used for
version conflict resolution. If not, a warning will be displayed to
the developer
=> feat(plugin-api): allow non-semver versioned dependencies (#1177)

packages/@vue/cli-plugin-e2e-nightwatch/README.md
README for `cli-plugin-e2e-cypress` had a broken link to the NightwatchJS site.
=> Fix link to NightwatchJS site in README

packages/@vue/cli-test-utils/createTestProject.js
This warning would have saved me a fair bit of time during testing because test projects are not cleaned up between individual tests and I kept stepping on previous tests. If this is a dumb idea then you can just reject and ignore
=> feat(test): warn developers when they re-use a test project name

packages/@vue/cli/lib/Creator.js, packages/@vue/cli/lib/util/readLocalPreset.js, packages/@vue/cli/package.json
I wasn't sure how to write a test for this (didn't see any for testing the remote preset fetching either), so I didn't write one...
=> feat(cli): allow local .json files for presets (#1068)

packages/@vue/cli-plugin-typescript/lib/tslint.js
I ran `vue create test-app` and selected TypeScript and TSLint.
At the end I got the following output:
```
🎉  Successfully created project test-app.
👉  Get started with the following commands:
$ yarn serve
```
The command `$ cd test-app` was missing, because tslint changed the working directory.
=> fix(tslint): don't change working directory

packages/@vue/cli-plugin-unit-jest/README.md
`vue add unit-jest` fails with following output
```
> vue add unit-jest
📦  Installing vue-cli-plugin-unit-jest...
yarn add v1.6.0
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find package "vue-cli-plugin-unit-jest" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
=> docs: correct vue add command in readme

packages/@vue/cli/lib/util/getVersions.js, packages/@vue/cli/lib/util/installDeps.js, packages/@vue/cli/lib/util/registries.js, packages/@vue/cli/lib/util/shouldUseTaobao.js
If a developer from China first use vue-cli, `useTaobaoRegistry` will be undefined. Then [getVersions](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli/lib/util/getVersions.js#L13) will not use the right registry.
=> feat: ask for whether to use taobao when get versions

packages/@vue/cli-service/lib/config/base.js, packages/@vue/cli-service/lib/config/css.js, packages/@vue/cli-service/lib/config/prod.js, packages/@vue/cli-service/lib/options.js, packages/@vue/cli-service/lib/util/getAssetPath.js
``` js
// vue.config.js
outputDir: 'dist',
assetDir: 'static'
}
```
output files:
```
- dist
- static
- js
app.js
- css
app.css
- img
image.png
index.html
```
=> feat(cli-service): add assetsDir option to specify assets directory

packages/@vue/cli-plugin-eslint/index.js, packages/@vue/cli-plugin-eslint/lint.js
add a `--max-warnings` and `--max-errors` option for cli-plugin-eslint to specify number of warnings or errors to trigger build failed. 
usage:
```bash
vue-cli-service lint --max-warnings 10 --max-errors 2
```
#1268 
https://eslint.org/docs/user-guide/command-line-interface#options
=> feat(lint): add max-warnings for cli-plugin-eslint, close #1268

packages/@vue/cli-plugin-e2e-cypress/README.md
Improve info about env variables according to discussion in #1290.
=> Update README with env variables info

docs/cli-service.md, packages/@vue/cli-service/lib/commands/build/index.js
Closes #1317 
Not sure if `--watch` can be an option or do we need to add it as switch / flag. Documentation is intentionally minimal, open for suggestions.
=> feat(build): add 'watch' option

packages/@vue/cli-plugin-pwa/generator/index.js, packages/@vue/cli-plugin-typescript/generator/convert.js, packages/@vue/cli-plugin-typescript/generator/index.js, packages/@vue/cli-service/generator/router/index.js, packages/@vue/cli-service/generator/vuex/index.js, packages/@vue/cli/lib/Generator.js, packages/@vue/cli/lib/GeneratorAPI.js, packages/@vue/cli/lib/add.js, packages/@vue/cli/lib/invoke.js
- `vue add router` & `vue add vuex` now works in typescript projects
- `router`, `vuex` and `pwa` JS files are converted to TS after invocation
- `api.entryFile` is either `src/main.js` or `src/main.ts`
- `api.invoking`
=> Improve invocation of builtin plugins in TypeScript projects

packages/@vue/cli-plugin-eslint/README.md
Minor fix: it's `config.module.rule('eslint')` not `config.rule('eslint')`
=> Update eslint webpack-chain documentation

docs/config.md, packages/@vue/cli-plugin-eslint/README.md
Catch up docs that were forgotten in pervious PR (#1289, #1322).
=> docs: update docs for assetsDir, --max-errors and --max-warnings

packages/@vue/cli-service/generator/template/src/components/HelloWorld.vue
Fixed the wrong link to vuex page in `HelloWorld.vue`
=> fix: 404 link to vuex intro page

docs/config.md
adding default for disableHostCheck since there isn't any documentation around this specific feature for vue-cli (I found a react-webpack config StackOverflow answer that worked)
=> Adding disableHostCheck default value

docs/cli-service.md, docs/cli.md, packages/@vue/cli-service/lib/commands/serve.js, packages/@vue/cli-service/lib/options.js, packages/@vue/cli-service/package.json, packages/@vue/cli/bin/vue.js
This feature will copy the local url to the clipboard. 
I use this feature of https://poi.js.org/ quite a lot.
It's not as aggressive as `--open` but just as convenient :)
=> Add a --copy option to the serve command

packages/@vue/cli-service/lib/commands/serve.js
In my scenario, the page is being served by PHP and the URL to the bundle is pointed directly to the webpack dev server. 
So, the website is being served at `http://my-project.test` and the script is pointing to `http://localhost:8080/app.js`. 
By specifying `?/sockjs-node` when including the webpack dev server client, it is forcing the sockjs server to be on the same domain as the page. Because of https://github.com/webpack/webpack-dev-server/blob/ab4eeb007283fdf3e8950ff1f3ff8150a4812061/client-src/default/index.js#L30
I need the __resourceQuery to be empty so that it gets the URL for the sockjs server from the `getCurrentScriptSource`
This PR shouldn't break for anyone already using `baseUrl`. 
Or if there is another way to achieve what I need, please let me know!
Also required by #1390 …
=> Only provide baseUrl fix if baseUrl provided

packages/@vue/cli-plugin-eslint/ui.js
See #1440 changing 'vue/html-indent': ['error', 'tab']` to match the vue/html-indent specs
I hope this is where the fix is. If not no harm in closing this.
Thanks for the great work!
=> Changing tabs to tab for vue/html-indent

packages/@vue/cli-service/ui.js
I was writing locale for vue-cli ui and found this mistake in the parameter-prompt in project's `build` task page.
Well, then another one.
=> fix(ui): correct i18n mistake

packages/@vue/cli-ui/locales/en.json, packages/@vue/cli-ui/src/graphql-api/connectors/plugins.js, packages/@vue/cli-ui/src/graphql-api/schema/plugin.js, packages/@vue/cli-ui/src/graphql/pluginsUpdate.gql, packages/@vue/cli-ui/src/views/ProjectPlugins.vue
A button to update all vue-cli plugins to wanted version if needed
=> Update all plugin to wanted version Button

packages/@vue/cli/lib/options.js
`vue-cli` now uses the following hierarchy for hosting its rc file:
* `VUE_CLI_CONFIG_PATH`
* `XDG_CONFIG_HOME/vue/.vuerc`
* `HOME/.config/vue/.vuerc`
* `HOME/.vuerc`
Let me know if you need something changed
I would like to point out that the middle 2 paths probably shouldn't be hidden files. Left that up to the devs though.
closes #1325
=> feat(xdg-compliance): rc file location hierarchy

packages/@vue/cli-service/lib/commands/build/index.js
As suggested on #1446, this PR adds support to a `--no-clean` flag on the `build` command to prevent the removal of the `dist` directory before building the project.
PS: I'm not sure if the `--help` message is good enough.
=> feat(cli-service): support --no-clean flag

packages/@vue/cli-plugin-typescript/lib/tslint.js
LInt tsx files on default as `cli-plugin-typescript` supports `.tsx`.
PS: Do we have a chance to support tslint `--project` option here?
=> feat(lint): default to lint tsx files 

packages/@vue/cli-service/lib/commands/serve.js
As [https://github.com/vuejs/vue-cli/issues/1472#issuecomment-394755323](https://github.com/vuejs/vue-cli/issues/1472#issuecomment-394755323) mentioned.
=> fix(cli-service): make sockjs url fixed with hostname

packages/@vue/cli-service/__tests__/Service.spec.js, packages/@vue/cli-service/lib/Service.js, packages/@vue/cli-service/lib/util/loadEnv.js
=> fix(env): preserve existing env vars so load in reverse order.

packages/@vue/cli/lib/promptModules/cssPreprocessors.js
Don't quite know if redirecting to GitHub instead of cli.vuejs.or is an expected behaviour, please feel free to update by this one if you want to link to GitHub https://github.com/vuejs/vue-cli/blob/dev/docs/guide/css.md
Thanks!
=> CSS Pre-processors "More info" link leads to 404

packages/@vue/cli-ui/locales/en.json, packages/@vue/cli-ui/src/graphql-api/connectors/projects.js, packages/@vue/cli-ui/src/graphql-api/schema/project.js, packages/@vue/cli-ui/src/views/ProjectCreate.vue
Implements #1482.
Hi! I went ahead and implemented support on UI to specify a custom initial git commit message and skip git initialization.
I'm not sure if using a single switch for both actions and skip git initialization if the switch is on but no message is specified is the best approach, I can switch to something else like having different switches if it seems a better option.
=> feat: Allow git commit message through UI

packages/@vue/cli-service/lib/commands/serve.js
See: https://github.com/vuejs/vue-cli/issues/1525
=> Use devServer.public to build sockjsUrl, if defined.

package.json
Update to `0.10.1` to get some very small UI enhancement (mainly for `lastUpdated`).
And I also want to **sell** two features here.
From now on, we can be free to use `relative path` for markdown file reference:
**e.g.**
``` md
[`transpileDependencies`](../config/#transpiledependencies)
```
Can be replaced by:
``` md
[`transpileDependencies`](../config/README.md#transpiledependencies)
```
The first convention assumes that the user uses the VuePress, and as a source file, it uses the runtime path, so I personally prefer the second one, mainly that it keeps the `jump-to-definition` in editor.
> Complete use case test [here](https://github.com/vuejs/vuepress/blob/master/test/markdown/link.spec.js).
Now we can easily add a `version`/`status`  to a new feature at docs.
**e.g.**
- Input
``` md …
```
=> docs: bump vuepress

packages/@vue/cli-service/__tests__/modernMode.spec.js, packages/@vue/cli-service/lib/webpack/ModernModePlugin.js
Otherwise, things like BasicAuth won't work.
See: https://github.com/vuejs/vue-cli/issues/1656
=> fix(modern): send credentials when loading script modules.

docs/guide/cli-service.md
Change `update-to-date` to `up-to-date`. It sounded weird and doesn't appear in the dictionary: https://www.merriam-webster.com/dictionary/update-to-date
=> Wording change in the cli-service guide

docs/dev-guide/plugin-dev.md, packages/@vue/cli/lib/GeneratorAPI.js
=> WIP: fix underscore escaping for dotfiles

packages/@vue/cli/lib/Creator.js, packages/@vue/cli/lib/util/generateReadme.js
Closes #1675.
As suggested in the issue, this PR adds a step to the `vue create` process to create a `README.md` based on the project's `package.json`.
I got some descriptions from the `cli-ui` package and created generic ones to the others. Please let me know if I missed any script/description.
Regarding the code, I used `Array.join`s to try to keep the code as clean as possible. I'm not sure if it's the best solution, but using only template strings in this situation is really messy in my opinion.
PS: If tests are necessary to this feature, let me know as well.
=> feature: Generating README.md

packages/@vue/cli-plugin-pwa/generator/template/public/robots.txt
Lighthouse 3.0 issue while passing a new audit:
"Ensure that your site's robots.txt file is properly formed so that search bots can crawl your site."
Ref: https://developers.google.com/web/updates/2018/05/lighthouse3
=> Add robots.txt

docs/guide/cli-service.md
This argument is present in the help text but not in the docs.
=> docs: add entry argument to serve command

packages/@vue/cli/bin/vue.js
If the legacy `vue init` API is still necessary to be compatible with, it is also necessary to keep the `--offline` option : )
=> chore: restore --offline option for legacy vue init API

packages/@vue/cli-plugin-unit-jest/generator/index.js
This PR fixes the bug in generated configuration of Jest testing framework. Issue was that when you create project using vue-cli and select to use jest configuration regex would be setup to look under a folder within tests/unit directory. This change makes it look for files also directly in tests/unit directory.
Without this change template test `HelloWorld.spec.js` would also fail.
Closes #1686
=> Fix issue with Jest configuration regex not matching template.

packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js, packages/@vue/babel-preset-app/index.js
=> fix(babel): default polyfills need es6.array.iterator for IE

docs/config/README.md
* Adds example to disable hashed asset filenames, as discussed in #1649 
* Adds example of disabling the generation of `index.html`, as discussed in #1478 
* Adds a tip about not needing to use `assetsDir` when overriding `filename` or `chunkFilename`, as discussed in #1753
=> Add configuration examples section

packages/@vue/cli-service/lib/webpack/ModernModePlugin.js
when use webpack `htmlWebpackIncludeAssetsPlugin` include script. the script has no attributes, and build throw error.
=> fix: when script has no attributes

packages/@vue/cli/__tests__/Generator.spec.js, packages/@vue/cli/lib/util/injectImportsAndOptions.js
This gives more flexibility for the plugins.
=> Don't allow duplicate injections of import statements and root options by plugins

docs/config/README.md
=> docs(css.extract): Explain "always-off" in development mode

packages/@vue/cli/bin/vue.js
Makes the Vue command structure more consistent. Easier to read over what they are doing during development.
=> refactor: consistent command structure

docs/guide/deployment.md
=> docs: update description on how to deploy project to surge.sh

packages/@vue/cli-service/lib/webpack/ModernModePlugin.js
The modern plugin will fail for multi page applications if the output is in sub directories. For example:
```
index.html
app2/index.html
```
This makes sure to append the directory to the `legacy-assets-index.html.json` files and make sure the sub-directories are created if needed. Solves my problems referenced in https://github.com/vuejs/vue-cli/issues/1683
=> Fix modern plugin when building multi page applications with output in sub directories

packages/@vue/cli/lib/Creator.js
close #1871 
I could also provide a fix by adding a validator to here https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli/lib/Creator.js#L395 Let me know which one you prefer.
=> fix(resolvePreset): Gives priority to ~/.vuerc presets

docs/.vuepress/config.js, docs/config/README.md, docs/guide/README.md, docs/guide/html-and-static-assets.md, docs/guide/installation.md, packages/@vue/eslint-config-airbnb/README.md, packages/@vue/eslint-config-prettier/README.md, packages/@vue/eslint-config-standard/README.md, packages/@vue/eslint-config-typescript/README.md, packages/@vue/eslint-config-typescript/index.js
=> docs: add description to extendable eslint configs

packages/@vue/cli/bin/vue.js, packages/@vue/cli/lib/Creator.js
=> fix(create): fix shouldInitGit check

docs/guide/browser-compatibility.md
The documentation was using babel-preset-env instead of babel-preset-app
=> Fix babel-preset-app link

packages/@vue/cli/lib/util/generateReadme.js
For example, if my preset has vue-cli-plugin-s3-deploy, then when the project is created, my README contains the following:
````md
```
npm run deploy
```
````
While my package.json has the following:
```js
"scripts": {
"deploy": "vue-cli-service s3-deploy"
}
```
=> fix(create): Commands added by plugin (through preset) won't have description in README

packages/@vue/cli/lib/Creator.js, packages/@vue/cli/lib/add.js, packages/@vue/cli/lib/invoke.js
Basically, the current logging is a bit haphazard with sometimes having a gap of 2 empty lines and sometimes with a gap of 1 empty line. This PR makes it consistent.
1. After running package install command, we don't need a new `log()`
2. Prettified invoking generator log
3. Made sure there's an empty line before the output of package install
=> chore: Make the logging consistent and pretty

packages/@vue/cli-service/__tests__/buildLib.spec.js, packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js
Solves #1941. This allows tweaking the webpack config for different targets when building libraries.
=> feat(build): set output target before configureWebpack, close #1941

packages/@vue/cli-plugin-babel/README.md
Replace mention of .babelrc with babel.config.js in README as we now strongly recommend the latter
=> docs(cli-plugin-babel): Fix config file name

packages/@vue/cli/bin/vue.js
From `this version of vue-clirequires Node >=8.9.`
To `this version of vue-cli requires Node >=8.9.`
=> Fix a message in checkNodeVersion.

packages/@vue/cli-plugin-eslint/__tests__/ui.spec.js, packages/@vue/cli-plugin-eslint/ui/configDescriptor.js, packages/@vue/cli-ui/locales/en.json
Since the base rules are necessary to get ESLint parsing to work properly for Vue and not really something users will typically configure, I think it makes sense not to show them in the UI.
=> Remove base rules from ESLint UI

packages/@vue/cli-plugin-typescript/__tests__/tsGenerator.spec.js, packages/@vue/cli-plugin-typescript/generator/template/tsconfig.json
cli-plugin-typescript without a tests plugin generates tsconfig.json with incorrect spacing:
```json
"types": [
"node"    ],
```
This fixes the formatting and tests each configuration:
```json
"types": [
"node"
],
```
=> fix(cli-plugin-typescript): tsconfig whitespace

packages/@vue/cli-plugin-typescript/generator/template/tsconfig.json
TypeScript was complaining about `Array.includes` not existing. Having `esnext` as a target isn't sufficient.
=> Include esnext in lib

docs/guide/html-and-static-assets.md, docs/zh/guide/html-and-static-assets.md
This fixes the following issues:
* The option is `fileBlacklist`, not `fileBlackList` (lowercase "L").
* This option is not specified by default, so you have to make sure it exists before calling `push` on it.
* You have to use `options[0]` to access the first options array member to get to the actual plugin options object (I'm not sure if this is documented better elsewhere?).
=> Fix issues with prefetch override docs

docs/zh/guide/webpack.md
fix a wrong spelling of "loader".
=> (docs): fix a wrong spelling.

docs/guide/creating-a-project.md
Ordered in the same way as they are shown in the CLI list 
Based on: https://github.com/vuejs/vue-cli/commit/c6ca93e0dd9c01e9ce9550fa52f475cf410d5202 for #2030
=> docs: added --bare / -b  && --no-git / -n flags 

packages/@vue/cli-service/generator/router/template/src/views/Home.vue, packages/@vue/cli-service/generator/template/public/index.html, packages/@vue/cli-service/generator/template/src/App.vue, packages/@vue/cli-service/generator/template/src/components/HelloWorld.vue
With some minor changes, we can significantly increase the Lighthouse score of the vue-cli default application. Considering people will use the generated app as a guide, I think it's worth following best practices. Plus it makes the pwa plugin look better to earn a good score by default :) This was addressed in #1532 though so feel free to close if you don't feel it's necessary. 
Before:
After:
=> Lighthouse PWA audit

packages/@vue/eslint-config-typescript/package.json
The version [18.0.0](https://github.com/eslint/typescript-eslint-parser/releases/tag/v18.0.0) add support for TypeScript 3.
=> chore(deps): update typescript-eslint-parser to ^18.0.0

package.json
In commit [3b21fad86](https://github.com/vuejs/vue-cli/commit/3b21fad86) js files were added to the `__tests__` folder and jest was interpreting them as test suites. Not finding any tests in them, it made the following ci command fail 
```
yarn test
```
Therefore, AppVeyor is saying that the tests are not passing.
Passing now
=> fix(ci): add testMatch because of mock-preset

docs/zh/guide/webpack.md
原来的翻译有一点歧义，可能让人误以为 webpack 内部在使用 [webpack-chain](https://github.com/mozilla-neutrino/webpack-chain)。修改了一下让意思更准确。
=> 修正 webpack.md 中文翻译

docs/config/README.md, packages/@vue/cli-service/__tests__/Service.spec.js, packages/@vue/cli-service/lib/Service.js
fix #2153
When normalizing "./foo/bar" baseurl option, the code was first removing the "./" to make it relative (foo/bar).
Then it was making sure that, if it was starting with neither a `/` nor a `.`, ensure it would start with a `/`, disallowing any relative baseUrl.
I think those two normalizations should be reversed to allow for `./foo/bar` to become `foo/bar/`.
=> fix: allow relative baseUrl

package.json
After adding the testMatch parameter,
jest is now picking up files as test suites that it should not:
example:
`cli-plugin-unit-mocha/generator/template/tests/unit/HelloWorld.spec.js`
This commit makes jest match only files in `__tests__`
=> fix(ci): make matcher more precise

docs/config/README.md, docs/zh/config/README.md
```
See also: [CORS settings attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes)
```
- setting -> settings
- zh docs:  CROS -> CORS
=> docs: fix typo & tweak link name

docs/guide/deployment.md
Contains instructions to deploy to bitbucket cloud, inspired and adapted from the github pages documentation
=> Add bitbucket cloud deployment documentation

packages/@vue/cli-ui/apollo-server/connectors/tasks.js
Fixes #2096 .
See [this comment](https://github.com/vuejs/vue-cli/issues/2096#issuecomment-414333317):
> Another approach would be to consider the command execution duration - if we're on Windows and we get a `ENOENT` after more than 1 second, it's most probably a "false" one (this will not cover the case where you press on start and immediately on stop; a workaround would be to disable the button for 1s after starting a task).
=> fix(cli-ui): ignore "false" ENOENT errors on Windows

packages/@vue/cli-ui/README.md
This should _improve_ actual README with more user-friendly notes for starting local development and explaining how to run tests in local aswell.
=> docs(cli-ui): add more notes for local development

packages/@vue/cli/lib/util/writeFileTree.js
closes #2275
Iterating over async functions would put too many write calls in I/O
queue in the same time, leading to weird bugs.
(On my computer this bug appears once the number of `fs.writeFile` calls > 10)
=> fix: use sync fs methods in writeFileTree

packages/@vue/cli-service/lib/commands/serve.js
Will fix issue setting openPage in vue.config.js, with the expected format:
```
devServer: {
open: true,
openPage: 'some-uri',
}
```
This should work in either the root devServer field, or within the configureWebpack.devServer field.
=> fix(serve): respect devServer.openPage field

packages/@vue/cli-service/lib/config/app.js
closes #1996
------
1. Hash collision is normal in multi page mode (they might share a `index.html` chunk).
2. Otherwise, chunks contain only 1 module in most cases, making the aesthetics improvement unnecessary.
=> fix: revert named-chunks nameResolver algorithm

packages/@vue/cli-service/lib/config/base.js
to circumvent a Safari caching issue
closes #2391, #1132
=> fix: add hash to filename in development mode

packages/@vue/cli-plugin-babel/__tests__/transpileDependencies.spec.js, packages/@vue/cli-plugin-babel/index.js
=> fix: fix scoped modules exclusion on windows

packages/@vue/cli/__tests__/Generator.spec.js, packages/@vue/cli/lib/GeneratorAPI.js
Fixes issue with dotfile rename caused by Globby returning forward slashes instead of OS specific.
=> fix(plugin api): fix generator dotfile rename for Windows.

packages/@vue/cli-plugin-unit-jest/generator/index.js
Avoids getting a Jest unexpected token exception when requiring SVG files in template.
=> fix: (cli-plugin-unit-jest) also process SVG files with jest-transform-stub

packages/@vue/cli-ui/src/components/TopBar.vue
Currently the project dropdown does not have left and right padding, it is removed here:
https://github.com/vuejs/vue-cli/blob/714d12ab1e2bbb6148f7f30b65f87e6ea743b36d/packages/%40vue/cli-ui/src/components/TopBar.vue#L200-L202
When the project name is short it is not a problem as seen here:
... but when the project name is longer then it does not look that nice:
My suggestion is to get rid of that padding reset, so it looks much better:
=> Removed padding reset from current project dropdown

packages/@vue/cli-service/lib/commands/build/setPublicPath.js
Allow Webpack to process this file as an ES Module, which allows
concatenating using ModuleConcatenationPlugin, resulting in a slightly
smaller bundle and removes the overhead of a runtime `require()`.
=> Add module concatenation hint

docs/zh/config/README.md, docs/zh/dev-guide/ui-api.md, docs/zh/guide/build-targets.md, docs/zh/guide/cli-service.md, docs/zh/guide/deployment.md, docs/zh/guide/html-and-static-assets.md, docs/zh/guide/mode-and-env.md
Ref: https://github.com/vuejs/vue-cli/compare/686ec259...78c68772
Deployment 未完全写好，固暂时保留了英文
/ping @Justineo 
Thanks.
=> docs(zh): keep updated

packages/@vue/cli/lib/Generator.js, packages/@vue/cli/lib/util/sortObject.js
The reason behind this PR is that my package.json is being rewritten everytime when I am running `vue invoke`. The keys which were not specified in the keyOrder are being inconsistent and changing everytime I am running `vue invoke`. This PR fixes that issue.
=> fix(cli): Make sortObject consistent even when keyOrder is given

packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js
bug fix: vue-cli-service build --target lib ignores externals in vue.config.js
=> PR to fix bug in issue#2646

packages/@vue/cli-service-global/lib/globalConfigPlugin.js
> this PR fixes #2654
By including the parserOptions as we do when we create an actual eslint config for normal projects, we get ESnext support for eslint during `vue serve`
=> fix(cli-service-global): fix eslint-loader config (close #2654)

packages/@vue/cli/lib/Creator.js, packages/@vue/cli/lib/util/sortObject.js
Hi,
Thanks for the new cli, it's really easy to use!
However, this days, when I update to v3.0.4. There is a problem of the invoke order of my preset plugins.
For example, here is the plugins config of preset.json:
```json
{
"plugins": {
"@vue/cli-plugin-babel": {},
"@dd/vue-cli-plugin-need-modify-based-babel": {
"prompts": true
}
}
}
```
I need to invoke the `@dd/vue-cli-plugin-need-modify-based-babel` behind the `@vue/cli-plugin-babel`. But the sortObject function in v3.0.4 would change my intended order to the sort of Unicode code point value. And I think do not sort by unicode is more appropriate for preset.plugin.
=> fix(preset): plugin invoke order don't sort by unicode order

packages/@vue/cli-ui/src/components/PackageSearchItem.vue
It was correctly done in `ProjectPluginItem` but not in `PackageSearchItem`.
=> fix(ui): i18n for 'Official' in plugin search results

packages/@vue/cli-plugin-pwa/generator/template/public/manifest.json
When deploying applications using Github Pages, and other scenarios, absolute paths don't work because the website is served under a subdirectory. But using relative paths should work in all scenarios where `manifest.json`, `index.html` and the icons folder are on the same location. Which should be the case with the generated files if they are not modified.
In case this is not accepted, it should at least be documented because the current setup is generating PWAs that don't have proper icons in Github Pages. This same thing happens with vuepress, so once this is resolved I'll do the same on the other repo.
=> fix: Use relative paths in manifest.json for compatibility with Github Pages

packages/@vue/babel-preset-app/index.js
It allows debugging babel preset env. That's especially useful when using the `usage` option of `useBuiltIns`.
=> [babel-preset-app] Forward preset-env's debug option

packages/@vue/cli-plugin-unit-mocha/setup.js
- Set `pretendToBeVisual` to `true` in jsdom-global. This adds features like `requestAnimationFrame`, and keeps the jsdom environment in line with [Jest](https://github.com/facebook/jest/blob/6d3da9be06350bfa7414b609807ebd0cbdf0c416/packages/jest-environment-jsdom/src/index.js#L31)
=> feat: set pretendToBeVisual option for jsdom-global

packages/@vue/cli/bin/vue.js, packages/@vue/cli/lib/ui.js
```console
$ vue ui --host 0.0.0.0
🚀  Starting GUI...
🌠  Ready on http://localhost:8000
```
Currently `vue ui` can not connect from outside. This is because it is bound to localhost.
In this Pull Request, an option is added so that it can be changed to host other than localhost.
=> feat(ui): add --host option

packages/@vue/cli-service/lib/commands/serve.js
While working on a Vue CLI 3 server / container template for CodeSandbox and having an HMR issue (an invalid webpack socket URL), looking at how HMR is configured in `serve.js`, I've noticed that `serve` should be detecting that it's running in a container, but it's not. Looking further at the [container detection code](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/commands/serve.js#L296), and then at `/proc/1/cgroup` inside the container, it looks like
```
12:memory:/kubepods/burstable/pod[redacted]
11:blkio:/kubepods/burstable/pod[redacted]
[...more similar lines...]
```
, so I added `kubepods` to the detection regex.
You can see it working at https://codesandbox.io/s/qv463kv6z6 (where I manually changed `serve.js` inside `node_modules/@vue/cli-service`).
The …
=> fix(serve): also detect kubernetes containers

packages/@vue/cli/lib/util/__tests__/extendJSConfig.spec.js, packages/@vue/cli/lib/util/extendJSConfig.js
There is a case that Vue CLI fails to add a plugin with the following assertion error (it's a case adding `vue-cli-plugin-quasar`):
```
🚀  Invoking generator for vue-cli-plugin-quasar...
ERROR  Error: Must either call this.traverse or return false in visitAssignmentExpression
Error: Must either call this.traverse or return false in visitAssignmentExpression
at Context.invokeVisitorMethod (/xxx/node_modules/@vue/cli/node_modules/ast-types/lib/path-visitor.js:365:21)
at Visitor.PVp.visitWithoutReset (/xxx/node_modules/@vue/cli/node_modules/ast-types/lib/path-visitor.js:196:32)
at visitChildren (/xxx/node_modules/@vue/cli/node_modules/ast-types/lib/path-visitor.js:246:25)
at Visitor.PVp.visitWithoutReset (/xxx/node_modules/@vue/cli/node_modules/ast-types/lib/path-visitor.js:204:20)
at …
```
=> fix(cli): avoid assertion error when vue.config.js includes assignment expression

docs/ru/guide/plugins-and-presets.md, docs/zh/guide/plugins-and-presets.md
ref: https://github.com/vuejs/vue-cli/pull/2777
=> docs: (ru / zh) update plugins-and-presets.md

packages/@vue/cli-service/generator/index.js, packages/@vue/cli-service/generator/router/index.js, packages/@vue/cli-service/generator/router/template/src/router.js, packages/@vue/cli-service/generator/template/src/main.js
Currently, both `main.js` and `router.js` templates contain arrow functions.
When a user chooses not to select babel or typescript during project creation, the generated code will fail in browsers that don't support arrow functions.
Since we aim to be compatible with IE 11 out of the box, I added conditionals to the templates for these files to use a normal function instead when neither babel nor typescript plugins are detected.
=> Fix Template files for main.js and router when not using a compiler

docs/dev-guide/ui-localization.md
Transifex is a platform for collaborative translation and I have been using it to maintain the German locale. I have also imported all other locales and invited both the maintainers and the contributors to use it as well for their locale packages.
Note: As a non-commercial opensource project, we can use Transifex for free. Discourse and Nextcloud, for instance, also use it.
=> Docs: Add information about Transifex for easier collaborative translation

packages/@vue/cli-service/lib/commands/build/resolveWcConfig.js
This was already fixed for `--target lib` here some time ago:
https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/commands/build/resolveLibConfig.js#L48-L55
I just replicated the change for the web components config.
=> fix(wc): don't overwrite user-defined externals

packages/@vue/cli-service/__tests__/modernMode.spec.js, packages/@vue/cli-service/lib/commands/build/index.js, packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js, packages/@vue/cli-service/lib/webpack/ModernModePlugin.js
=> feat: add `--no-unsafe-inline` flag for modern mode

packages/@vue/cli-plugin-eslint/index.js, packages/@vue/cli-plugin-eslint/lint.js
Currently `@vue/cli-plugin-eslint` and it's `lint` command relies strictly on the ESLint package that has been set in its `package.json`.
There is however one problem with this - if a user updates the ESLint by him/herself - it won't be reflected by using `vue-cli-service lint` as it will resolve the `ESlint` specified in this plugin's package.json.
It might also lead to the following problem: https://github.com/vuejs/eslint-plugin-vue/issues/568
After updating both ESLint and `eslint-plugin-vue` the ESLint no longer resolves the right `eslint-plugin-vue`. 
In order to fix this problem I'm resolving the `ESLint` package using `loadModule` from shared utils.
Although this solves the problem, I still have few things on my mind:
- Perhaps we should add `eslint` and `eslint-plugin-vue` to …
=> fix(cli-plugin-eslint): Resolve proper ESLint package

packages/@vue/cli-plugin-eslint/__tests__/eslintGenerator.spec.js, packages/@vue/cli-plugin-eslint/generator/index.js, packages/@vue/cli-plugin-eslint/generator/template/airbnb/_editorconfig, packages/@vue/cli-plugin-eslint/generator/template/standard/_editorconfig, packages/@vue/cli-test-utils/createTestProject.js, scripts/buildEditorConfig.js, scripts/release.js
=>  feat: generate .editorconfig file for each specific eslint config

docs/config/README.md
Updates readme to reflect changes done on #2544 (commit 4cabf5e8c798287825908fb193d61fcc1e8d62af ) for v3.1.0.
Not sure if properly worded but with those changes, it fares an explanation that any other properties will also get passed along to `html-webpack-plugin`, not only listed properties.
An example would, for example, to pass data to template, like I illustrated on above issue, using `require('html-webpack-template')` as a template.
=> update config pages README.md

packages/@vue/cli-plugin-pwa/README.md
=> Fixed minor typo

packages/@vue/eslint-config-prettier/index.js, packages/@vue/eslint-config-prettier/package.json, yarn.lock
This PR updates the prettier and related packages, as well as extends eslint configuration, so it doesn't conflict with `eslint-plugin-vue` visual rules.
=> chore(eslint-config-prettier): Upgrade prettier and extend configuration

packages/@vue/cli-plugin-e2e-cypress/__tests__/cypressPlugin.spec.js, packages/@vue/cli-plugin-e2e-cypress/generator/index.js, packages/@vue/cli-plugin-e2e-cypress/generator/template/tests/e2e/plugins/index.js, packages/@vue/cli-plugin-e2e-cypress/package.json
Removes the `@cypress/webpack-preprocessor` from the generated cypress configuration, as it leads to several issues regarding file watching, headless mode and TS support.
~~Note that the dependency is still there, so any user needing it back just have to uncomment the lines in the generated config.~~ 
Update: after discussing with @sodatea the dependency is not needed and has been removed. Users can install it manually if they need it.
Note that I also added a simple test with cypress with TS
Fixes #2903
=>  fix: remove webpack-preprocessor from cypress config

packages/@vue/cli-service/lib/commands/serve.js, packages/@vue/cli-service/lib/util/isAbsoluteUrl.js
=> fix(cli-service): do not log absolute baseUrl in terminal, close #2877

packages/@vue/cli-plugin-typescript/lib/tslint.js
Updates `tslint.js` to respect `linterOptions.exclude` from `tslint.json`.
Previously, this configuration option was ignored in favour of the
following list of globs:
```
['src/**/*.ts', 'src/**/*.vue', 'src/**/*.tsx', 'tests/**/*.ts', 'tests/**/*.tsx']
```
See:
https://palantir.github.io/tslint/usage/configuration/
=> fix(typescript): respect excluded globs in tslint

packages/@vue/cli/bin/vue.js, packages/@vue/cli/package.json
As with many other projects, an astounding number of issues and conversations center around what versions of tools, CLIs and OSs users are running. I'd like to help this issue. We already ask for this info, why not automate it?
Other command line tools such as 
- React Native
- Create React App
- Expo
- Webpack
- Solidarity
- Gatsby
have all benefitted from adding envinfo to their CLI and issue template.
Here's an example output, custom tailored for Vue:
```
Environment Info:
System:
OS: macOS 10.14
CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
Binaries:
Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
Yarn: 1.9.4 - ~/.yarn/bin/yarn
npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
Browsers:
Chrome: 70.0.3538.77
Safari: 12.0
npmPackages:
@vue/babel-preset-app:  3.1.1 …
```
=> feat: add envinfo package via `vue info` in cli

packages/@vue/cli/lib/create.js
Show console warning messages for "Invalid project name" error in create function.
Warnings include errors such as "name can no longer contain capital letters" or "name can no longer contain more than 214 characters".
=> fix: display project name validation warnings

packages/@vue/cli-service/lib/config/base.js
Hello,
It is pretty common to see `.wasm` and `.mjs` files nowadays, some library start using them and this break by default in `vue-cli` without extending like this.
This pull request add support for those kind of files out-of-the-box.
**vue.config.js**
```JS
chainWebpack: config => config.resolve.extensions.prepend('.mjs').prepend('.wasm')
}
```
**Do not hesitate to ping me if you have any questions / need something.**
Regards
=> Add support for loading WebAssembly and ES Modules

docs/config/README.md
So that it'll be obvious that proxies are configured via regexes. Usually it's not noticeable, but the original example becomes problematic when vue-router in history mode is used.
Here is a place where matching happens - https://github.com/binarin/vue-cli/blob/5786e273b2e133c836f53f4ab5c1d8d65f9766f5/packages/%40vue/cli-service/lib/util/prepareProxy.js#L69
=> Update devServer.proxy documentation

lerna.json, packages/@vue/cli/lib/Creator.js, packages/@vue/cli/lib/options.js, packages/@vue/cli/lib/util/clearConsole.js, packages/@vue/cli/lib/util/getVersions.js, packages/@vue/cli/package.json, scripts/release.js, yarn.lock
- Keep package minors in sync (`lerna publish --force-publish` when releasing a new minor)
- Patch on demand (`lerna publish` fixed mode)
- `eslint-config-*` packages are published manually
1. We used to force publish every package till v3.1, this is due to the unbalanced update frequency among different plugins. In practice, some of them, like the pwa plugin, are quite stable and rarely need updating. So force publishing is overkill now.
2. We have switched to independent mode then, for two major benefits: 1) patching on demand and only on demand 2) eslint config packages needs a more aggressive update strategy in practice, due to the frequent breaking changes in the upstream packages. However, this also causes maintenance burden and confusion to end users. So it's far from ideal.
3. So …
=> New release strategy

packages/@vue/cli-plugin-pwa/README.md
=> docs(pwa): explanation why SW is enabled only in production mode

docs/.vuepress/config.js
Hey there! I enabled VuePress' feature to show the search via DocSearch so there's the extra features, like searching in the content, and typo tolerance. 
Thanks!
=> docs: enable Algolia search

docs/guide/browser-compatibility.md
=> Add tip about detecting modern mode

packages/@vue/cli-plugin-typescript/index.js
When you run `vue-cli-service help`, there is no description for the `lint` command. I discovered that this was because the command registration code had a typo.
=> TypeScript plugin: Fix typo in lint command registration

docs/guide/deployment.md
Included instructions for users that use `History Pushstate mode` on Vue Router and run application on Netlify.
=> Instructions about History Pushstate in Netlify

packages/@vue/cli-plugin-unit-mocha/setup.js
Set `url: 'http://localhost'` option to jsdom-global. This fix `SecurityError: localStorage is not available for opaque origins` in mocha tests caused of jsdom (jsdom/jsdom#2304).
=> fix(unit-mocha): set `url` option for jsdom-global

packages/@vue/cli-plugin-unit-jest/generator/index.js
tsconfig.json is set to preserve jsx:
```json
"jsx": "preserve"
``` 
Because Typescript can't compile JSX into Vue-style render functions, only React-style.
But that means:
* When using Typescript and Babel, Typescript will emit Javascript that still contains JSX. That's fine with`build` and `serve` if we also use babel to conmplie the JSX afterwards. But in Jest, we can only pick one transform, we can't chain them.
* When Only using Typescript, we can't use JSX at all.
This PR is meant to fix the first issue: ts-jest should use babel to transform result for correct JSX transforms by setting its `babelConfig` option.
close #3100
Sidenote: The second issue still exists, and likely isn't resolable. We should probably document it, though, and also mention in the prompt messages.
=> fix(cli-plugin-unit-jest): When using TS & Babel, make ts-jest use babelConfig 

packages/@vue/cli-service/lib/config/dev.js
As per comment https://github.com/vuejs/vue-cli/issues/1451#issuecomment-448952314, https://github.com/vuejs/vue-cli/issues/1451#issuecomment-450410469.
`NoEmitOnErrorsPlugin` is not necessarily needed anymore and causing problems, kindly remove it.
=> fix(cli-service): drop webpack NoEmitOnErrorsPlugin usage

packages/@vue/cli-ui-addon-webpack/package.json, packages/@vue/cli-ui-addon-widgets/package.json
The direct dependencies from cli "cli-ui-addon-webpack" and "cli-ui-addon-widgets" were missing the license information. Simply adding a line in package.json for npm to be able to pick up the license information.
=> Add license to addons

packages/@vue/cli-service/__tests__/build.spec.js, packages/@vue/cli-service/lib/config/app.js
don't skip files named `index.html` `/public` when nested in a subfolder. We only need to ignore the index.html directly under `/public/index.html`, which is used by html-webpack-plugin as a template.
close #3119
=> fix(cli-service): Fix copy plugin's ignore pattern (fix #3119)

packages/@vue/babel-preset-app/README.md, packages/@vue/babel-preset-app/index.js
This ensures support for Object rest spread usage in templates with [vue-template-es2015-compiler@1.8.0](https://github.com/vuejs/vue-template-es2015-compiler/releases/tag/v1.8.0).
=> feat(babel): include es6.object.assign by default

packages/@vue/cli-plugin-e2e-cypress/README.md
It took me 5 minutes to find the right path for the spec command. Cypress docs are referenced, but the path is different + the indication `Note: quotes required` can be misleading.
=> docs: Add an example with the spec option

docs/zh/config/README.md, packages/@vue/cli-service/lib/Service.js
eg: 
command `vue-cli-service serve -h` has the same effect as `vue-cli-service serve --help`
=> feat: support use -h show detailed usage of command

packages/@vue/cli-plugin-typescript/lib/tslint.js
Fixes issue in #1900
Only yml, yaml und json is supported by tslint (https://github.com/HyphnKnight/tslint/commit/adb5ac92d385c646c10a8ad8de7ab8989725dbf5). 
Feature Request by @algil  for tslint.js is ignored.
=> Support yml, yaml und json tslint Configuration files

packages/@vue/cli-ui/apollo-server/connectors/folders.js
Issue: https://github.com/vuejs/vue-cli/issues/3253
It's a node issue on Windows when using drive path without backslash.
=> fix(cli-ui): folder list when root windows

packages/@vue/cli/lib/util/installDeps.js
refactor
```javascript
if (command === 'npm') {
...
} else if (command === 'yarn') {
...
} else {
throw new Error('...')
}
```
to
```javascript
checkPackageManagerIsSupported(command)
if (command === 'npm') {
...
} else if (command === 'yarn') {
...
}
```
=> refactor: check support package manager befor install

packages/@vue/cli-service/__tests__/css.spec.js, packages/@vue/cli-service/__tests__/generator.spec.js, packages/@vue/cli-service/__tests__/serve.spec.js, packages/@vue/cli-service/generator/index.js, packages/@vue/cli-service/generator/template/src/App.vue, packages/@vue/cli-service/generator/template/src/components/HelloWorld.vue, packages/@vue/cli-service/lib/config/css.js, packages/@vue/cli-service/package.json, packages/@vue/cli/lib/options.js, packages/@vue/cli/lib/promptModules/__tests__/cssPreprocessors.spec.js, packages/@vue/cli/lib/promptModules/cssPreprocessors.js, packages/@vue/cli/lib/util/inferRootOptions.js, packages/@vue/cli/lib/util/injectImportsAndOptions.js, yarn.lock
closes https://github.com/vuejs/vue-cli/issues/1782
1. `sass` + `fibers` combined is ~10MiB smaller than the `node-sass` package, and approximately 1.5x slower in performance ([perf report](https://github.com/sass/dart-sass/blob/master/perf.md), and with `fibers` there's a 2x speedup)
2. [It's the future of sass](http://sass.logdown.com/posts/1022316-announcing-dart-sass)
TODOs in this PR:
1. [x] Should add tests
2. [ ] This PR uses a `try ... catch` block to test if `sass` package can be resolved and default to it. Should we make it more explicit? How?
=> feat: support dart-sass as default sass implementation

packages/@vue/cli-plugin-eslint/__tests__/eslintGenerator.spec.js, packages/@vue/cli-plugin-eslint/generator/index.js, packages/@vue/cli-plugin-typescript/generator/index.js, packages/@vue/cli-plugin-typescript/package.json, packages/@vue/cli/__tests__/invoke.spec.js, packages/@vue/eslint-config-typescript/README.md, packages/@vue/eslint-config-typescript/index.js, packages/@vue/eslint-config-typescript/package.json
Packages
- typescript-eslint-parser: https://github.com/eslint/typescript-eslint-parser
- eslint-plugin-typescript: https://github.com/bradzacher/eslint-plugin-typescript
got deprecated in favor of [@typescript-eslint](https://typescript-eslint.io)
=> Update eslint-config-typescript to use @typescript-eslint

packages/@vue/cli-plugin-typescript/lib/tslint.js
Support for TSX writing in.vue files and validation by tslint.
=> fix: .vue file script lang is tsx but createSourceFile as JS. so  join ScriptKind.

packages/@vue/babel-preset-app/package.json, packages/@vue/cli-init/package.json, packages/@vue/cli-overlay/package.json, packages/@vue/cli-plugin-babel/package.json, packages/@vue/cli-plugin-e2e-cypress/package.json, packages/@vue/cli-plugin-e2e-nightwatch/package.json, packages/@vue/cli-plugin-eslint/package.json, packages/@vue/cli-plugin-pwa/package.json, packages/@vue/cli-plugin-typescript/package.json, packages/@vue/cli-plugin-unit-jest/package.json, packages/@vue/cli-plugin-unit-mocha/package.json, packages/@vue/cli-service-global/package.json, packages/@vue/cli-service/package.json, packages/@vue/cli-shared-utils/package.json, packages/@vue/cli-test-utils/package.json, packages/@vue/cli-ui-addon-webpack/package.json, packages/@vue/cli-ui-addon-widgets/package.json, packages/@vue/cli-ui/package.json, packages/@vue/cli-upgrade/package.json, packages/@vue/cli/package.json, packages/@vue/eslint-config-airbnb/package.json, packages/@vue/eslint-config-prettier/package.json, packages/@vue/eslint-config-standard/package.json, packages/@vue/eslint-config-typescript/package.json
This field allows you specify path of each package in a monorepo thanks to [this npm RFC](https://github.com/npm/rfcs/blob/latest/accepted/0010-monorepo-subdirectory-declaration.md). Main benefit of providing this field is a more accurate link to the package's source code from its npmjs.com page.
I had to add `repository` section in three packages: `cli-ui`, `cli-ui-addon-widgets`, `cli`cli-ui-addon-webpack` as it was missing from their `package.json`.
=> chore: add `repository.directory` field to each `package.json`

packages/@vue/cli-ui/src/i18n.js
Hi! :wave: 
While I was investigating #3410, I noticed that we were using `VueTimeago.createTimeAgo`, but `createTimeAgo` is a named export.
=> fix: Import createTimeAgo from vue-timeago

docs/guide/mode-and-env.md
Following the issue https://github.com/vuejs/vue-cli/issues/2625 I incorporated information that helped me understand better how modes and environment variables work in Vue CLI. Also the modes are moved to the beginning for emphasis.
=> Extend mode and env vars guide

packages/@vue/cli-plugin-typescript/__tests__/tsPluginTSLint.spec.js, packages/@vue/cli-plugin-typescript/lib/tslint.js
=> Don't reread the input file on ts linting

packages/@vue/cli-service/lib/commands/serve.js
With `multi-page` configuration like: 
```js
pages: {
main: {
entry: 'src/main.js',
template: 'public/index.html',
filename: 'index.html'
},
preview: {
entry: 'src/preview.js',
template: 'public/index.html',
filename: 'preview.html'
}
}
}
```
HTML for page `preview` can only be accessed by `localhost:8080/preview.html`.
This plays well with vue-router + `hash` mode. But with `history` mode, `preview.html` would not be accessible. 
eg. accessing `localhost:8080/preview.html/about` will result in `index.html` because `/preview.html/about` is a not found request and being fallback.
This PR adds support for multi-page fallback, it fallback `${baseUrl}/${name of page}` to the correct html file (filename specified or `${name}.html`). 
In above case, the two pages could be …
=> feat(cli-service): add history api fallback for multi-page mode

packages/@vue/cli-service/lib/commands/build/index.js
fix #3438, #3474
Fixes modern mode issues by really running the two builds in separate processes (thus avoiding any babel preset caching issues)
=> fix: run modern build in separate process

docs/guide/deployment.md
This guide shows how to build a docker image to run a vue-cli based application with nginx. It has an example nginx config that does the appropriate pushState() based routing fallbacks for 404's.
=> Add docker based nginx deployment guide to docs

docs/guide/cli-service.md, packages/@vue/cli-service/lib/commands/serve.js
As explained in issue #3476 , `clipboardy` throws an exception on some platforms, notably Windows Subsystem for Linux. This results in an `unhandledPromiseRejection` when using the `--copy` option.
As of right now this is just very annoying, but those rejections are deprecated and will completely stop the process in the future and so forth – you know the drill.
To prevent this I changed the copying to use `writeSync()` and wrapped it in a `try catch`-block. This also means we only log `(copied to clipboard)` now if copying was actually successful.
I also added a tip to the docs, it looks like this:
___
___
If you think this is unnecessary and we can just fail silently without mentioning it somewhere, we can also revert this commit of course :)
=> fix(cli-service): catch exception if "copy to clipboard" fails (issue #3476)

packages/@vue/cli-ui/src/components/dependency/NpmPackageSearch.vue
This will allow us to have a focused analytics on only queries done by Vue. If you don't have access to the dashboard yet, you can let me know (make an Algolia account first, and tell the email).
Did you know the most-searched term without results is "firebase"?
=> add analytics tags to dependency search

packages/@vue/cli-plugin-babel/index.js
I'm not 100% sure but the option transpileDependencies in vue.config.js did not work for dependencies that use .mjs files. This small regex change fixes that problem.
=> Add .mjs files as transpileable files

packages/@vue/babel-preset-app/README.md, packages/@vue/babel-preset-app/index.js, packages/@vue/babel-preset-app/polyfillsPlugin.js
To inject polyfills to all entry file.
Multi page repo now will be only inject polyfills to the first entry file.And the queue of entry file list may be different.So the hash may change in different machine.
We should inject polyfills to all entry file.
=> fix(babel-preset-app): multiPage repo add option entryFileList

packages/@vue/cli-plugin-typescript/generator/index.js, packages/@vue/cli-plugin-typescript/package.json
https://github.com/typescript-eslint/typescript-eslint/pull/184
@typescript-eslint/eslint-plugin has now loosen their requirement for peer dep.
And users are now able to disable the warning by specifying `warnOnUnsupportedTypeScriptVersion` in `parserOptions`.
So to ease maintenance burden, we should also loosen this restriction.
=> feat: loosen the restriction of typescript version

packages/@vue/cli-service/lib/commands/inspect.js
should only return rules that actually have a name 
(= which were added with the chainWebpack API)
close #3334
Alternative: Instead of filtering these cases, we could add a default name to inform the user that there are rules not included in this list?
=> fix(cli-service): inspect --rules (close #3334)

packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js, packages/@vue/babel-preset-app/index.js, packages/@vue/babel-preset-app/polyfillsPlugin.js, packages/@vue/cli-service/lib/Service.js
The old logic is not reliable due to the presence of thread-loader
closes #2983
=> fix: use an environment variable to determine the entry files to inject default polyfills

docs/guide/css.md
path should start with `~` because of css-loader url()
or it will be regarded as relative path.
=> docs(css): sass import path

packages/@vue/cli-plugin-e2e-nightwatch/index.js
Before it was only checking for `--env`. So if `-e something` was used, the generated command line included `-e` and `--env`:
... -e something ... --env chrome
Now it does not append `--env chrome` if `-e` is used.
=> fix setting env by `-e` in e2e tests

docs/config/README.md, packages/@vue/cli-plugin-unit-jest/README.md, packages/@vue/cli-plugin-unit-jest/generator/index.js
I found that many people have issues running tests with jest, receiving an error like `"unexpected token "import"`.
The most common reason - as far as I can tell - are packages in their node_modules that contain untranspiled ES6 imports.
While we offer the `transpileDependencies` option, jest doesn't respect it, and rightfully so, since the issues solved by that option are often different ones (transpiling for browser compatibility).
Instead, people have to adjust jest's `transformIgnorePatters` option when one of the packages they use has to be transformed by `babel-jest` or `vue-jest`.
=> docs: Document jest's `transformIgnorePatterns` option to avoid pitfall

README.md
vue-cli is using [lerna](https://lernajs.io/) that's why I think we should add lerna badge.
=> add lerna badge in README [ci skip]

docs/dev-guide/plugin-dev.md
=> docs: adjust plugin dev guide example to write modified contents, fixes #3655

docs/guide/html-and-static-assets.md
I have edited the code examples to reference the plugin by the name 'prefetch-app', as this seems to be the correct name the webpack config requires from inspecting the generated config. I have tested and can confirm this works with the example that deletes the plugin altogether, but not the blacklisting example.
=> Add notes for multi-page apps on references to 'prefetch' plugin

packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js, packages/@vue/babel-preset-app/package.json, packages/@vue/babel-preset-app/polyfillsPlugin.js
=> fix: use absolute import path for injected core-js polyfills

packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js, packages/@vue/cli-service/lib/webpack/ModernModePlugin.js
=> fix: set the path of safari-no-module-fix.js correctly

packages/@vue/cli-service/lib/PluginAPI.js
https://github.com/vuejs/vue-cli/commit/a2bc927ac837ac6b343f597be4271f0ce9d688f1#diff-04612bf191a2c1a06ac248910d9e9415R162 attempted to fix a problem with cache invalidation when javascript config files (like babel.config.js) change their content i.e. depending on an env variable.
The fix was:
```javascript
if (absolutePath.endsWith('.js')) {
// should evaluate config scripts to reflect environment variable changes
try {
return JSON.stringify(require(absolutePath))
} catch (e) {
return fs.readFileSync(absolutePath, 'utf-8')
}
}
```
However we missed to add an `else` branch to keep including non-js config files (like `.browserslistrc`) in the generation of the cache key.
This PR adds that `else {` branch
close #3631
=> fix: properly load non-js config files in genCacheConfig

packages/@vue/babel-preset-app/index.js, packages/@vue/babel-preset-app/package.json, yarn.lock
seems there're still problems with it, e.g. when core-js 3 is hoisted as the root level dependency.
=> fix: downgrade @babel/preset-env temporarily

packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js, packages/@vue/babel-preset-app/index.js, packages/@vue/babel-preset-app/package.json, packages/@vue/cli-plugin-babel/index.js
It is due to a misunderstanding when upgrading babel from 7.0.0-beta.47
to 7.x.
In Vue CLI, usage-based polyfills are **only** added by @babel/preset-env
so that it avoids overheads. `transform-runtime` plugin adds polyfills
regardless of env targets so we must disable its polyfill feature.
Though, there're edge cases where runtime-helpers' polyfill dependency
are not correctly added (https://github.com/babel/babel/issues/7597),
so we also need to whitelist `@babel/runtime` for webpack to transpile.
=> fix: should not add polyfills from transform-runtime plugin

packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js, packages/@vue/babel-preset-app/index.js, packages/@vue/babel-preset-app/polyfillsPlugin.js
=> fix: should not use absolute polyfill paths when `absoluteRuntime` is on

packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js, packages/@vue/babel-preset-app/index.js, packages/@vue/babel-preset-app/package.json, packages/@vue/cli-plugin-babel/index.js
This reverts commit b98796938ed05ccbaa41e62db8e2f9744d3cb5ac.
Closes #3741
We need a better strategy to fix the `'Symbol' is undefined ` issue. Until then, we'll settle on the current not-ideal-but-works configuration.
=> revert: "fix: should not add polyfills from transform-runtime plugin (#3730)"

docs/guide/css.md, packages/@vue/cli-service/__tests__/generator.spec.js, packages/@vue/cli-service/generator/index.js
fixes #3429
fixes #3570
fixes #3624
=> feat: make `fibers` opt-in for dart sass

packages/@vue/cli-plugin-e2e-nightwatch/package.json
The yarn.lock file changes fairly drastically when I run yarn so not committing it in this PR. I was able to run the test and it ran successfully. I also ran this in the context of a new project and everything seems to work well with boilerplate generators.
```bash
$ yarn -v
1.13.0
```
=> chore(plugin/nightwatch): bump nightwatch dependency

packages/@vue/cli-plugin-eslint/generator/index.js, packages/@vue/cli-plugin-eslint/package.json, packages/@vue/cli-service-global/package.json
BREAKING CHANGE: may cause old projects' linting fail
(those scaffolded with Vue CLI 3.0.x).
=> feat: use ESLint v5 by default everywhere

packages/@vue/cli-plugin-e2e-nightwatch/index.js
"vue-cli-service e2e" has been deprecated in v3 and
renamed to "vue-cli-service test:e2e". Now the legacy command is
completely removed.
=> chore: remove support for legacy `vue-cli-service e2e` command

packages/@vue/cli-service/generator/template/_gitignore
Currently this ignores more than the possible 3 character vim swap file extensions. This change will only ignore 3 letter vim swap files starting with `.sw` (most common)
=> chore: more accurate vim swap file ignore

packages/@vue/babel-preset-app/README.md
missing document when i want to disabled @vue/babel-preset-jsx injectH feature
**Reasons to try to contribute**
because the document does not have any description of the  `@vue/babel-preset-jsx` feature configuration
`@vue/babel-preset-app`文档只提到可以通过设置 `jsx:false` 来关闭 jsx 语法，但实际上源码里面还会通过 `jsx`字段来配置 `@vue/babel-preset-jsx` 的功能，却没有任何说明……
=> docs: add tip about jsx options

packages/@vue/cli-service/lib/util/getAssetPath.js
placeAtRootIfRelative is not using so remove it
=> refactor: remove unused `placeAtRootIfRelative` parameter

packages/@vue/cli-service/__tests__/buildLib.spec.js, packages/@vue/cli-service/lib/commands/build/demo-lib-js.html, packages/@vue/cli-service/lib/commands/build/demo-lib.html, packages/@vue/cli-service/lib/commands/build/index.js, packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js
When build target is 'lib', developer can specify an output filename that is different from the library's name.
=> feat(cli-service): add --filename option to specify the output file name

packages/@vue/cli-ui/locales/en.json, packages/@vue/cli-ui/src/components/content/TerminalView.vue
Add button to copy all the terminal content or only selection to the clipboard
Is quite annoying select all the text when doing an `webpack inspect`, because `CTRL+ COMMAND` is not supported in terminal
=> feat(ui): add copyContent to clipboard button on terminal component

packages/@vue/cli-service/lib/commands/serve.js, packages/@vue/cli-shared-utils/lib/env.js, packages/@vue/cli-ui/apollo-server/util/command.js, packages/@vue/cli-ui/src/components/file-diff/FileDiffView.vue, packages/@vue/cli/lib/Creator.js, packages/@vue/cli/lib/add.js, packages/@vue/cli/lib/invoke.js, packages/@vue/cli/lib/util/installDeps.js, packages/@vue/cli/lib/util/loadCommand.js
=> fix pnpm compatibility issues during scaffolding

packages/@vue/cli-ui/apollo-server/util/rcFolder.js
=> fix: fix ERR_INVALID_ARG_TYPE error when launching `vue ui`

packages/@vue/cli-ui-addon-webpack/src/components/BuildProgress.vue
On dark mode the remaining progress bar color was the same color as the background.
=> Fixed progress-path background color for dark mode

packages/@vue/cli-ui/locales/en.json
Just saw this typo while trying to kill a process using a port
=> Fix typo "procress" -> "process"

packages/@vue/cli-service/generator/index.js, packages/@vue/cli-ui-addon-widgets/.browserslistrc
The `not ie <= 8` rule in the browserlist is redundant. `ie <= 8` browsers aren't added by `> 1%` nor `last 2 versions`
=> Remove redundant <= IE8 rule

packages/@vue/cli-service/lib/commands/build/resolveWcConfig.js, packages/@vue/cli-service/lib/config/app.js, packages/@vue/cli-service/lib/config/base.js, packages/@vue/cli-service/lib/util/resolveClientEnv.js
This change breaks use cases where users have tapped the `define`
plugin options in `chainWebpack`
fixes #3579
=> refactor: use EnvironmentPlugin instead of DefinePlugin

packages/@vue/cli-service/lib/config/base.js
Detailed explanation: https://github.com/vuejs/vue/issues/9208#issuecomment-450012518
Take the following template as example:
```
<p>
Welcome to <b>Vue.js</b> <i>world</i>.
Have fun!
</p>
```
With `preserveWhitespace: false`, it was compiled as:
```
<p> Welcome to <b>Vue.js</b><i>world</i>. Have fun! </p>
```
With `whitespace: 'condense'`, it is now compiled as:
```
<p> Welcome to <b>Vue.js</b> <i>world</i>. Have fun! </p>
```
Note the **inline whitespace between tags** is preserved.
Closes #1020
=> feat!: set `whitespace: 'condense'` for template compiler

package.json, packages/@vue/cli-plugin-typescript/package.json, packages/@vue/cli-plugin-unit-jest/generator/index.js, packages/@vue/cli-plugin-unit-jest/package.json
See:
https://jestjs.io/blog/2019/01/25/jest-24-refreshing-polished-typescript-friendly
https://github.com/facebook/jest/blob/20ba4be9499d50ed0c9231b86d4a64ec8a6bd303/CHANGELOG.md#2400
closes #3450
closes #3605
closes #3497
=> feat!: upgrade jest to v24

docs/dev-guide/plugin-dev.md
Close #3873 
Moved a plugin naming convention to the beginning of the Plugin dev guide.
=> docs: move plugin naming

packages/@vue/cli-ui/package.json
This commit fixes a peer dependency warning described here:
https://github.com/vuejs/vue-cli/issues/2862#issuecomment-485777470
=> fix: vue-virtual-scroller should be in devDependencies as it's client-side only

packages/@vue/cli-plugin-unit-jest/package.json
=> fix: pin jest-watch-typeahead to 0.2.1, avoid introducing jest 24 deps

packages/@vue/cli-service/lib/PluginAPI.js
=> fix: should invalidate cache when lockfiles have updated

packages/@vue/cli-service/lib/config/base.js
To be in line with webpack's default configuration and avoid confusions:
https://webpack.js.org/configuration/node/
DefinePlugin uses simple string replacements so it won't interfere with this polyfill.
=> fix: `process` should be polyfilled rather than mocked

packages/@vue/cli-plugin-babel/index.js, packages/@vue/cli-plugin-typescript/index.js, packages/@vue/cli-service/lib/options.js, packages/@vue/cli-service/types/ProjectOptions.d.ts
=> feat: allow `parallel` option to be an integer

docs/dev-guide/plugin-api.md, packages/@vue/cli-service/__tests__/Service.spec.js, packages/@vue/cli-service/lib/PluginAPI.js
partially addresses #2336 (GeneratorAPI TBD)
=> feat: add `.version` field and `assertVersion` helper to plugin api

packages/@vue/cli-service/lib/config/app.js
This changes the output directory structures for development mode
(app.js -> index.js + chunk-common.js + chunk-vendors.js).
By enabling splitChunks by default, the memory usage of webpack may be
greatly reduced for large multi-page projects.
This commit fixes #3838
May also fix #2991
=> feat!: enable splitChunks by default even in development mode

packages/@vue/cli-service/package.json
See https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/CHANGELOG.md#500-2019-02-20
=> chore!: upgrade to copy-webpack-plugin v5

packages/@vue/cli-service/__tests__/generator.spec.js, packages/@vue/cli-service/generator/index.js, packages/@vue/cli/lib/options.js, packages/@vue/cli/lib/util/inferRootOptions.js
Preset generated before v3.4.0 may contain a `"cssPreprocessor": "sass"`
field. It now means dart-sass rather than node-sass.
For generators, `rootOptions.cssPreprocessor === 'sass'` now also means dart sass.
=> chore!: default to dart sass for `sass` option of `cssPreprocessor`

packages/@vue/cli-plugin-typescript/index.js
When using Typescript, the webpack resolve options should prefer ts? file extensions over js? ones.
Strictly speaking, this is a breaking change, so we can ship this with v4 I think.
close #3898
=> chore: prefer .tsx? files over .jsx? file extensions

packages/@vue/cli-ui/src/i18n.js
This is because [vue-cli-locales/locales](https://unpkg.com/vue-cli-locales@3.7.0/locales/) use `_` to separate language and region name, while some browser use `-` to do so.
=> fix(cli-ui): fix detectLanguage function

packages/@vue/babel-preset-app/package.json
@vue/babel-preset-jsx 1.0.0 has been released. It doesn't have any breaking changes from the latest beta that we included so far.
=> feat(babel-preset-app): Bump jsx dependency version

packages/@vue/cli-service/package.json
See: https://github.com/neutrinojs/webpack-chain/blob/master/CHANGELOG.md#v600
New feature: extended DevServer method
Also dropped support for Node.js v6. It is not a breaking change for Vue
CLI, though, as Node.js v6 was never officially supported.
=> chore: upgrade webpack-chain to v6

packages/@vue/cli/bin/vue.js, packages/@vue/cli/package-lock.json, packages/@vue/cli/package.json
Suggest appropriate commands if the user mistypes utilising the [didyoumean](https://www.npmjs.com/package/didyoumean) package.
=> feat(cli): suggest matching commands if the user mistypes

packages/@vue/cli-plugin-eslint/__tests__/eslintPlugin.spec.js, packages/@vue/cli-service-global/index.js, packages/@vue/cli-service/__tests__/Service.spec.js, packages/@vue/cli-service/lib/options.js, packages/@vue/cli-ui-addon-widgets/src/components/News.vue, packages/@vue/cli/__tests__/Generator.spec.js, packages/@vue/cli/__tests__/invoke.spec.js
See https://github.com/vuejs/vue-cli/pull/3572
=> chore!: change default value of `lintOnSave` option

packages/@vue/cli/__tests__/Generator.spec.js, packages/@vue/cli/lib/util/injectImportsAndOptions.js, packages/@vue/cli/package.json
=> refactor: replace recast with jscodeshift for `injectImportsAndOptions`

packages/@vue/cli-service/lib/config/css.js
feat(compiler): enable hmr for 'mini-css-extract-plugin' in dev
since: https://github.com/webpack-contrib/mini-css-extract-plugin#hot-module-reloading-hmr
Solve #3751
=> Enable HMR when extracting CSS in dev

packages/@vue/cli-upgrade/package.json
=> fix: add missing dependencies to @vue/cli-upgrade

packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js, packages/@vue/cli-plugin-pwa/ui.js, packages/@vue/cli-ui/locales/en.json
=> feat(HtmlPwaPlugin): adds 'manifestCrossorigin' option

docs/dev-guide/plugin-dev.md
I've added it because it was not mentioned in the document about the details of prompts export.
See more details the commit:
https://github.com/vuejs/vue-cli/commit/e33b04c306bd539303812a1c6a2cffbae61acad4
=> docs: add more explanation at prompts

packages/@vue/cli-service/lib/commands/serve.js
=> fix(cli-service): avoid opening browser twice (#4063)

packages/@vue/cli-service/lib/Service.js
Thanks to @SneakyMax
See https://github.com/vuejs/vue-cli/issues/4014#issuecomment-497993827
=> fix: fix resolve project local plugin's file path

packages/@vue/cli-service/lib/util/prepareURLs.js, packages/@vue/cli-service/package.json
fixes #3266
see https://github.com/vuejs/vue-cli/issues/3266#issuecomment-493487325
Thanks to @shenliangv
=> fix: display correct address when multiple network adapters present

packages/@vue/cli/lib/util/configTransforms.js
The root cause here is the same as #4095
The failing `loadModule` call will return `undefined` for a js config
read operation, which later caused config being overwritten.
=> fix: fix config merging during `vue invoke` in Node.js v12

docs/guide/creating-a-project.md
In #1509 it is mentioned that a new project can be created in the current directory. This is a common scenario (e.g. creating a repo on GitHub, cloning it, and then running `vue create`). This commit makes this functionality more well known.
=> Add creating new project in existing directory

packages/@vue/cli-plugin-eslint/package.json, packages/@vue/cli-plugin-typescript/package.json, packages/@vue/cli-service/package.json
It is because yorkie is not used anywhere in @vue/cli-service, but only
included for the `lintOn: 'commit'` feature of eslint & typescript
plugin.
Also, a lot of global installation issues are caused by the yorkie
postinstall script. Moving it out of the dependency chain of `@vue/cli`
mitigates such issues.
=> chore: move yorkie from cli-service to plugin-eslint & plugin-typescript

docs/guide/browser-compatibility.md
We don't include some plugins during legacy build when building in modern mode. Trying to tap into their options causes `webpack-chain` to throw a pretty cryptic error.
This warning should help people deal with that situation.
----
close #3845
=> docs: mention caveat about missing plugins when in legacy config

docs/guide/deployment.md
I see there are many other guides for heroku proposed:
- https://github.com/vuejs/vue-cli/pull/3684
- https://github.com/vuejs/vue-cli/pull/3607
- https://github.com/vuejs/vue-cli/pull/3445
- https://github.com/vuejs/vue-cli/pull/3285
- https://github.com/vuejs/vue-cli/pull/2998
- https://github.com/vuejs/vue-cli/pull/3365
But all of them include some sort of node server which isn't really required with `heroku-buildpack-static` buildpack.
I'd argue that, this is the easiest and most straightforward way to deploy vue-cli app to heroku ;)
=> Add heroku deployment guide

packages/@vue/cli/lib/util/installDeps.js
This is an attempt to reduce redundant code.
=> Minor refactor to eliminate redundant code

docs/guide/deployment.md
This PR introduces a guide for deploying Vue.js apps on the Render platform. Disclosure: I work at Render.
It replaces https://github.com/vuejs/vue-cli/pull/3636 which was added by a Render user.
cc @NataliaTepluhina
=> docs: add Render deployment guide

packages/@vue/cli-plugin-typescript/generator/index.js
A `debugger` instruction was left after https://github.com/vuejs/vue-cli/pull/4090
=> fix: remove debugger

packages/@vue/cli-plugin-typescript/generator/convert.js, packages/@vue/cli-plugin-typescript/generator/index.js, packages/@vue/cli-plugin-typescript/generator/template/tsconfig.json, packages/@vue/cli-plugin-typescript/prompts.js
Close #2676 
At the moment when we run `vue add`, Vue CLI renames all `*.js` files to `*.ts`. This PR introduces two new prompts on `@vue/cli-plugin-typescript` late-invokation:
1) `convertJsToTs`: if set to `true`, renames all `.js` files to `.ts`. Otherwise renames only `main.js` -> `main.ts`;
2) `allowJs`: if set to `true`, adds `allowJs: true` to TSConfig compiler options.
=> feat(typescript): add an option to not rename all .js files to .ts and to set `allowJs` to true

packages/@vue/cli-plugin-eslint/index.js
=> fix: use module directory instead of main entry path for `eslintPath`

docs/guide/deployment.md
Travis CI supports force-pushing to the `gh-pages` branch using a personal access token and the `pages` deploy provider.
It's simpler than using `deploy.sh`
=> deployment.md: Add instructions for Travis CI

docs/guide/plugins-and-presets.md, docs/ru/guide/plugins-and-presets.md, docs/zh/guide/plugins-and-presets.md, packages/@vue/cli-plugin-vuex/.npmignore, packages/@vue/cli-plugin-vuex/README.md, packages/@vue/cli-plugin-vuex/__tests__/vuexGenerator.spec.js, packages/@vue/cli-plugin-vuex/generator/index.js, packages/@vue/cli-plugin-vuex/generator/template/src/store/index.js, packages/@vue/cli-plugin-vuex/index.js, packages/@vue/cli-plugin-vuex/package.json, packages/@vue/cli-service/__tests__/serve.spec.js, packages/@vue/cli-service/generator/index.js, packages/@vue/cli-service/lib/PluginAPI.js, packages/@vue/cli-ui/apollo-server/api/PluginApi.js, packages/@vue/cli-ui/tests/e2e/specs/g2-plugins.js, packages/@vue/cli-ui/ui-defaults/suggestions.js, packages/@vue/cli/lib/Creator.js, packages/@vue/cli/lib/Generator.js, packages/@vue/cli/lib/add.js, packages/@vue/cli/lib/options.js, packages/@vue/cli/lib/promptModules/__tests__/vuex.spec.js, packages/@vue/cli/lib/promptModules/vuex.js
=> feat!: make vuex a separate plugin

docs/config/README.md
Fixes #3308 , see that for details.
=> docs(proxy): add warning when proxy set as string (fix #3308)

packages/@vue/cli-service/package.json
Update `lodash.defaultsdeep` to version `^4.6.1`.
This is causing a high severity vulnerability in our repo.
Fixed in https://github.com/lodash/lodash/pull/4336.
=> fix(@vue/cli-service): Update lodash.defaultsdeep

packages/@vue/cli-service/lib/config/base.js
The use key is `pug-plain` despite a similar item above it using the key `pug-plain-loader`. This just makes them consistent.
This has a small chance of breaking projects that already override that particular loader config. So feel free to ignore this if it isn't worth it.
=> fix: make webpack `use` values consistent

packages/@vue/cli-service/lib/commands/build/index.js, packages/@vue/cli-service/lib/config/app.js
This patch fixes two related problems:
1. `indexPath` is not respected for non-production builds #2327
2. `build --dest` is applied after generating webpack config despite a number of elements in that config already setting values based on `outputDir`
I attempted to make it possible for `--dest` to override even user webpack config but it was far too complicated, not just in regard to `indexPath` but also other parts that rely on it. It might still be desirable if someone wants to have a go. This patch at least improves things in the mean time, as users are already instructed in the docs to set `outputDir` in config rather than overriding webpack settings themselves.
=> fix: indexPath should also affect non-production builds (#2327)

docs/guide/mode-and-env.md
It appears that .env files are only loaded at the start of `vue-cli-service` and are not watched for hot reloads. 
**I am actually not sure this is the case for everyone, but is so for me.**
I think it is worth noting because the expectation is that a file at the root of the project would be watched for hot reloads.
=> Explain when .env files are loaded.

packages/@vue/cli/lib/options.js, packages/@vue/cli/lib/util/getVersions.js
=> fix: fix latest version check when current version is a prerelease

packages/@vue/cli-test-utils/createTestProject.js
adjust args related to option 'initGit', use `--git`  `--no-git`
fix #4223
=> fix(cli-test-utils): fix can't create a project without a Git repository

docs/dev-guide/generator-api.md, docs/dev-guide/plugin-dev.md, packages/@vue/cli-plugin-eslint/generator/index.js, packages/@vue/cli/__tests__/Generator.spec.js, packages/@vue/cli/lib/Creator.js, packages/@vue/cli/lib/Generator.js, packages/@vue/cli/lib/GeneratorAPI.js, packages/@vue/cli/lib/add.js, packages/@vue/cli/lib/invoke.js
Fixes #1754, Fixes #1938
Implements the discussion regargding hooks from https://gist.github.com/sodatea/37bc8c36d7d0c285dfea52fbe8ddaf90
=> More flexible hook system

packages/@vue/cli-service/lib/config/app.js, packages/@vue/cli-service/lib/config/prod.js
Changing directory structure, though now becoming more intuitive, may
still break users' workflows, so it's considered a breaking change.
Fixes #4215.
Fixes #3767.
Fixes #3613.
=> chore!: ensure consistent directory structure for all modes

packages/@vue/cli-service/__tests__/buildLib.spec.js, packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js
See #4311 for more information
=> Fixed: "Default value of the --filename parameter results in broken build if scoped package name is used #4311"

packages/@vue/cli-plugin-eslint/generator/index.js
See changelog at https://github.com/vuejs/eslint-config-prettier/blob/master/CHANGELOG.md#500-2019-07-22
This only affects newly generated projects so it's not considered a
breaking change.
Fixes #4310
(In the long run, we should implement [install-peerdeps](https://github.com/nathanhleung/install-peerdeps/)-like API, to avoid maintaining peer dependencies in the generator)
=> feat(eslint-generator): upgrade @vue/eslint-config-prettier to v5.0.0

packages/@vue/cli/lib/GeneratorAPI.js
=> fix: require parent template after `when` condition evaluated as truthy

packages/@vue/cli-shared-utils/lib/env.js
- We never referred to `yarnpkg` anywhere else in the codebase
- For the rare case that `yarn` binary is overridden by Hadoop YARN,
`yarn --version` will throw (it only supports `yarn version`), therefore
it won't pass this check.
Fixes #3941.
Closes #3942.
=> fix: use `yarn --version` to detect yarn

packages/@vue/cli-service/__tests__/css.spec.js, packages/@vue/cli-service/lib/config/css.js
Fixes #4337
Backlog: maybe we should test for behaviors instead of configurations? But in that case, we'll have a very huge test suite…
=> fix: fix css modules configuration in css-loader v3

docs/guide/prototyping.md, packages/@vue/cli/bin/vue.js
Thanks to webpack, this one line addition in `packages/@vue/cli/bin/vue.js` is sufficient and works perfectly ! 🎉
=> Add --port argument to 'vue serve' command

README.md
[lernajs.io](https://lernajs.io/) has been moved to [lerna.js.org](https://lerna.js.org/), which makes the readme badge a dead link
Old badge: [![lerna](https://img.shields.io/badge/maintained%20with-lerna-cc00ff.svg)](https://lernajs.io/)
New badge: [![lerna](https://img.shields.io/badge/maintained%20with-lerna-cc00ff.svg)](https://lerna.js.org/)
=> Update lerna link in README.md

packages/@vue/cli-service/lib/commands/build/formatStats.js
修复：`vue.config.js`中如果设置`config.output.chunkFilename("jsi/[name].js?v=xxx")`，打包时不展示相应文件的问题
=> 修复chunkFilename带有查询字符串?xxx时build不展示文件的问题

docs/guide/css.md, packages/@vue/cli-service/lib/Service.js, packages/@vue/cli-service/lib/config/css.js, packages/@vue/cli-service/lib/options.js
=> fix: fix `css.loaderOptions.css.modules` default values

packages/@vue/cli-plugin-typescript/__tests__/tsGenerator.spec.js, packages/@vue/cli/lib/GeneratorAPI.js
The recent refactoring in #4330 introduced a regression where a `Home.vue` file was generated if using the TS plugin even without the router plugin. This happened because the result from the ejs rendering was `undefined`. This fixes the issue by returning an empty string instead, which will not be written.
=> fix: do not generate empty file

packages/@vue/cli-plugin-typescript/generator/template/tslint.json
The usual convention is to keep the TSLint rules ordered as you can see in the recommended set for example https://github.com/palantir/tslint/blob/master/src/configs/recommended.ts
=> chore: ordered tslint rules

.eslintrc.js, packages/@vue/cli-plugin-e2e-cypress/index.js, packages/@vue/cli-plugin-e2e-nightwatch/index.js, packages/@vue/cli-plugin-eslint/generator/index.js, packages/@vue/cli-plugin-pwa/ui.js, packages/@vue/cli-plugin-typescript/__tests__/tsPluginBabel.spec.js, packages/@vue/cli-plugin-typescript/index.js, packages/@vue/cli-plugin-typescript/lib/tslint.js, packages/@vue/cli-service-global/index.js, packages/@vue/cli-service-global/lib/globalConfigPlugin.js, packages/@vue/cli-service/lib/Service.js, packages/@vue/cli-service/lib/commands/build/formatStats.js, packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js, packages/@vue/cli-service/lib/commands/help.js, packages/@vue/cli-service/lib/commands/serve.js, packages/@vue/cli-service/lib/config/app.js, packages/@vue/cli-service/lib/webpack/analyzeBundle.js, packages/@vue/cli-shared-utils/lib/object.js, packages/@vue/cli-test-utils/serveWithPuppeteer.js, packages/@vue/cli/bin/vue.js, packages/@vue/cli/lib/GeneratorAPI.js, packages/@vue/cli/lib/config.js, packages/@vue/cli/lib/util/stringifyJS.js
It has become a common source of mistakes.
For example, during PR #4363 I've referred to the wrong `options`
several times due to the variable shadowing.
=> style: add a "no-shadow" linter rule

docs/config/README.md, docs/guide/css.md, docs/zh/config/README.md, docs/zh/guide/css.md, packages/@vue/cli-service/__tests__/css.spec.js, packages/@vue/cli-service/lib/config/css.js, packages/@vue/cli-service/lib/options.js
=> feat: allow configuring scss options separately from sass

docs/config/README.md
Link to mini-css-extract-plugin so users can check 
what kind of options they can provide.
close #4401
=> docs(cli-service): Clarify object options for css.extract

docs/guide/deployment.md
Now that ZEIT has launched [zero config deployments](https://twitter.com/zeithq/status/1159145442896166912), deploying a Vue site is now much easier:
=> Adjusted deployment documentation for ZEIT Now

.github/COMMIT_CONVENTION.md, .github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
Now that we do v3 & v4 releases in parallel (even after v4 stable release, v3 will continue to receive bug fixes), I'd like to tweak the git workflow a little bit to make it easier.
So, inspired by Gitflow, I propose that we have two production-ready branches - `master` & `next`. `master` is for the `latest` `dist-tag` version on npm, and `next` for `next` `dist-tag` (pre-release versions). It's not only used for v4 betas, but we can also have prereleases for feature releases in the future.
I've also set up Netlify to deploy https://next.cli.vuejs.org from the `next` branch so that users can preview documentation for the new features.
In the past, the website is deployed from the `docs` branch. It seems not so obvious for many users. Many documentation PRs are targeting the `dev` branch. …
=> chore: use a gitflow-like workflow for the project

packages/@vue/cli-ui-addon-webpack/src/util/assets.js, packages/@vue/cli-ui/apollo-server/connectors/tasks.js, packages/@vue/cli-ui/ui-defaults/utils/audit.js, packages/@vue/cli-ui/ui-defaults/utils/modules.js
This PR removes the useless self-assignments of `Array.sort`.
=> fix: remove self-assignment

packages/@vue/cli-plugin-unit-jest/generator/index.js, packages/@vue/cli-plugin-unit-mocha/generator/index.js
The unit test packages support tests in /tests/unit and \*/\_\_tests\_\_/ folders, but eslint config for jest/mocha  was only applied to the former
This PR adds overrides to the eslint config for files in the latter type of folder so eslint can successfully detect and lint jest/mocha globals
=> fix(eslint): eslint should override env

packages/@vue/cli-plugin-eslint/lint.js, packages/@vue/cli-ui/apollo-server/connectors/locales.js, packages/@vue/cli-ui/apollo-server/resolvers.js, packages/@vue/cli-ui/apollo-server/type-defs.js
split parent path from patterns and add cwd option, make globby working as expected when project path contains parentheses.
close #4417 .
=> chore: add cwd option when calling globby

docs/guide/cli-service.md, docs/guide/html-and-static-assets.md
The 'CLI Service' and 'HTML and Static Assets' docs pages have some minor typos.
=> Documentation typo fixes

packages/@vue/cli/bin/vue.js, packages/@vue/cli/lib/Upgrader.js, packages/@vue/cli/lib/outdated.js, packages/@vue/cli/lib/upgrade.js
It feels a little weird to use `vue upgrade` to check for updates only, so I now move this functionality to a new command `vue outdated`, and `vue upgrade` is interactive now.
=> feat: add `vue outdated` command & make `vue upgrade` interactive

packages/@vue/cli-plugin-babel/generator.js, packages/@vue/cli-plugin-babel/preset.js, packages/@vue/cli-plugin-typescript/__tests__/tsGenerator.spec.js
The current setup relies on the hoisting for `babel.config.js` to be able to access `@vue/babel-preset-app`, since it's not actually part of the package dependencies. This change re-exports it from `@vue/cli-plugin-babel`, which is an actual dependency.
Ref https://github.com/yarnpkg/berry/issues/368
=> fix(cli-plugin-babel): roperly exports the babel preset

packages/@vue/cli/lib/util/generateReadme.js
The generated README was mentionning:
```
npm run test
```
but `npm run test` throws:
Error: no test specified
This removes the mention of this command from the generated README.
=> fix: remove the nonexistent `test` command from generated README

packages/@vue/cli-plugin-e2e-nightwatch/index.js
Nightwatch checks for `nightwatch.conf.js` instead
of the existing `nightwatch.config.js` user options
file, this adds a branch to check for the file
suggested by upstream as well.
Please see https://nightwatchjs.org/gettingstarted#configuration
There are currently no tests for this behaviour. Feel free to point me in the right direction.
=> feat: Check for `nightwatch.conf.js` config

packages/@vue/cli-service/lib/util/prepareProxy.js
fixes #4504
thanks to https://github.com/facebook/create-react-app/pull/7444
=> fix: should not proxy sockjs endpoint

packages/@vue/cli-plugin-e2e-nightwatch/nightwatch.config.js
based on this nightwatch release note:
https://github.com/nightwatchjs/nightwatch/releases/tag/v1.1.12
added the following option for Chromedriver 75
```
chromeOptions: {
w3c: false
}
```
=> fix: fix incompatibility with Chrome 75

packages/@vue/cli/lib/util/generateReadme.js
Removes the `run` command for yarn, as it is useless. Keeps it for the other package managers.
=> docs: remove run for yarn commands in readme

packages/@vue/cli-plugin-e2e-nightwatch/README.md, packages/@vue/cli-plugin-e2e-nightwatch/__tests__/lib/globals-gecko.js, packages/@vue/cli-plugin-e2e-nightwatch/__tests__/lib/globals-generated.js, packages/@vue/cli-plugin-e2e-nightwatch/__tests__/lib/nightwatch.conf.js, packages/@vue/cli-plugin-e2e-nightwatch/__tests__/nightwatchPlugin.spec.js, packages/@vue/cli-plugin-e2e-nightwatch/generator/index.js, packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/custom-assertions/elementCount.js, packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/custom-commands/customExecute.js, packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/custom-commands/openHomepage.js, packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/custom-commands/openHomepageClass.js, packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/globals.js, packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/page-objects/homepage.js, packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/specs/test-with-pageobjects.js, packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/specs/test.js, packages/@vue/cli-plugin-e2e-nightwatch/index.js, packages/@vue/cli-plugin-e2e-nightwatch/nightwatch.config.js, packages/@vue/cli-plugin-e2e-nightwatch/package.json
This PR upgrades the Nightwatch version bundled with the `cli-e2e-nightwatch` plugin to latest v1.2 version. In addition, it adds several new features for running end-to-end tests with Nightwatch in a Vue application a bit more pleasant of an experience.
- switched to using standalone Webdriver (default with [Chromedriver](https://sites.google.com/a/chromium.org/chromedriver/)) instead of with Selenium server
- added support for running tests in Firefox (via [Geckodriver](https://github.com/mozilla/geckodriver/releases))
- added built-in support for running tests in **headless** mode (via `--headless`) with Chrome and Firefox
- updated generated tests and also …
=> Upgrade Nightwatch to v1.2 and update bundled config and generated tests

docs/guide/deployment.md
Edited `Dockerfile` section of https://cli.vuejs.org/guide/deployment.html#docker-nginx
As shown in [Vue v2 cookbook](https://vuejs.org/v2/cookbook/dockerize-vuejs-app.html) copying `package*.json` initially and running `npm install` in a separate step allows caching and reduces time elapsed during Docker build. Also the difference between the two docs will be reduced and be less confusing to those who end up with both of them.
=> Edited Dockerfile of Docker(Nginx) deployment doc

docs/.vuepress/config.js
Currently, our documentation for both next and current version has `Edit this page on GitHub` link leading to `docs` branch while we want docs PRs to target `next` or `master` branch respectively. This PR changes the Vuepress config to target `next` branch on links.
=> docs: fixed vuepress link for next branch

docs/.vuepress/config.js
Currently, our documentation for both next and current version has `Edit this page on GitHub` link leading to `docs` branch while we want docs PRs to target `next` or `master` branch respectively. This PR changes the Vuepress config to target `master` branch on links.
=> docs: changes vuepress link for master branch

packages/@vue/cli-plugin-unit-jest/__tests__/jestGenerator.spec.js, packages/@vue/cli-plugin-unit-jest/__tests__/jestPlugin.spec.js, packages/@vue/cli-plugin-unit-jest/generator/index.js, packages/@vue/cli-plugin-unit-jest/package.json, packages/@vue/cli-plugin-unit-jest/preset/jest-preset.js, packages/@vue/cli-plugin-unit-jest/preset/no-babel/esmoduleTransformer.js, packages/@vue/cli-plugin-unit-jest/preset/no-babel/jest-preset.js, packages/@vue/cli-plugin-unit-jest/preset/typescript-and-babel/jest-preset.js, packages/@vue/cli-plugin-unit-jest/preset/typescript/jest-preset.js
This could significantly reduce the size of default jest boilerplate,
and gives us more control on the internal config details, thus
potentially making future upgrades easier.
=> refactor: move jest configs into presets

packages/@vue/cli-service/__tests__/multiPage.spec.js, packages/@vue/cli-service/lib/config/app.js
=> fix: correctly ignore html templates in copy-webpack-plugin

packages/@vue/cli-plugin-e2e-nightwatch/__tests__/nightwatchPlugin.spec.js, packages/@vue/cli-plugin-e2e-nightwatch/generator/index.js, packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/_eslintrc.js, packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/custom-assertions/elementCount.js, packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/custom-commands/customExecute.js, packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/custom-commands/openHomepage.js, packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/custom-commands/openHomepageClass.js, packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/globals.js, packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/page-objects/homepage.js, packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/specs/test-with-pageobjects.js
=> fix: fix nightwatch template's compatibility with eslint plugin

packages/@vue/cli/lib/util/ProjectPackageManager.js
Use `process.env.VUE_CLI_PACKAGE_MANAGER_BIN` to specify the bin used by `PackageManager`
=> feat: allow custom packageManager other than npm/yarn/pnpm

packages/@vue/cli/lib/util/ProjectPackageManager.js
Turn `Unknown package manager` error into a warning and use the npm subcommands as fallbacks.
=> feat: support custom package manager

packages/@vue/cli-service/__tests__/css.spec.js, packages/@vue/cli-service/lib/config/css.js
=> fix: fix sassOptions merging for scss syntax in sass-loader v8

packages/@vue/cli-plugin-babel/migrator/index.js
In older versions of v4 alpha & beta, we still use `@vue/app` as default babel preset. This should be fixed in the migrator. So we now do this transform regardless of the existing plugin version.
=> fix(babel-migrator): transform babel preset regardless of plugin version

packages/@vue/cli-service/__tests__/css.spec.js, packages/@vue/cli-service/lib/config/css.js
=> fix: avoid accidentally overriding sass config with scss configs

packages/@vue/cli-plugin-unit-mocha/README.md
As of e08603b, this plugin uses mochapack instead of mocha-webpack. Updated the README to reflect this.
=> docs: Reference mochapack in README (#4652) [ci skip]

packages/@vue/cli-service/lib/config/base.js, packages/@vue/cli-service/lib/config/prod.js
As long as the `minimize` option is set to false (which is default in
production mode), the code won't be minimized regardless of the `minimizer` config's presence.
By exposing this config, users can simplify their custom config, by
removing the `process.env.NODE_ENV === 'production'` guard around their
custom minimizer configuration.
=> feat: make the minimizer config available in all modes

docs/guide/css.md, docs/zh/guide/css.md, packages/@vue/cli-service/__tests__/css.spec.js, packages/@vue/cli-service/generator/index.js, packages/@vue/cli-service/lib/config/css.js, packages/@vue/cli-service/package.json
The warning on the loader version was removed to avoid frustrations.
Users could postpone the sass-loader upgrade until they decide to move to Vue CLI v4.
=> [v3] Support sass-loader v8

packages/@vue/cli-service/lib/commands/serve.js
By replacing the `quiet` option with `logLevel: 'silent'`.
Fixes #4599
=> fix: fix redundant log messages from webpack-dev-server

packages/@vue/cli-plugin-pwa/index.js
1. `public/manifest.json` will be used when no `pwa.manifestOptions`
present;
2. warn user when there are both the file & the config field present.
=> feat(pwa): improve compatibility with v3 plugin usage

packages/@vue/babel-preset-app/index.js, packages/@vue/cli-plugin-unit-jest/index.js, packages/@vue/cli-plugin-unit-mocha/index.js
Typically only unit test frameworks do so.
This change will improve the interoperability with Jest editor extensions, etc.
=> feat(babel-preset): set target to node whenever NODE_ENV === 'test'

packages/@vue/cli-service/lib/commands/build/resolveWcConfig.js, packages/@vue/cli-service/lib/config/app.js, packages/@vue/cli-service/lib/config/base.js, packages/@vue/cli-service/lib/util/resolveClientEnv.js
Fixes #4658
The reasoning behind the previous change was stated at #3579.
But after a closer look at the webpack documentation, I see that webpack is only against the `process: { env: { NODE_ENV: JSON.stringify('production') } }` style, which would break the `process` object mock, while, in Vue CLI's base config, only `process.env` is replaced, which has a much smaller impact.
By providing the whole `process.env` object, use cases such as the abovementioned destructuring of `process.env` are now supported, which is more intuitive IMO.
What might be problematic is how users customize their env vars that not started with `VUE_APP`. If they follow our example, they may accidentally override the `process.env` object - we've made that mistake too …
=> refactor!: use DefinePlugin (again) instead of EnvironmentPlugin

packages/@vue/cli-service/lib/config/terserOptions.js, packages/@vue/cli-service/package.json, yarn.lock
The only real breaking change is https://github.com/webpack-contrib/terser-webpack-plugin/issues/129,
which is not likely to affect normal users.
The rest is default option values changes, which are already covered in
the default provided `terserOptions` of Vue CLI.
Note that here we choose to disable `extractComments` by default, as I
don't see enough data showing such license comments taking too much
space. The extra LICENSE file may also be confusing to some users.
=> chore!: upgrade terser-webpack-plugin to 2.x

packages/@vue/cli/lib/util/shouldUseTaobao.js
**What kind of change does this PR introduce?**
**Does this PR introduce a breaking change?**
We've done a large work to make our configuration more uniform, and some configuration keys have changed. One such key is `registry`, which is now called `npmRegistryServer`.
I've also made this code resilient to unforeseen failures.
Ref https://github.com/yarnpkg/berry/issues/368
=> Add a variant for `config get registry`

packages/@vue/cli/bin/vue.js
Sorry for the last-minute breaking change. But I do think it is important to make the branding clearer.
Including the name in the output is also a common practice in command-line tools,
such as `bash`, `brew`, etc. And this change only requires minimal effort for other tools to get the version number from the new output format.
Closes #4514
=> chore!: add `@vue/cli` in `--version` output, to avoid confusion

packages/@vue/cli-service/generator/index.js
=> fix: add a compatibility layer for router & vuex for CLI v3

packages/@vue/cli-plugin-eslint/generator/index.js, packages/@vue/cli-plugin-typescript/generator/index.js, packages/@vue/cli-ui/package.json
Fix the "ENOENT: no such file or directory … debugnode_module/sms/index.js" error.
The problem are caused by 2 issues:
1. The `lint-staged` packages introduced an old version of debug,
causing node_module deduping, thus changing the node_module layout
2. The dependencies required in the cached `lint` module is no longer at
its originial position, thus the "ENOENT" error.
This change still does not fix the PNPM 4 issue, considering its smaller
user base, we'll fix it later.
=> fix: fix "lint on commit" projects generation error

packages/@vue/cli-ui/ui-defaults/suggestions.js, packages/@vue/cli/lib/add.js
=> fix: fix `vue add router` command in v3 projects

packages/@vue/cli/lib/Creator.js
=> fix(v3): do not install core plugins that have major version bumps

packages/@vue/cli-plugin-eslint/index.js
=> fix: fix eslint not found error in `vue serve` command

packages/@vue/cli/lib/Creator.js
Same as the fix for v3: https://github.com/vuejs/vue-cli/pull/4712
=> fix: do not install core plugins that have major version bumps

docs/guide/cli-service.md
=> Fix indentation of --inline-vue description

packages/@vue/cli-ui/apollo-server/connectors/dependencies.js
=> fix(ui): fix latest version check always displaying "0.1.0"

packages/@vue/cli-plugin-eslint/generator/index.js
=> fix(eslint): autofix code style after scaffolding on older versions of cli

packages/@vue/cli/lib/util/clearConsole.js, packages/@vue/cli/lib/util/getVersions.js
=> fix: should tolerate cli version check error

packages/@vue/cli/lib/util/ProjectPackageManager.js
=> feat: support binary mirrors for taobao registry

packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js, packages/@vue/babel-preset-app/index.js, packages/@vue/babel-preset-app/package.json, packages/@vue/cli-plugin-babel/__tests__/babel-runtime.spec.js, packages/@vue/cli-plugin-babel/index.js, packages/@vue/cli-service/__tests__/serve.spec.js
As recommended in babel/babel#9903.
Get rid of the module-resolver plugin, may fix #3928.
Seems to have fixed #4742 as well.
There may be a small breaking change: as we now use `excludes` & `includes`, babel requires `filename` option to be present (introduced in https://github.com/babel/babel/pull/10181/files). So users who call `babel.transformSync` directly may encounter an error.
However, as we explicitly stated that this preset is only used for Vue CLI internally, I don't expect too many such use cases there. And the error messages are clear enough.
Considering the benefits that this PR brings, I think it's an acceptable tradeoff.
=> refactor: use babel overrides to transpile babel runtime helpers

docs/guide/css.md
Moved 'localsConvention' to the same level as 'modules'.
I only tested on macOS.
logs from css-loader's
```
[Function: validate] {
schema: {
additionalProperties: false,
properties: {
url: [Object],
import: [Object],
modules: [Object],
sourceMap: [Object],
importLoaders: [Object],
localsConvention: [Object],
onlyLocals: [Object]
},
type: 'object'
},
errors: null,
refs: {},
refVal: [ [Circular] ],
root: [Circular]
}
```
=> fix docs `css.loaderOptions.css.localsConvention`

packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js, packages/@vue/babel-preset-app/index.js
Fixes #4773
The reasoning is stated at https://github.com/vuejs/vue-cli/issues/4773#issuecomment-548241889
=> fix: add `sourceType: 'unambiguous'` to babel preset

.postcssrc, packages/@vue/cli-service/__tests__/css.spec.js, packages/@vue/cli-service/generator/index.js, packages/@vue/cli-service/lib/config/css.js, packages/@vue/cli-ui-addon-webpack/.postcssrc, packages/@vue/cli-ui-addon-widgets/postcss.config.js, packages/@vue/cli-ui/.postcssrc, packages/@vue/cli/lib/Creator.js
This also fixes the issue with Yarn PnP that requires `autoprefixer` to
be explicitly listed in the user's project dependency.
=> feat: enable postcss+autoprefixer by default internally, reducing boilerplate

docs/guide/deployment.md
=> use gitlab CI env variable for project name

packages/@vue/cli-service/lib/commands/build/formatStats.js
Fixes issue #4667 by implementing the proposal https://github.com/vuejs/vue-cli/issues/4667#issuecomment-548464520 (I opened that issue and checked if this change really fixes the issue I had - it does)
Also gets rid of a node module by using simpler code for removing eventual GET parameters
=> fix(lib): replace "url" module with simple string split (close #4667)

packages/@vue/cli-service/__tests__/Service.spec.js, packages/@vue/cli-service/lib/Service.js
fixes #3338
fixes #4184
Actually I don't know why the slash was added in the first place, seems
extraneous to me.
=> fix: don't prepend publicPath with slash

packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
This PR allows use of pwa.manifestPath: 'https://other-domain.com/manifest.json' and makes more sense when using pwa.manifestCrossorigin: true.
I added support of full url for icons too, because it's the same way of building links.
=> feat: allow use of full url for pwa manifest and icons

docs/guide/build-targets.md, docs/zh/guide/build-targets.md
These warnings are originally stated in the vue-loader documentation,
but the CLI documentation perhaps have more visibility.
Fixes #4832
=> docs: add warnings on CSS sideEffects

packages/@vue/cli/__tests__/Generator.spec.js, packages/@vue/cli/lib/util/runCodemod.js
=> fix: support `parser` option for codemods, and enable ts parsing by default

packages/@vue/cli-shared-utils/lib/logger.js, packages/@vue/cli-shared-utils/package.json
When logging multi-line logs, the logger uses chalk.reset in order to get the length of the tag for the log. This is to achieve an indented layout of multi-line logs. However, chalk.reset only replaces styles such as **bold** and *italic*, not color, see [GitHub issue](https://github.com/chalk/chalk/issues/62). When the tag contains colors, the result is not pretty. Replacing with stripAnsi gets the intended result.
I found this behavior when using the GeneratorApi.exitLog function, when building a custom preset for vue-cli. Any multi-line entry is not well-formatted, and adding multiple exitLog calls gets rather noisy, since the logger adds …
=> Replace chalk.reset with stripAnsi in @vue/cli-shared-utils/lib/logger.js

packages/@vue/cli-service/lib/commands/build/resolveWcEntry.js
`async` is a javascript keyword, so I suggest this variable name will be less prone to error and confusing.
=> changed var-name `async` to `isAsync`

packages/@vue/cli/lib/util/loadRemotePreset.js
=> fix: should download to different directories for different presets

docs/core-plugins/pwa.md
The [navigateFallback](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#generateSW-navigateFallback) option is disabled by default but it is crucial to make an SPA work offline.
I was struggling to make my app work offline until I found this comment: https://github.com/vuejs/vue-cli/issues/717#issuecomment-382079361
So I believe this should be mentioned in the docs.
Feel free to update the wording.
=> docs: mention navigateFallback option for PWA App Shell caching

packages/@vue/cli-plugin-pwa/ui.js
=> fix: fix several bugs in the PWA plugin UI, make it usable again

packages/@vue/cli-plugin-e2e-nightwatch/__tests__/nightwatchPlugin.spec.js, packages/@vue/cli-plugin-e2e-nightwatch/index.js
flag is documented as `--use-selenium` but we checked for `args['with-selenium']`
fix #5015
=> fix(e2e-nightwatch): check for correct flag name

packages/@vue/cli-plugin-e2e-cypress/generator/template/tests/e2e/plugins/index.js
The current cypress config has a global eslint-disable:
typescript
```
/* eslint-disable import/no-extraneous-dependencies, global-require, arrow-body-style */
// const webpack = require('@cypress/webpack-preprocessor')
```
But this assumes that `eslint-import-plugin` is present, whereas this is only true when the selected preset is the Airbnb one.
In other cases, this fails `yarn lint` right away with:
```
error: Definition for rule 'import/no-extraneous-dependencies' was not found (import/no-extraneous-dependencies) at tests/e2e/plugins/index.js
```
Even if using the Airbnb preset, the comment does not have any effect, as, by default, the `require` call is commented.
This commit now splits the rules disabling in two:
- one commented for the people using Airbnb and who will uncomment the …
=> fix: comment eslint disable in cypress config

docs/zh/guide/cli-service.md
the original version in Chinese means `yorkie` is not compatible with `husky` in future version
=> Updated zh-cn translation in cli section

packages/@vue/cli/bin/vue.js, packages/@vue/cli/lib/create.js
- Usage: `vue create --merge .`
- This option works like the `--force` option.
=> feat: add option merge to command create

packages/@vue/cli-service-global/lib/globalConfigPlugin.js
1. they're useful in development
2. to be in line with the default preset
=> feat: don't throw on console/debugger statements for `vue serve`

packages/@vue/babel-preset-app/index.js
`@babel/plugin-transform-runtime` has an option named [version](https://babeljs.io/docs/en/babel-plugin-transform-runtime#version).
By default `@babel/plugin-transform-runtime` assumes that `@babel/runtime@7.0.0-beta.0` is installed, which means helpers introduced later than `7.0.0-beta.0` will be **inlined** instead of **imported**. Which in turn leads to a larger bundle size.
See https://github.com/babel/babel/issues/10261 and https://github.com/facebook/docusaurus/pull/2111
=> feat: specify babel runtime version

packages/@vue/cli-service/lib/Service.js, packages/@vue/cli-service/package.json, packages/@vue/cli-shared-utils/index.js, packages/@vue/cli-shared-utils/lib/pkg.js, packages/@vue/cli-shared-utils/package.json, packages/@vue/cli/lib/Creator.js, yarn.lock
This pull request will close https://github.com/vuejs/vue-cli/issues/4544
=> feat: respect existing package.json

packages/@vue/cli-plugin-router/generator/template/src/router/index.js, packages/@vue/cli-plugin-router/generator/template/src/views/Home.vue, packages/@vue/cli-plugin-typescript/generator/template/src/App.vue, packages/@vue/cli-plugin-typescript/generator/template/src/views/Home.vue, packages/@vue/cli-service/generator/template/src/App.vue
Making components' naming follow [Component name casing in JS/JSX](https://vuejs.org/v2/style-guide/index.html#Component-name-casing-in-JS-JSX-strongly-recommended).
=> 🎨 style: unified components' naming style

docs/zh/config/README.md
=> Update zh-cn translation in config lintOnSave section

packages/@vue/cli-service/__tests__/serve.spec.js, packages/@vue/cli-service/lib/commands/serve.js, packages/@vue/cli-test-utils/launchPuppeteer.js, packages/@vue/cli-test-utils/serveWithPuppeteer.js
Fixes #4947 , see that for details.
=> Use a single websocket connection for HMR

packages/@vue/cli/__tests__/Generator.spec.js, packages/@vue/cli/lib/util/mergeDeps.js
Fixes the following issue:
```
🚀  Invoking generator for vue-cli-plugin-storybook...
ERROR  TypeError: Cannot read property 'match' of undefined
TypeError: Cannot read property 'match' of undefined
at resolveDeps (/home/circleci/vue-cli-plugin-storybook/node_modules/@vue/cli/lib/util/mergeDeps.js:14:27)
at GeneratorAPI.extendPackage (/home/circleci/vue-cli-plugin-storybook/node_modules/@vue/cli/lib/GeneratorAPI.js:195:20)
at module.exports (/home/circleci/vue-cli-plugin-storybook/tmp/node_modules/vue-cli-plugin-storybook/generator/index.js:9:7)
at Generator.initPlugins (/home/circleci/vue-cli-plugin-storybook/node_modules/@vue/cli/lib/Generator.js:150:13)
at Generator.generate (/home/circleci/vue-cli-plugin-storybook/node_modules/@vue/cli/lib/Generator.js:168:16)
at runGenerator …
```
=> fix: extendPackage object values should be string

packages/@vue/cli/lib/Migrator.js, packages/@vue/cli/lib/Upgrader.js
=> fix `afterInvoke`/`onCreateComplete` callbacks in Migrator

docs/migrating-from-v3/README.md
=> docs: mention the precedence of `.vue` & `.ts(x)` extensions

packages/@vue/cli-shared-utils/lib/request.js, packages/@vue/cli/lib/util/ProjectPackageManager.js
=> refactor: use a plain http request to get package metadata

packages/@vue/cli-service/generator/template/public/index.html, packages/@vue/cli-service/lib/config/app.js
=> refactor: use the `title` option in the html template, instead of hard-code the project name

docs/zh/guide/browser-compatibility.md
'@vue/babel-preset-env' to '@vue/babel-preset-app'
- [x ] Docs
=> line 47 according to english version

packages/@vue/cli/lib/Creator.js
This should display the emoji ⚙️ instead of the ascii ⚙ that is used currently. Making the whole thing more consistent with other emojis
=> feat: enforce emoji variation in logs for gear

packages/@vue/cli-shared-utils/lib/module.js
See https://github.com/benmosher/eslint-plugin-import/pull/1591 and https://github.com/benmosher/eslint-plugin-import/pull/1602
As far as I understand, `createRequire` is the only semantically correct way to resolve modules from a different context.
=> refactor: use createRequire to load/resolve modules

packages/@vue/cli-plugin-babel/__tests__/babelMigrator.spec.js, packages/@vue/cli-plugin-eslint/__tests__/eslintMigrator.spec.js, packages/@vue/cli-plugin-eslint/eslintDeps.js, packages/@vue/cli-plugin-eslint/eslintOptions.js, packages/@vue/cli-plugin-eslint/generator/index.js, packages/@vue/cli-plugin-eslint/migrator/index.js, packages/@vue/cli-plugin-eslint/package.json, packages/@vue/cli-test-utils/createUpgradableProject.js
TODO:
- Tests (would like to open another PR to make the migrator easier to test first)
- Documentation? Not sure where to put it.
=> feat: implement a migrator to upgrade to eslint 6

docs/zh/guide/browser-compatibility.md
when use core.js@^3.4.3， you should use ```import "core-js/stable";import "regenerator-runtime/runtime";```
[this is an doc about core.js@3](https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#babelpolyfill)
=> vue-cli@4 use core.js@^3.4.3

packages/@vue/cli-plugin-pwa/README.md, packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
This PR is a bug fix which occure when you specify an URL inside the config's manifestPath option.
The bug is not blocking the `vue-cli-service build` command, but it throws a misleading error because it attemps to create a directory for the manifest, which is impossible when it is a full URL.
=> fix: pwa-plugin avoid generating manifest when path is an URL

packages/@vue/cli-service/lib/PluginAPI.js
follow up of #3865
fixes #4438
=> fix: correctly calculate cacheIdentifier from lockfiles

packages/@vue/cli-service/lib/config/base.js, packages/@vue/cli-service/package.json
Users should be able to remove the `vue-template-compiler` dependency if they use the `vue-next` plugin.
=> fix: vue-template-compiler can be optional if @vue/compiler-sfc presents

packages/@vue/cli-plugin-e2e-cypress/index.js, packages/@vue/cli-plugin-e2e-cypress/package.json
When running vue-cli-service test:e2e,w e currently use the -headless flag to distinguish wether to run `cypress run` (headless) or `cypress open` (interactive mode). Therefore, we remove the `--headless` flag from the args before passing them on to cypress: we expect `cypress run` to run headless anyway by default.
Since then, Cypress.io added the possibility to have `cypress run` execute with a Chrome window open, but not in interactive mode like `cypress open`.
So now when you run `cypress run --browser chrome` (b< calling `vue-ci-service test:e2e --browser chrome`) the tests run automatically, but not headless anymore. To make cypress …
=> fix(e2e-cypress): make --headless work with --browser chrome

docs/guide/deployment.md
At the moment this is done like this: https://github.com/travis-ci/travis.rb#env
=> fix(docs): new travis CLI interface

packages/@vue/babel-preset-app/index.js, packages/@vue/babel-preset-app/package.json, packages/@vue/cli-plugin-babel/index.js, yarn.lock
=> refactor: remove usage of deprecated babel functions, preparing for babel 8

packages/@vue/cli-ui/apollo-server/connectors/dependencies.js, packages/@vue/cli/lib/Creator.js, packages/@vue/cli/lib/Upgrader.js, packages/@vue/cli/lib/add.js, packages/@vue/cli/lib/util/ProjectPackageManager.js, packages/@vue/cli/lib/util/getVersions.js
=> feat: lock minor versions when creating projects / adding plugins

packages/@vue/cli/lib/ui.js
=> fix(cors): fixup #4985, allow same-origin ws requests of any domain

packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/_eslintrc.js
Commit 1b64ff8464c317f8d5616626bf483f582c2e01c3 introduced a nested if in `_eslintrc.js` with the same condition than the wrapping one. I may be missing something really obvious, but I think it was meant to check for TS instead.
=> fix(e2e-nightwatch): fix eslint config generation

packages/@vue/cli-plugin-unit-jest/generator/index.js, packages/@vue/cli-plugin-unit-jest/package.json, packages/@vue/cli-plugin-unit-mocha/generator/index.js, packages/@vue/cli-plugin-unit-mocha/package.json, yarn.lock
See changelog at https://github.com/vuejs/vue-test-utils/blob/v1.0.0-beta.31/CHANGELOG.md#100-beta31-2020-01-18
New projects will be created with this new version.
There are a few breaking changes since beta.29. So we can't automatically migrate existing projects to this new version. Users can upgrade at their own will.
=> feat: create projects with @vue/test-utils beta 31

packages/@vue/cli-plugin-babel/migrator/index.js, packages/@vue/cli-plugin-eslint/migrator/index.js, packages/@vue/cli-plugin-typescript/migrator/index.js, packages/@vue/cli/__tests__/Generator.spec.js, packages/@vue/cli/lib/GeneratorAPI.js, packages/@vue/cli/lib/util/mergeDeps.js
Currently, 3 options are implemented:
- options.prune (defaults to `false`) - Remove null or undefined
fields from the object after merging.
- options.merge (defaults to `true`) deep-merge nested fields, note
that dependency fields are always deep merged regardless of this option.
- options.warnIncompatibleVersions (defaults to `true`) Output warning
if two dependency version ranges don't intersect.
Closes #4779
=> feat(GeneratorAPI): allow passing options to `api.extendPackage`

packages/@vue/cli-shared-utils/lib/env.js, packages/@vue/cli/lib/util/ProjectPackageManager.js
=> fix: should infer package manager from config if there's no lockfile in the project

docs/guide/deployment.md
When you use VueRouter and want to deploy to gh-pages (in a project) you have to set the base property of the VueRouter to the project's name
=> :pencil: docs: Set base property of VueRouter when deploying to gh-pages

packages/@vue/cli/bin/vue.js, packages/@vue/cli/package.json, yarn.lock
=> chore: switch over to leven for command suggestion

docs/guide/installation.md
=> Added basic upgrading instructions

docs/zh/guide/mode-and-env.md
=> docs(zh): update example format

packages/@vue/cli/__tests__/Generator.spec.js, packages/@vue/cli/lib/util/mergeDeps.js
Currently, if we use `api.extendPackage({foo: null}, {prune: true})` the dependency is removed but a warning is logged as the range is invalid:
```
WARN  invalid version range for dependency "foo":
- null injected by generator "my-plugin"
```
This commit fixes it, by skipping the range check if we delete a dependency.
=> fix(GeneratorAPI): remove warning when using extendPackage with prune

packages/@vue/cli/package.json
closes #5161
The root cause of such issues:
`vue-jscodeshift-adapter` requires `vue-template-compiler`.
`vue-template-compiler` tries to require the `vue` package and check
its version on startup.
Normally, there's no `vue` package in the dependency tree of `@vue/cli`,
so this check will just skip.
But if the user has installed some other global package that depend on
`vue`, and hoists it to the root `node_modules`, `vue-template-compiler`
would successfully require it and check against that `vue` version,
which sometimes may be outdated, thus failing the bootstrap process.
So by adding a "vue" dependency to the `@vue/cli` package, we can make sure the `vue-template-compiler` package in the dependency tree can always get the up-to-date version number and pass the test.
**What kind of …
=> fix "Vue packages version mismatch" error caused by other global packages

packages/@vue/cli-plugin-router/generator/index.js, packages/@vue/cli-plugin-router/generator/template/src/router/index.js
This PR adds the type annotation to the const routes in router/index.ts when vue-router and TypeScript are selected in the CLI.
❌If you use the @vue/composition-api with both, router and TS selected, and error will pop up in the console as a shown in this image: [https://i.imgur.com/NXugrHy.png](https://i.imgur.com/NXugrHy.png)
✅ After you add the annotation as stated in this PR there is no error shown in the console: 
[https://i.imgur.com/rq0S34U.png](https://i.imgur.com/rq0S34U.png)
**Note:** ❌ If you add the annotation type like `const routes:<Array<RouteConfig>>` an error will occur and won't accept the error: …
=> types(router): added router array type for Array RouteConfig

packages/@vue/cli-plugin-eslint/README.md
The default target directories of `vue-cli-service lint` command was written as `src` and `test`, but I think that `src` and `tests` are correct. If my opinion is correct, please merge.
Related code here:
https://github.com/vuejs/vue-cli/blob/0380f226b9d5df188622c6bdb3d1b12f8b4e044c/packages/%40vue/cli-plugin-eslint/lint.js#L47-L61
=> docs: fix readme of @vue/cli-plugin-eslint

packages/@vue/babel-preset-app/index.js
=> fix(babel-preset-app): avoid corejs warning when useBuiltIns is false

docs/guide/mode-and-env.md
Inspired by the create-react-app documentation
create-react-app.dev/docs/adding-custom-environment-variables
=> docs: add warning on client side environment variables

packages/@vue/cli/__tests__/args.spec.js
=> test: test case for command suggestion logic

packages/@vue/cli-plugin-eslint/eslintOptions.js, packages/@vue/cli-service-global/lib/globalConfigPlugin.js, packages/@vue/cli-ui-addon-widgets/.eslintrc.js
As ESLint 6 removes this rule from the recommended config
https://eslint.org/docs/user-guide/migrating-to-6.0.0#eslint-recommended-has-been-updated
=> feat: ease the default `no-console` severity to `warn`

packages/@vue/cli-plugin-eslint/__tests__/ui.spec.js, packages/@vue/cli-plugin-eslint/ui/configDescriptor.js
closes #5175
I didn't change the choice name because it's used in translations; didn't change the constant name to keep consistency.
=> fix: fix severity config in ui

packages/@vue/cli-plugin-eslint/package.json, yarn.lock
eslint-loader >= 2.2.0 is supported ESLint 6.  
https://github.com/webpack-contrib/eslint-loader/releases/tag/v2.2.0  
However, package.json `"eslint-loader": "^2.1.2"`.  
If locked version 2.1.2 by user `yarn.lock` or `package-lock.json`, continue to use not supported version.
=> chore(eslint): bump minimum required eslint-loader version to support ESLint 6

packages/@vue/cli-plugin-typescript/index.js, packages/@vue/cli-plugin-typescript/package.json, packages/@vue/cli-plugin-typescript/vue-compiler-sfc-shim.js
Update: I'll let you decide but #5172 is probably a better alternative. See https://github.com/vuejs/vue-cli-plugin-vue-next/issues/5 for more context
The `fork-ts-checker-webpack-plugin` is using `vue-template-compiler` by default, and this compiler is not the correct one to pick for vue-next. This commit tries to load `@vue/compiler-sfc` and falls back to `vue-template-compiler` if it does not find it.
It also bumps the `fork-ts-checker-webpack-plugin` to use v3.1.3
=> feat: use @vue/compiler-sfc as a compiler for TS if available

packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
I think it would be useful to be able to ignore certain icons and not have the link/meta tags link to a missing file.
=> feat(pwa): Check for null or undefined in iconPaths

packages/@vue/cli/lib/Creator.js, packages/@vue/cli/lib/options.js
=> feat(vue-cli): Choosing to save as a preset tells you where it is saved

packages/@vue/cli-service/lib/commands/build/resolveWcConfig.js
This PR allows `globby` to get files from multiple different directories by using comma separated list of file patterns. This way we can also list specific components.
Examples:
`vue-cli-service build --target wc --name myprefix src/components/core*.vue,src/components/basic*.vue`
`vue-cli-service build --target wc --name myprefix src/components/myFirst.vue,src/components/mySecond.vue`
=> Fix wc entry to allow multiple file patterns

packages/@vue/cli-service/__tests__/Service.spec.js, packages/@vue/cli-service/lib/Service.js
Use error code thrown by `require` directly.
This also simplifies module mocking in unit tests.
=> refactor: simplify config loading by skipping `fs.existsSync` check

packages/@vue/cli-service-global/lib/globalConfigPlugin.js, packages/@vue/cli-service-global/package.json
Eliminates the peer dependency warning.
=> chore(cli-service-global): remove direct dependency on `@vue/babel-preset-app`

packages/@vue/cli-ui/ui-defaults/tasks.js
=> fix(cli-ui): build task defaults should respect outputDir option from config file (fix #2639)

packages/@vue/cli-service/__tests__/Service.spec.js, packages/@vue/cli-service/__tests__/ServiceESM.spec.js, packages/@vue/cli-service/__tests__/mockESM/package.json, packages/@vue/cli-service/lib/Service.js, yarn.lock
if `"type": "module"` was set in package.json, the vue service will emit error.
```
ERROR  Error loading vue.config.js:
ERROR  Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: .../vue.config.js
require() of ES modules is not supported.
.../vue.config.js from .../node_modules/@vue/cli-service/lib/Service.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename vue.config.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from .../package.json.
```
this pr enable use of `vue.config.cjs`, as a simple solution in those environment.
**Does this PR …
=> support vue.config.cjs

packages/@vue/cli-shared-utils/index.js, packages/@vue/cli-shared-utils/lib/env.js
fixes #5310
fixes #5286
**What kind of change does this PR introduce?** (check at least one
=> fix: avoid process hanging when trying to get Chrome version

packages/@vue/babel-preset-app/index.js, packages/@vue/babel-preset-app/package.json
Per the discussion at https://github.com/babel/babel/pull/11083,
it should not be considered a breaking change.
Considering we started locking minor versions since v4.2, I believe we can ship this flag enabled by default in v4.3.
Closes #5301
Closes #4848
=> feat: enable `bugfixes` option for babel by default

packages/@vue/cli-ui/locales/en.json
This will change the git initialization commit message placeholder text on the project creation form when using `vue ui`. See https://github.com/vuejs/vue-cli/issues/5280 and https://github.com/vuejs/vue-cli/issues/5280#issuecomment-605369470.
=> fix(ui): change git initialization commit message placeholder text

packages/@vue/cli-plugin-unit-mocha/index.js
This change allows developers to specify a host and port to bind the node debugger to. This is helpful in my case where I am running my application in a docker container and need to allow the debugger to listen on an IP other than the default localhost
=> feat(service): Allow mocha unit tests debugger to be bound to a specified IP and port

packages/@vue/cli/lib/Upgrader.js
Sometimes there may still be errors like `Error: ENOENT: no such file or directory` after running `vue upgrade --all`.
This refactor fixes such issues.
=> fix: run migrator in a separator process, fix require cache issues during upgrade

packages/@vue/cli-plugin-e2e-nightwatch/nightwatch.config.js
I tried scaffolding a new vue-cli project with e2e tests with nightwatch, and it wasn't picking up changes in globals.js. After a bit of digging it seems that the globals.js that was added during the scaffolding wasn't actually being used. Adding this line fixed it.
=> [cli-plugin-e2e-nightwatch] fixing globals.js import

packages/@vue/cli-service/generator/template/_gitignore
I have just added an entry for `pnpm-debug.log` to the `_gitignore` generator file, it is the pnpm equivalent of the debug logs for `npm` and `yarn`, which are already present.
=> Added 'pnpm-debug.log' to '_gitignore'

docs/core-plugins/pwa.md
=> docs: explain pwa head/manifest icons

docs/zh/guide/README.md
scaffold 用做动词时，翻译为搭建更合适，而不是脚手架。
When scaffold is used as a verb, it is more appropriate to translate it to 搭建(similar to create) rather than 脚手架(scaffolding)。
脚手架(scaffolding)只是个名词，没有搭建的意思。
Scaffolding is just a noun, there is no meaning of 搭建(similar to create)
=> fix: the translation of  the scaffold

packages/@vue/cli-shared-utils/lib/openChrome.applescript
Sometimes the script "openBrowser" takes a lot of time, and during this period, dev server is blocked and cannot handle any request。
=> fix: set timeout of openChrome.applescript

packages/@vue/cli/lib/GeneratorAPI.js
=> fix: normalize the `file` argument of `transformScript`, fix Windows compatibility

packages/@vue/cli-service/lib/commands/build/index.js
Mentioned in Issue #1597.
The `serve` command was addressed with PR #2411, this adds the same functionality to the `build` command, useful when watching in development (for example, a Elixir Phoenix watcher).
```
vue-cli-service build --mode development --watch --stdin
```
=> feat(cli-service) add stdin flag to build

packages/@vue/cli/lib/util/ProjectPackageManager.js
Update ProjectPackageManager.js upgrade() method: manage multiple package names separated by spaces
This fixes https://github.com/vuejs/vue-cli/issues/5295
Tested for both NPM and Yarn
Fixes https://github.com/vuejs/vue-cli/issues/5295
=> Update ProjectPackageManager.js upgrade() method: manage multiple package names separated by spaces

packages/@vue/cli-plugin-eslint/index.js
add the .eslintignore file to the cache generation algorithm
- [] Other, please describe:
`eslint-loader` 运行时会生成 `cache` ，再次运行时，会检查 `cache` 是否可用
理论上 `.eslintignore` 发生变化时， `cache` 应该失效，重新运行
但 `@vue/cli-plugin-eslint` 没有把该文件加入 `cache` 的生成算法中
从而导致了当  `.eslintignore` 发生变化时，`cache`没有失效，`eslint` 忽略规则没有生效
所以需要将 `.eslintignore` 文件加入到 `cache` 处理中
=> fix(eslint): invalidate the cache when `.eslintignore` changes

packages/@vue/cli-service/lib/commands/serve.js
When you change the `devServer.sockPath` setting, one of the required `webpack-devserver-client` ignores the `sockPath` setting. This is visible in your developer console: the local sockjs url connects but the network sockjs fails.
This is caused by incorrectly providing the `sockPath` to the webpack client. It infers the host and port from the provided URL parameter but not the sockPath, which has to be specified as an additional parameter. This PR removes the path part from the `sockjsUrl` (as it does nothing) and adds the `sockPath` as additional param.
=> fix(serve): pass devServer sockPath properly to client

packages/@vue/cli-plugin-unit-mocha/index.js
The `Array.splice()` method was implemented wrong, removing a number of flags or parameters based on the position of `--inspect-brk` rather than just that flag itself.
=> fixed --inspect-brk flag clobbering other values

packages/@vue/cli/lib/add.js
=> fix: allow specifying plugin version when calling `vue add`

packages/@vue/cli-plugin-unit-jest/__tests__/jestPlugin.spec.js, packages/@vue/cli-plugin-unit-jest/presets/no-babel/jest-preset.js
=> fix(unit-jest): fix .vue coverage report when babel plugin is not enabled

__mocks__/inquirer.js, packages/@vue/cli/lib/Creator.js, packages/@vue/cli/lib/invoke.js
closes #5167
also closes #5124
Note: custom prompt types are not supported in the CLI UI
=> feat(plugin-api): expose `inquirer` to prompts.js, allowing custom prompt types

packages/@vue/cli-service/__tests__/Service.spec.js, packages/@vue/cli-service/__tests__/ServiceESM.spec.js, packages/@vue/cli-service/__tests__/mockESM/package.json, packages/@vue/cli-service/lib/Service.js, packages/@vue/cli-shared-utils/lib/module.js
reverts #5305
this makes the tests a little more tedious, need to find a better way
to test these functionalities
fixes #5442
=> fix: should throw errors if there is bad require() in vue.config.js

packages/@vue/cli/lib/Creator.js
=> fix(cli): fix the creation log

packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js, packages/@vue/babel-preset-app/index.js, packages/@vue/babel-preset-app/package.json, packages/@vue/babel-preset-app/polyfillsPlugin.js
It is both a bugfix and refactoring.
Fixes #5507.
Fixed:
- Should also apply the `polyfills` option to the modern mode target
Improved:
- Should provide the exact version of core-js instead of a vague `3` to `@babel/preset-env`, making the polyfills more accurate and up-to-date
- By calculating the intersection of modern browsers and browserslist targets, we may come to a much narrower range of browsers, thus greatly reducing the final bundle size. It may even yield a better result than the `bugfixes` option of `@babel/preset-env`.
=> refactor: improve the polyfill importing logic of modern mode

packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js, packages/@vue/babel-preset-app/index.js
Pass not just the useBuiltIns and corejs options, but the whole envOptions object, into the @babel/preset-env preset that is used to transform @babel/runtime, just like for the @babel/preset-env that is used for the application source code. This allows users to also specify other options, such as `exclude` and `polyfills`, and have them apply here too.
In particular, this can be used to exclude the Promise polyfill, e. g. if Promise is already polyfilled in some other way. Previously,
```js
exclude: ['es.promise'],
polyfills: ['es.array.iterator', 'es.object.assign'],
```
could be used to configure the preset for the application source code, but the babel runtime would be transformed without those options, and so es.promise would still end up being included.
Closes #5208
**What kind of …
=> feat(babel-preset-app): pass full config to @babel/preset-env

packages/@vue/cli/lib/Creator.js
The user's custom generator may generate a commitlint, add `--no-verify` to fix the git initial commit.
=> fix: add `--no-verify` to initial git commit

packages/@vue/cli-service/lib/commands/serve.js
#4891 
Vue CLI forgot to process the webpack failed hook in the serve command.
=> fix(cli-service): process the webpack failed hook in the serve command

packages/@vue/cli-plugin-typescript/vue-compiler-sfc-shim.js
Fixes the line padding to retain diagnostics location
=> fix: correctly shim @vue/compiler-sfc for fork-ts-checker-plugin

docs/guide/cli-service.md
https://github.com/vuejs/vue-cli/issues/4485
Document [`vue-cli-service serve`](https://cli.vuejs.org/guide/cli-service.html#vue-cli-service-serve) command default serve entry.
=> docs: serve command default entry value

docs/config/README.md, docs/ru/config/README.md, docs/zh/config/README.md
=> docs: translation update

docs/core-plugins/eslint.md, packages/@vue/cli-plugin-eslint/README.md
=> docs: update cli eslint plugin configuration

packages/@vue/cli-plugin-e2e-nightwatch/generator/index.js
=> fix(nightwatch): should not install corresponding webdriver if the browser is unselected

packages/@vue/cli/lib/util/ProjectPackageManager.js, packages/@vue/cli/package.json
=> fix: support auth token when retrieving package metadata

packages/@vue/cli-plugin-e2e-cypress/index.js
Since we always call `removeArg(rawArgs, 'config')`, and since the `matchRE` matches `--config` as well as `--config-file`, we end up ignoring the `--config-file` option if it is provided (e.g. `--config-file my-config.json`).
This commit fixes this by ensuring that calling `removeArg('config')` removes `--config` without removing `--config-file`.
=> Fix: stop ignoring --config-file cypress option

docs/zh/dev-guide/plugin-dev.md
=> docs: translate plugin-dev

packages/@vue/cli-plugin-e2e-nightwatch/generator/index.js
=> fix(nightwatch): compat with legacy presets without `webdrivers` field

packages/@vue/cli-service/lib/Service.js
Though, it is still a bad practice to use `VUE_CLI_SERVICE_CONFIG_PATH`
in a project with `vue.config.js`
closes #5584
=> fix: fix an edge case that VUE_CLI_SERVICE_CONFIG_PATH might be ignored

packages/@vue/cli-service/__tests__/Service.spec.js, packages/@vue/cli-service/lib/Service.js, packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js
=> fix polyfill injection when building app on multiple threads

packages/@vue/cli/lib/util/ProjectPackageManager.js
Some registry servers do not recognize `application/vnd.npm.install-v1+json`
in the Accept header, so here we add `application/json` as fallback.
=> fix: fix support for some legacy registry servers

packages/@vue/cli/package.json, yarn.lock
Fixes #5612
TODO: @babel/preset-env can be removed when we switch over from
jscodeshift to vue-codemod
=> fix jscodeshift peer dependency error

packages/@vue/cli-service/bin/vue-cli-service.js, packages/@vue/cli/bin/vue.js
=> feat: support node nightly builds

packages/@vue/babel-preset-app/index.js
=> fix: better error message for non-existent polyfill names

docs/zh/dev-guide/plugin-dev.md
This PR has been cancelled ([5642](https://github.com/vuejs/vue-cli/pull/5642))
<br>
<br>
This  link  is not displayed correctly 👇
<br>
<br>
<br>
<br>
<br>
Hi there, this is my first contribution, and  **I am eager to get this merged** . Thx~       
@sodatea 
<br>
=> fix(doc-zh): The link cannot be displayed correctly

docs/guide/deployment.md
=> Update Firebase project link

docs/guide/css.md, docs/zh/guide/css.md
=> sass-loader 9.0注入教程 从master推送到master

packages/@vue/babel-preset-app/README.md, packages/@vue/babel-preset-app/index.js, packages/@vue/babel-preset-app/package.json, yarn.lock
There needs to be an option to force set the Vue version for JSX transformation. But I'm not very sure what the API should be like if it has to be backward compatible. So let's leave it for the next major version, or until someone comes up with a good design.
=> feat: use Vue 3 JSX plugin if Vue 3 is detected in the project

docs/guide/css.md, docs/ru/guide/css.md, docs/zh/guide/css.md
Closes #5648 
In sass-loader v9, the `prependData` option was removed in favor the `additionalData` option. [Changelog](https://github.com/webpack-contrib/sass-loader/releases/tag/v9.0.0).
=> docs: additionalData option for sass-loader 9.0

packages/@vue/cli-plugin-typescript/generator/template/tsconfig.json, packages/@vue/cli-plugin-typescript/prompts.js
References:
- It's turned on by default with `tsc --init` https://github.com/microsoft/TypeScript/pull/37808 https://github.com/formium/tsdx/issues/529#issuecomment-598304924
- It's turned on by default in `create-react-app` https://github.com/facebook/create-react-app/pull/5903
- It's turned on by default in Angular CLI https://github.com/angular/angular-cli/pull/16682 https://github.com/angular/angular-cli/issues/16696
Pros:
- Greatly speeds up TypeScript compilation (not a big issue in Vue CLI because we use [fork-ts-checker-webpack-plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin))
- Both TypeScript and Vue minor version updates, though as widely tested as they can go, still have chances to break existing type definitions. Users' projects should not break because …
=> feat: add `skipLibCheck` option in the TS template (defaults to `true`)

packages/@vue/cli-service/lib/commands/serve.js
While configuring a new Kubernetes cluster for [CodeSandbox Containers](https://codesandbox.io/docs/environment#container-environment), I've noticed that HMR was not working (again, see #2795). The reason seems to be that cgroup naming has changed in recent Kubernetes versions, and the regex at https://github.com/vuejs/vue-cli/blob/11d60d537e7f748420bf69c086adcbda6769a0e8/packages/@vue/cli-service/lib/commands/serve.js#L300 doesn't match anymore. This PR fixes the regex to match the new cgroup name, adding an optional `.slice` after `kubepods`.
I also went ahead and added a special detection for CodeSandbox Containers, by checking if the …
=> Fix Kubernetes container detection

packages/@vue/cli-shared-utils/lib/logger.js
=> refactor: use console.clear to clear the log

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/config.yml
added the new issue template configuration options. Awesome new feature 🎉
copied from https://github.com/vuejs/vue/pull/10777
=> chore: add issue template config.yml

packages/@vue/cli-plugin-typescript/index.js, packages/@vue/cli-plugin-typescript/package.json, yarn.lock
Fixes #5712
Note this is an optional dependency so that we don't break compatibility
with Node.js v8.
=> fix: use fork-ts-checker-webpack-plugin v5 for vue 3 type checking

packages/@vue/cli-service/package.json
fixes #5715
*What kind of change does this PR introduce?** (check at least one)
=> fix: make vue-loader-v16 an optional dependency, avoid crashing npm 5

packages/@vue/cli-service/migrator/index.js
=> feat: implement a migrator that removes `vue-cli-plugin-next` as it's no longer needed

packages/@vue/cli/lib/util/readFiles.js
=> fix: ignore `.svn/**` when reading and writing files

packages/@vue/cli-plugin-typescript/generator/index.js, packages/@vue/cli-plugin-typescript/generator/template/tsconfig.json
=> fix: fix skipLibCheck default value for `vue create`

packages/@vue/cli-plugin-e2e-webdriverio/generator/template/wdio.shared.conf.js, packages/@vue/cli-service/generator/template/_gitignore
This allows us to have a more accurate path to specify in .gitignore
=> refactor: output webdriverio logs to `tests/e2e/logs`

packages/@vue/cli-service/lib/commands/build/formatStats.js
=> chore: use `stdout.columns` to determine the stats table width

CHANGELOG.md, docs/config/README.md, docs/dev-guide/ui-localization.md, docs/guide/deployment.md, packages/@vue/babel-preset-app/index.js, packages/@vue/cli-plugin-e2e-nightwatch/__tests__/lib/globals-generated.js, packages/@vue/cli-plugin-eslint/generator/index.js, packages/@vue/cli-plugin-typescript/__tests__/tsPluginTSLint.spec.js, packages/@vue/cli-service/lib/config/terserOptions.js, packages/@vue/cli-service/lib/util/resolveLoaderError.js, packages/@vue/cli/__tests__/invoke.spec.js, packages/@vue/cli/lib/GeneratorAPI.js, packages/@vue/cli/lib/util/confirmIfGitDirty.js
For reference: https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings/For_machines
=> [Fix] common misspelling errors

packages/@vue/cli-plugin-e2e-webdriverio/generator/index.js, packages/@vue/cli-plugin-e2e-webdriverio/package.json, packages/@vue/cli-plugin-typescript/generator/index.js, packages/@vue/cli-plugin-typescript/generator/template/tsconfig.json
A better fix is to use different `tsconfig` for E2E or unit testing files, but I haven't got the time to figure it out. So adding this as a temporary workaround.
=> fix: add missing mocha type if wdio is not installed along with any unit testing frameworks

packages/@vue/cli-service/lib/config/base.js
=> fix: load vue from `@vue/cli-service-global` on `vue serve`/`vue build`

packages/@vue/cli/bin/vue.js
Closes https://github.com/vuejs/vue-cli/issues/5761
=> fix: missing proxy argument

packages/@vue/cli-service/lib/util/prepareProxy.js
if the proxy path is `/`,  `isPublicFileRequest` will be `/path/to/project/dist/` which is always exist by `fs.existSync(isPublicFileRequest)`. Therefore, it is also necessary to determine whether `isPublicFileRequest` is a file.
=> fix: mayProxy.isPublicFileRequest judgment

packages/@vue/cli-service/__tests__/serve.spec.js, packages/@vue/cli-service/__tests__/serveVue3.spec.js, packages/@vue/cli-service/lib/config/base.js
The old alias `@vue/runtime-dom` was introduced because webpack HMR has
trouble with pure re-exports. Now that the `vue.runtime.esm-bundler.js`
file also includes a call to `initDev`, it's no longer an issue. This
also enables Dev Tool in Vue 3 runtime.
Fixes #5785
=>  fix: ensure Dev Tool is enabled in Vue 3 runtime

docs/dev-guide/plugin-dev.md
I've tested the example code on the docs, however it didn't work. After wrapping the file path with api.resolve it worked.
=> fix: writeFileSync path was missing api.resolve

packages/@vue/cli/__tests__/Generator.spec.js, packages/@vue/cli/lib/GeneratorAPI.js
=> fix: do not throw when api.render is called from an anonymous function

docs/guide/installation.md, docs/zh/guide/installation.md
It's recommended to use NPM v6 with Node.js v8, because:
1. Some of the upstream packages may accidentally introduce dependencies
that require Node.js 10+ in the `engines` field. This only leads to a
warning in NPM but will break Yarn.
2. NPM v5 does not support dependency versions starting with `npm:`,
so it can't support Vue 3 related features in Vue CLI.
Also added recommendation for `n` as the Node version manager because `nvm` sometimes causes problems for Vue CLI UI.
=> docs: update Node version requirement to address package manager issues

packages/@vue/cli/lib/util/ProjectPackageManager.js, packages/@vue/cli/package.json
To deal with malformed stdout result retrieved from child processes.
Fixes #5802
=> fix: strip non-ansi characters from registry config

packages/@vue/cli/lib/Creator.js
Fixes #5818 
~~If the git config option `commit.gpgSign` is set
to `true`, passes the flag `--no-gpg-sign` when
creating the initial commit, then warns user that
initial commit is not signed and instructs how
to sign the initial commit~~
If git config `commit.gpgSign = true`, then warning on failed initial commit is expanded to also state that failure to commit could
be due to failure to sign commit. Also sets the `commit.gpgSign` config to `false` if testing or debugging.
~~This PR will change `vue create` to *never* sign the initial commit. My personal opinion is that this is the preferred behavior, since I wouldn't want to default to …
=> Handle GPG sign git config for initial commit

packages/@vue/cli/bin/vue.js, packages/@vue/cli/lib/Creator.js, packages/@vue/cli/lib/util/ProjectPackageManager.js
=> fix: fix support for Node.js v8 and deprecate it

packages/@vue/cli-ui/src/components/dashboard/WidgetAddPane.vue
I'm currently studying the project to see patterns used in real world projects, and I found this logic that's currently being used, but it seems like there is not much need for it?
I would like if possible your opinion on why you guys decided to use the ListFilter, instead of a cleaner solution? 
Thank you
=> Remove ListFilter logic

docs/guide/deployment.md, docs/zh/guide/deployment.md
=> Docs: Change zeit to vercel

packages/@vue/babel-preset-app/README.md, packages/@vue/babel-preset-app/index.js, packages/@vue/babel-preset-app/package.json
=> chore: rename jsx package scope from ant-design-vue to vue

packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
=> fix: allow turning off theme color tags

docs/zh/guide/plugins-and-presets.md
=> 更新远程preset文档，与英文文档同步

packages/@vue/cli-plugin-router/__tests__/routerGenerator.spec.js, packages/@vue/cli-plugin-router/generator/template-vue3/src/App.vue, packages/@vue/cli-service/__tests__/generator.spec.js, packages/@vue/cli-service/generator/index.js, packages/@vue/cli-service/generator/template/src/App.vue, packages/@vue/cli-service/generator/template/src/main.js
=> fix: fix duplicate id="app" in Vue 3 project template

packages/@vue/cli-service/lib/config/base.js, packages/@vue/cli-service/package.json, yarn.lock
These are enabled by default in the `@vue/babel-preset-app`.
Fixes #5863
Fixes #5866
This don't fix the case where the user has enabled more custom syntax in
babel. `@vue/compiler-sfc` needs to fail gracefully in such cases.
=> fix: enable some syntax extensions by default for vue script compiler

packages/@vue/cli/lib/Creator.js
Fix the issue described at https://github.com/vuejs/vue-cli/pull/5823#issuecomment-690269893
This simplifies the logic, thus less error-prone.
The error message is still correct anyway.
=> fix: skip checking git gpgSign config

packages/@vue/cli/lib/util/ProjectPackageManager.js
This should fix the remaining issue reported in #5411.
In particular, if the user configured a dedicated npm registry for a
specific scope, this setting was previously disregarded by vue-cli.
Thus it was impossible to use vue upgrade if the packages were not also
published to the official npm registry.
=> fix: respect scope when resolving package metadata

packages/@vue/cli-plugin-pwa/__tests__/pwaPlugin.spec.js, packages/@vue/cli-service/__tests__/build.spec.js, packages/@vue/cli-service/__tests__/cors.spec.js, packages/@vue/cli-service/__tests__/modernMode.spec.js, packages/@vue/cli-service/__tests__/multiPage.spec.js, packages/@vue/cli-service/lib/config/app.js
Fixes #5896
It's also recommended to enable this option with caution in the
html-minifier documentation:
<http://perfectionkills.com/experimenting-with-html-minifier/#remove_attribute_quotes>
=> fix: shouldn't remove attribute quotes in HTML

.github/CONTRIBUTING.md
```bash
$ yarn link
---> warning There's already a package called "@vue" registered. This command has had no effect. If this command was run in another folder with the same name, the other folder is still linked. Please run yarn unlink in the other folder if you want to register this folder.
```
=> docs: add yarn link error solution

packages/@vue/cli/lib/util/ProjectPackageManager.js
The binary mirrors are configured by the meta information in the `versions` field.
=> fix: incorrectly read Taobao binary mirror configuration.

docs/guide/deployment.md
Added a small fix related to PWAs deployed on Netlify. If you don't exclude the `_redirects` file, the service worker will try to cache it but it won't be able to find the file in the netlify servers and as a result the service worker installation will fail, which will break all the PWA functionalities, so we need to exclude the file through workbox exclude option.
=> Updated netlify docs for vue/cli-plugin-pwa

docs/guide/webpack.md
Adding description that vue inspect defaults to development and how to see the production config details and rules.
=> docs: add notes on the `vue inspect` command

packages/@vue/cli/lib/util/clearConsole.js, packages/@vue/cli/lib/util/getGlobalInstallCommand.js, packages/@vue/cli/lib/util/loadCommand.js
such as `@vue/cli-service-global` & `@vue/cli-init`
=> fix: more accurate warning message for missing global peer dependencies

packages/@vue/cli-service/lib/commands/build/resolveWcConfig.js
=> chore: show error message that the `wc` target with Vue 3 isn't supported yet

docs/migrations/migrate-from-v4.md, packages/@vue/cli-plugin-unit-mocha/generator/index.js, packages/@vue/cli-plugin-unit-mocha/package.json, yarn.lock
Closes #5423
Backlog:
Mochapack hasn't support Mocha v8 & Webpack v5 so we can't upgrade to these versions yet.
=> chore!: bump unit-mocha dependency versions

docs/guide/deployment.md
This pull request updates the Vercel deployment documentation to match what Vercel recommends users can do to deploy for the greatest chance of success.
=> Update Vercel deployment instructions

packages/@vue/cli-plugin-eslint/README.md, packages/@vue/cli-plugin-eslint/__tests__/eslintPlugin.spec.js, packages/@vue/cli-plugin-eslint/index.js, packages/@vue/cli-plugin-eslint/lint.js
Add an `output-file` option to the ESLint plugin that saves lint report results to the specified file path.
This mimics the [ESLint option](https://eslint.org/docs/user-guide/command-line-interface#options) of the same name
Closes #4849
=> feat(lint): add output file option (close #4849)

docs/migrations/migrate-from-v4.md, packages/@vue/cli-plugin-typescript/index.js, packages/@vue/cli-plugin-typescript/package.json
=> feat!: bump fork-ts-checker-webpack-plugin version to v5

packages/@vue/cli/lib/util/ProjectPackageManager.js
=> fix: npm 7 compat by turning on `legacy-peer-deps` flag

packages/@vue/cli-plugin-eslint/package.json
=> fix: narrow the eslint peer dep version range, avoiding npm 7 error

packages/@vue/cli-plugin-typescript/generator/template-vue3/src/shims-vue.d.ts
https://github.com/vuejs/vue-next/commit/6aa2256913bfd097500aba83b78482b87107c101 intriduced a change in `DefineComponent` type, that results in a broken bare CLI app that would use VTU, as `mount` will not compile.
This relaxes the type definitation by using generic `any`.
Fixes #5974
=> fix: update vue-shims for Vue v3.0.1

packages/@vue/cli-service-global/template/index.html, packages/@vue/cli-service/generator/template/public/index.html, packages/@vue/cli-service/lib/config/index-default.html
Fixes #5945
`lang="en"` may be wrong to users, use empty string instead. See : https://github.com/h5bp/html5-boilerplate/issues/1542
=> fix: using `lang` attribute with empty string in html template

packages/@vue/cli-plugin-e2e-webdriverio/__tests__/wdioGenerator.spec.js, packages/@vue/cli-plugin-e2e-webdriverio/generator/index.js, packages/@vue/cli-plugin-unit-jest/__tests__/jestGenerator.spec.js, packages/@vue/cli-plugin-unit-jest/generator/index.js, packages/@vue/cli-plugin-unit-mocha/__tests__/mochaGenerator.spec.js, packages/@vue/cli-plugin-unit-mocha/generator/index.js
=> fix(unit-jest, unit-mocha): ensure EOL in existing tsconfig.json

packages/@vue/cli-service/types/ProjectOptions.d.ts
Personally, I have found it frustrating working with `vue.config.js`, due to lack of type information available.  Yesterday I discovered https://github.com/vuejs/vue-cli/issues/2138#issuecomment-484520356 , and was delighted to see I had a bit more info, but still not as much as I'd like.  
This commit adds JSDoc documentation (from `docs/config/README.md`) to add better editor support for `vue.config.js`
=> types(vue.config.js): add descriptions for config

docs/zh/dev-guide/plugin-dev.md
=> docs(zh): correction of some format problems

packages/@vue/cli-ui/apollo-server/util/notification.js
This prevents SnoreToast from installing a Start Menu shortcut by specifying an `appID`. The `appID` is also used to set the
notification's title bar text in Windows 10. That text is now set to "Vue UI", which replaces the default value of "SnoreToast".
fixes #2720
*Screenshot of desktop notification on Windows 10:*
*Screenshot of notification bar on Windows 10:*
=> fix: prevent snoretoast shortcut, set notif title (#2720)

packages/@vue/cli-plugin-typescript/prompts.js
TSLint options have been removed. [#5065](https://github.com/vuejs/vue-cli/pull/5065/files#diff-e24fb13625fcff6df42f64355ccad136579fbf2932b01d32a4a9a01e0756124b) `getPrompts` would break `convertJsToTs` prompt. https://github.com/vuejs/vue-cli/issues/2676
=> fix(cli-plugin-typescript): remove getPrompts function in prompts.js

docs/migrations/migrate-from-v4.md, packages/@vue/cli-service/package.json, packages/@vue/cli/lib/util/ProjectPackageManager.js
=> chore!: drop support of NPM 5

packages/@vue/cli-plugin-e2e-cypress/index.js
Hello @sodatea,
As discussed on Saturday, this PR simulates peer dependencies for cypress the same way as ESlint.
It circumvents the breaking change to have cypress a peer dependency.
=> fix(cypress): allow users to update cypress

packages/@vue/cli-service/lib/commands/serve.js
close #3220
Prevent "Invalid Host" error by passing public host through to webpack-dev-server when `--public` is used
When you use the `public` option in webpack-dev-server [it'll automatically allow requests from the specified host](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L926-L935), without needing the additional `allowedHosts[]` or `disableHostCheck` options. However when the `--public` option in Vue CLI was used, the value was not passed through to webpack-dev-server (as HMR client injection is handled separately) so you still got the `Invalid host` error in that case.
This PR extracts the host from the …
=> fix(cli-service): pass --public host to devserver

packages/@vue/cli-plugin-unit-mocha/index.js, packages/@vue/cli-service/package.json
Fixes https://github.com/vuejs/vue-loader/issues/1734
=> fix(mocha): disable SSR optimization for Vue 3 testing

packages/@vue/cli-service/__tests__/build.spec.js, packages/@vue/cli-service/package.json
=> chore: webpack-bundle-analyzer to ^4.1.0

packages/@vue/cli/__tests__/args.spec.js, packages/@vue/cli/bin/vue.js
=> chore(cli): return with an exit code of 1 on supplying an unknown command

packages/@vue/cli-service/__tests__/generator.spec.js, packages/@vue/cli-service/generator/index.js, packages/@vue/cli/lib/options.js, packages/@vue/cli/lib/promptModules/__tests__/cssPreprocessors.spec.js, packages/@vue/cli/lib/promptModules/cssPreprocessors.js, packages/@vue/cli/lib/util/ProjectPackageManager.js, packages/@vue/cli/lib/util/inferRootOptions.js, packages/@vue/cli/types/cli-test.ts, packages/@vue/cli/types/index.d.ts
The `node-sass` package is deprecated so it shouldn't be used anymore https://sass-lang.com/blog/libsass-is-deprecated#how-do-i-migrate
=> chore: remove deprecated node-sass

.eslintignore, packages/@vue/cli-service/lib/commands/build/.gitignore, packages/@vue/cli-service/lib/commands/build/resolveWcConfig.js, packages/@vue/cli-service/lib/commands/build/resolveWcEntry.js, packages/@vue/cli-service/package.json, yarn.lock
Fixes https://github.com/yarnpkg/berry/issues/2189
Ref https://github.com/vuejs/vue-cli/issues/5135
When building web components (`--target wc`) `@vue/cli-service` tries to write an `entry-wc.js` file to itself which breaks when running multiple builds in parallel or when using Yarn PnP.
=> fix(cli-service): don't write entry-wc to node_modules

packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js
See https://github.com/babel/babel/pull/10862
=> test: should not expect babel polyfill paths to be extension-less

packages/@vue/cli-plugin-e2e-nightwatch/__tests__/nightwatchPlugin.spec.js, packages/@vue/cli-plugin-eslint/__tests__/eslintPlugin.spec.js, packages/@vue/cli-plugin-eslint/index.js, packages/@vue/cli-plugin-eslint/package.json, packages/@vue/cli-service-global/__tests__/globalService.spec.js, packages/@vue/cli-service-global/lib/globalConfigPlugin.js, packages/@vue/cli-ui/vue.config.js, yarn.lock
close #5926, using `eslint-webpack-plugin` can fix the problem of `eslint-loader` caused by `cache-loader`, related issue: #3065,  #5399, #4425
eslint@7 contains a break change related to [plugin resolution](https://eslint.org/docs/user-guide/migrating-to-7.0.0#plugin-resolution-has-been-updated)
> In previous versions, ESLint resolved all plugins from the current working directory by default. Starting in ESLint v7.0.0, plugins are resolved relative to the directory path of the entry configuration file.
After checking the [rfc](https://github.com/eslint/rfcs/blob/master/designs/2019-plugin-loading-improvement/README.md), I  believe new …
=> feat: replace eslint-loader by eslint-webpack-plugin

docs/config/README.md
files -> file
Signed-off-by: Hollow Man hollowman@hollowman.ml
In `Whether to extract CSS in your components into a standalone CSS file`, `file` should use the singular form according to the context and the Chinese version `是否将组件中的 CSS 提取至一个独立的 CSS 文件中`.
=> Fix Grammar Mistake in Docs

packages/@vue/cli/package.json
It's only used in the `linkBin` function, which is used for setting up
testing projects.
=> chore: update cmd-shim and move it to devDependencies

docs/guide/webpack.md, docs/ru/guide/webpack.md, docs/zh/guide/webpack.md
See the reasoning at https://github.com/Akryum/vue-cli-plugin-apollo/pull/463
=> docs: don't add `.loader()` when modifying vue-loader options

packages/@vue/cli/lib/util/linkBin.js
`cmd-shim@4`  return `Promise` now. `require('util').promisify` will break the expected behavior, it only works for `callback`.
=> fix: fix usage of cmd-shim

packages/@vue/cli-plugin-eslint/__tests__/eslintPlugin.spec.js, packages/@vue/cli-plugin-eslint/index.js
ESlint 7 has move code formatter to `eslint/lib/cli-engine/formatters/codeframe` but we have not change the path
=> fix: eslint formatter path error

packages/@vue/cli/package.json
The only notable change may be dropping support of the include
preprocessor directive, which I don't know any Vue CLI plugin is using.
<https://github.com/mde/ejs/pull/478/files>
=> chore!: bump ejs to v3

packages/@vue/cli-plugin-unit-mocha/generator/index.js, packages/@vue/cli-plugin-unit-mocha/package.json, packages/@vue/cli-plugin-webpack-4/README.md, packages/@vue/cli-plugin-webpack-4/generator.js, packages/@vue/cli-plugin-webpack-4/index.js, packages/@vue/cli-plugin-webpack-4/package.json, packages/@vue/cli-shared-utils/lib/pluginResolution.js
More and more webpack plugins no longer support webpack 4 in their most
recent versions. For better webpack 5 compatibilities and easier upgrades
in the future, we should update these dependencies.
So it makes sense to extract webpack-4-specific dependencies and logic
to a standalone package.
While the task is not that urgent at the moment, and I haven't got the
time to complete this refactor, I think we should at least have a
placeholder package here, so that users don't have to add this
dependency manually in later prerelease versions.
=> feat: add a @vue/cli-plugin-webpack-4 package for future use

docs/core-plugins/babel.md, packages/@vue/cli-plugin-babel/README.md, packages/@vue/cli-plugin-babel/index.js, packages/@vue/cli-plugin-babel/package.json, packages/@vue/cli-service/lib/PluginAPI.js
It's supposed to have better performance.
See https://github.com/babel/babel-loader/issues/525#issuecomment-375756108
Besides, this improves webpack 5 compatibility as cache-loader is now
deprecated
=> refactor: replace cache-loader with babel-loader's built-in cache

docs/zh/dev-guide/plugin-dev.md
lines[renderIndex] + = `\n router,` => lines[renderIndex] += `\n router,`
=> fix docs type error;  `+ =` => `+=`

docs/guide/mode-and-env.md, docs/zh/guide/mode-and-env.md
=> mode-and-env doc need be updated

package.json, packages/@vue/cli-plugin-eslint/eslintDeps.js, packages/@vue/cli-plugin-eslint/package.json, packages/@vue/cli-plugin-typescript/package.json, packages/@vue/cli-plugin-unit-jest/package.json, packages/@vue/cli-service/package.json, packages/@vue/cli-test-utils/package.json, packages/@vue/cli-ui/apollo-server/connectors/configurations.js, packages/@vue/cli-ui/package.json, packages/@vue/cli/lib/util/stringifyJS.js, packages/@vue/cli/package.json, yarn.lock
The only remaining production dependencies that are not up-to-date are:
- `sass-loader`
- `css-loader`
- `commander`
- `execa`
All of them may require non-trivial changes to the code.
=> chore: some trivial dependency version bumps

packages/@vue/cli/__tests__/Generator.spec.js, packages/@vue/cli/lib/Generator.js
make afterInvoke/afterAnyInvoke code more readable and add test
=> refactor(generator): minor refactor afterInvoke/afterAnyInvoke

packages/@vue/cli-service/package.json, yarn.lock
Vue CLI v5.0.0-alpha.0 uses `rule.resolve` in the CLI service (see https://github.com/vuejs/vue-cli/blob/v5.0.0-alpha.0/packages/@vue/cli-service/lib/config/base.js#L17-L20) which was introduced in webpack-chain v6.5.0.
See https://github.com/neutrinojs/webpack-chain/blob/master/CHANGELOG.md#v650
As the CLI service defines a dependency to webpack-chain v6.4.0, this causes issues in existing projects when trying to upgrade to the CLI v5.
Upgrading an existing project leads to `yarn build` throwing:
```
TypeError: Cannot read property 'set' of undefined
at /Users/ced-pro/Code/ninjasquad/vue-ebook/book-tests/node_modules/@vue/cli-service/lib/config/base.js:20:19
at /Users/ced-pro/Code/ninjasquad/vue-ebook/book-tests/node_modules/@vue/cli-service/lib/Service.js:240:40
at Array.forEach …
```
=> chore: use webpack-chain v6.5.1

packages/@vue/cli/__tests__/Generator.spec.js, packages/@vue/cli/lib/Generator.js, packages/@vue/cli/lib/util/writeFileTree.js
avoid overwriting the file which is not modified when executing `vue add/invoke`
This fix is related to #5939 **in some degree**
**Other information:** none
=> fix(generator): avoid doing redundant write operations

packages/@vue/cli/lib/GeneratorAPI.js
https://cli.vuejs.org/zh/dev-guide/plugin-dev.html#generator
Although in this passage, it is suggested that we should change ".env" to "_env" to solve the problem of uploading npm packages. But there will also be such a demand, the files in `generator/template` are dynamically pulled from the git repository at runtime, and there may be `.env` files in the repository, so this pr can solve the problem here
=> feat(cli): make globby includes dot files

docs/guide/cli-service.md
Simplify language, omit unnecessary use case example to better align with tone of other feature descriptions
=> Update skip plugins section of cli-service

packages/@vue/cli-plugin-unit-jest/presets/default/jest-preset.js
Add missing assets to default present `jest-transform-stub` regex. A better solution to #6169.
N/A
=> fix: add missing jest-transform-stub media types (#6169)

packages/@vue/cli-service/lib/commands/serve.js
To support history route mode, we current make `webpackDevServer` to redirects all requests to the entry html.
All 404 requests will be redirected, including requests for non-existent js/css files. In the case of JS files, this will usually result in a JS syntax error while try to execute html content as javascript.
And if the user code needs to use 404 errors, for example, `docisfy` will try to load `_sidebar.md` from multiple url one by one, all the way to the success one, this will lead to `docisfy`  never try to load next url  because the first request will be either success or redirect to entry html,  and will never return 404.
this PR …
=> fix(cli-service): restrict request headers of historyApiFallback in WebpackDevServer

packages/@vue/cli-plugin-pwa/lib/noopServiceWorker.js
**What kind of change does this PR introduce?**
**Does this PR introduce a breaking change?**
Hi,
currently Google Chrome prevents installing local pwa due to the error: "Page does not work offline". The reason is service worker has to listen to `fetch` event. Since in localhost we serve `noopServiceWorker` we should not cache any requests thus fetch listener should be an empty function.
The reason why i think this change is important is, pwa technologies are quite complex and there are already lots of debugging involved, so being able to quickly see (+) install icon in google chrome will prevent early giving up on pwa by new comers.
Unfortunately I couldnt find docs explaining why `fetch` listener is needed, the solution is taken from this [stackoverflow …
=> fix pwa installability when using noopServiceWorker "Page does not work offline"

docs/migrations/migrate-from-v4.md, packages/@vue/cli-service/__tests__/css.spec.js, packages/@vue/cli-service/generator/index.js, packages/@vue/cli-service/lib/config/css.js, packages/@vue/cli-service/package.json, yarn.lock
=> feat!: bump default sass-loader version to v10, drop sass-loader v7 support

package.json, packages/@vue/cli-ui/package.json, yarn.lock
It causes peer dependency warnings because of several ill-maintained
apollo packages, but let's just ignore them.
Fixes #6191
=> fix: should use graphql v15 at all levels of dependency

docs/core-plugins/eslint.md
The documentation mentions all files in the `src` and `tests` directories are linted by default. Upon inspection of the [sourcecode](https://github.com/vuejs/vue-cli/blob/3eaef4d388c52ea1d698991e7e96497164f90a04/packages/%40vue/cli-plugin-eslint/lint.js#L55) however, it seems that also Javascript files in the root directory are being linted by default.
I stumbled upon this when trying to figure out why my `.eslintrc.js` file itself was being linted by running `vue-cli-service lint` without passing any args.
=> Fix documentation on default linted files

packages/@vue/cli/lib/util/ProjectPackageManager.js
When username and password are configured in the .npmrc for the
respective scope, use basic auth when getting package metadate from the
npm registry.
Cf. https://github.com/vuejs/vue-cli/issues/6206
=> fix: use basic auth for npm registry access

packages/@vue/cli-plugin-unit-mocha/generator/index.js
Note this plugin is compatible with cli-service v4, therefore users can
upgrade to it separately for mocha major version upgrades
=> fix(unit-mocha): shouldn't require webpack-4 plugin with cli-service v4

packages/@vue/cli-ui/src/components/content/TerminalView.vue, packages/@vue/cli-ui/src/components/dashboard/Widget.vue, packages/@vue/cli-ui/src/components/dashboard/WidgetAddPane.vue, packages/@vue/cli-ui/src/components/file-diff/FileDiffChange.vue, packages/@vue/cli-ui/src/components/folder/FolderExplorer.vue, packages/@vue/cli-ui/src/components/prompt/PromptsList.vue, packages/@vue/cli-ui/src/components/view/ViewNav.vue, packages/@vue/cli-ui/src/components/view/ViewNavButton.vue
=> refactor: fix eslint warnings in the cli-ui codebase

packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js
=> fix: "commonjs2" target should not be used with "output.library"

packages/@vue/cli-plugin-babel/index.js
See the reasoning at https://github.com/facebook/create-react-app/pull/7633
This change should improve the build speed for large projects
=> chore: disable cacheCompression for babel-loader by default

packages/@vue/cli/lib/util/ProjectPackageManager.js
Avoid empty `node_modules` when the user has set `NODE_ENV` to
`production` in the shell environment.
In the long run, we should have a more comprehensive preflight check
for execution environment though.
=> fix: discard `NODE_ENV` when installing project dependencies

packages/@vue/cli-plugin-typescript/generator/template/tsconfig.json
Added this option in the template because vue-class-component introduced [a new API](https://github.com/vuejs/vue-class-component/issues/465) that encourages users to set `useDefineForClassFields: true`.
It would also make sense for non-class component users to enable this option as it follows the standard class field behavior AFAIK.
Ref: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier
=> feat(typescript): add `useDefineForClassFields` option in tsconfig template

docs/config/README.md, docs/guide/cli-service.md, docs/zh/config/README.md, docs/zh/guide/cli-service.md, packages/@vue/cli-service/lib/commands/build/index.js
=> fix(cli-service): avoiding recreating dist directory

packages/@vue/cli/bin/vue.js, packages/@vue/cli/lib/migrate.js, packages/@vue/cli/package.json, yarn.lock
=> chore: upgrade commander to v7

packages/@vue/cli-service/lib/config/css.js
When the user set the project public path to the absolute path, the extract-css publicPath option should be changed synchronously
N/A
=> fix: mini-css-extract-plugin publicPath option can be an absolute path

docs/guide/css.md
sass-loader is incompatible with webpack 4 since https://github.com/webpack-contrib/sass-loader/releases/tag/v11.0.0. It might be good to include a note for users stumbling upon this problem.
=> Add note about loader incompatible with webpack 4

packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
While #6247 was closed and called a dupe of #6236. This warning will still occur if the plugin needs to generate a manifest.json file.
This PR will address the deprecation warning and fix the issue.
=> fix(cli-plugin-pwa): webpack5 warning for emitting manifest.json

packages/@vue/cli-ui/apollo-server/connectors/projects.js, packages/@vue/cli-ui/locales/en.json, packages/@vue/cli/__tests__/Creator.spec.js, packages/@vue/cli/lib/Creator.js
Now that most Vue 3 core packages has reached stable, I think it makes
sense to remove the word "Preview".
Remaining dependencies to reach stable:
- @vue/test-utils 2.x (in RC)
- vue-class-component 8.x (in RC)
- vue-jest v5 (in alpha)
=> chore: remove the word "Preview" from vue 3 preset

packages/@vue/cli/__tests__/Generator.spec.js, packages/@vue/cli/lib/util/mergeDeps.js
=> fix(generator): support npm package aliases ("@npm:" in version specifier)

packages/@vue/cli-shared-utils/lib/logger.js
String padding does not calculate the length of the line and spaces, which makes the log look strange.（Sorry, I am not good at English, these words are translated by Google）
=> fix: correctly pad log strings

packages/@vue/cli-plugin-webpack-4/generator.js, packages/@vue/cli/__tests__/Generator.spec.js, packages/@vue/cli/lib/GeneratorAPI.js, packages/@vue/cli/lib/util/mergeDeps.js, packages/@vue/cli/types/cli-test.ts, packages/@vue/cli/types/index.d.ts
Sometimes we need to force using an older version of a dependency, such
as in the webpack-4 plugin.
=> feat(GeneratorAPI): `forceOverwrite` option for `extendPackage`

docs/config/README.md, docs/guide/css.md, docs/migrations/migrate-from-v4.md, packages/@vue/cli-service/__tests__/css.spec.js, packages/@vue/cli-service/lib/Service.js, packages/@vue/cli-service/lib/config/css.js, packages/@vue/cli-service/lib/options.js, packages/@vue/cli-service/package.json, yarn.lock
=> feat!: upgrade to css-loader 5; remove `css.requireModuleExtension` & `css.modules` options

packages/@vue/cli-plugin-unit-jest/__tests__/jestPlugin.spec.js, packages/@vue/cli-plugin-unit-jest/package.json, packages/@vue/cli-plugin-unit-jest/presets/no-babel/jest-preset.js, yarn.lock
This PR only updates vue-jest and its corresponding config.
Need to do a refactor later to fix the complicated peer dependency requirements.
The new version of `vue-jest` uses babel 7, so existing `jest.globals['vue-jest'].babelConfig` may break if they rely on babel 6 features.
=> chore!: update vue-jest to v4.x

docs/migrations/migrate-from-v4.md, packages/@vue/cli-plugin-unit-jest/generator/index.js, packages/@vue/cli-plugin-unit-jest/migrator/index.js, packages/@vue/cli-plugin-unit-jest/package.json
vue-jest now requires several different peer deps for vue 2 and vue 3;
ts-jest now requires typescript as peer dep, which should be optional
for unit-jest plugin users because they might choose not to use
typescript.
Both are causing annoying peer dep warnings.
So it only makes sense to move them to the project level, to keep things
clean.
=> refactor!: move vue-jest and ts-jest to peer dependencies

docs/guide/mode-and-env.md
As a beginner, I was confused with the parentheses staging line of the example. I thought the parentheses were the pattern to make the env variable work. I hope the change that I made could help.
=> Minor change on the staging mode example

packages/@vue/cli-service/bin/postinstall.js, packages/@vue/cli-service/generator/hotfix-npm6only.js, packages/@vue/cli-service/generator/index.js, packages/@vue/cli-service/package.json
=> fix: work around npm6/postcss8 hoisting issue

docs/config/README.md, docs/zh/config/README.md, packages/@vue/cli-service/lib/Service.js, packages/@vue/cli-service/types/index.d.ts
Just like the API with the same name in Vite.
<https://vitejs.dev/config/>
=> feat: a `defineConfig` API from `@vue/cli-service` for better typing support in `vue.config.js`

docs/config/README.md, docs/core-plugins/babel.md, docs/migrations/migrate-from-v4.md, docs/zh/config/README.md, packages/@vue/cli-plugin-babel/__tests__/babelRuntime.spec.js, packages/@vue/cli-plugin-babel/__tests__/transpileDependencies.spec.js, packages/@vue/cli-plugin-babel/index.js, packages/@vue/cli-service/lib/options.js, packages/@vue/cli-service/types/ProjectOptions.d.ts
=> feat: when `transpileDependencies` is set to `true`, transpile all dependencies in `node_modules`

packages/@vue/cli-service/lib/config/app.js
=> feat(cli-service): add inline loader support for html-webpack-plugin

packages/@vue/cli-plugin-unit-mocha/setup.js
related to https://github.com/vuejs/vue-next/pull/2929
[CI log](https://app.circleci.com/pipelines/github/vuejs/vue-cli/951/workflows/03898f80-f144-4f64-adf9-a4d49f170bfd/jobs/25648)
=> fix(mocha): workaround the SVGElement issue in Vue

packages/@vue/cli-service/lib/commands/serve.js
Respect the existing 'devtool' when running dev server
Fixes #6398
=> fix(cli-service): respect the existing 'devtool'

package.json, packages/@vue/cli-plugin-typescript/__tests__/tsPluginBabel.spec.js, packages/@vue/cli-service/__tests__/Service.spec.js, packages/@vue/cli-service/__tests__/ServiceESM.spec.js, packages/@vue/cli-service/__tests__/css.spec.js, packages/@vue/cli-service/lib/Service.js, packages/@vue/cli-service/lib/util/checkWebpack.js, packages/@vue/cli-service/lib/util/loadFileConfig.js, packages/@vue/cli-service/lib/util/resolveUserConfig.js, packages/@vue/cli-service/package.json, yarn.lock
In Node.js 12.17+ only.
Otherwise, the `--experimental-modules` flag need to be turned on for
Node.
Not compatible with `eslint-import-resolver-webpack`.
Closes #4477
=> feat: support `vue.config.mjs`

packages/@vue/cli-plugin-babel/__tests__/transpileDependencies.spec.js, packages/@vue/cli-service/__tests__/build.spec.js, packages/@vue/cli-service/__tests__/cors.spec.js, packages/@vue/cli-service/__tests__/cssPreprocessors.spec.js, packages/@vue/cli-service/__tests__/modernMode.spec.js, packages/@vue/cli-service/__tests__/multiPage.spec.js, packages/@vue/cli-service/lib/commands/build/index.js, packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js, packages/@vue/cli-service/lib/util/targets.js, packages/@vue/cli-service/lib/webpack/ModernModePlugin.js, packages/@vue/cli-service/package.json, packages/@vue/cli-ui/src/components/content/TerminalView.vue, packages/@vue/cli-ui/ui-defaults/tasks.js
1. Documentation hasn't been updated. But I'd like to do the overhaul in a separate PR later;
2. I chose the `--no-module` name over `--no-modern` because I think it better reflects the actual usage of `script type="module"`. And the base browser targets for ES module support isn't that modern as we are now at years after its initial introduction.
I'm also working on a `--module-only` option in a separate PR.
=> feat!: turn on modern mode by default, and provide a `--no-module` option

packages/@vue/babel-preset-app/index.js, packages/@vue/cli-service/__tests__/modernMode.spec.js, packages/@vue/cli-service/bin/vue-cli-service.js, packages/@vue/cli-service/lib/commands/build/index.js, packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js, packages/@vue/cli-service/lib/util/targets.js, packages/@vue/cli-service/lib/webpack/DashboardPlugin.js, packages/@vue/cli-service/lib/webpack/ModernModePlugin.js, packages/@vue/cli-service/lib/webpack/SafariNomoduleFixPlugin.js
Also no `type="module"` thing. Because webpack does not emit actual ES module code anyway. That was just for differential loading.
=> feat: only needs one bundle if all targets support es module

docs/guide/browser-compatibility.md, docs/guide/cli-service.md, docs/zh/guide/browser-compatibility.md, packages/@vue/cli-service/__tests__/modernMode.spec.js, packages/@vue/cli-service/lib/commands/build/index.js, packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js, packages/@vue/cli-service/lib/webpack/ModernModePlugin.js
=> feat!: always inject safari-nomodule-fix as an external script; drop `--no-unsafe-inline` flag

packages/@vue/cli/bin/vue.js
From [v5.0.0](https://github.com/tj/commander.js/releases/tag/v5.0.0), `Commander.js` displays help information for missing subcommand by default.
=> chore(cli): rely on default arg parser behaviour

docs/migrations/migrate-from-v4.md, package.json, packages/@vue/cli-plugin-babel/package.json, packages/@vue/cli-plugin-e2e-cypress/package.json, packages/@vue/cli-plugin-e2e-nightwatch/package.json, packages/@vue/cli-plugin-e2e-webdriverio/package.json, packages/@vue/cli-plugin-typescript/package.json, yarn.lock
Default Cypress version is now v7
=> chore: some dependency version bumps

packages/@vue/cli-plugin-typescript/generator/template/tsconfig.json
there are 11 [recommended tsconfig options](https://www.typescriptlang.org/tsconfig#forceConsistentCasingInFileNames), we should add the missing one **forceConsistentCasingInFileNames**.
Also **importHelpers** is useless if target `esnext` and if **importHelpers** is true, we should add **tslib** in deps(not impl it in this PR).
=> feat(plugin-typescript): add all recommended tsconfig

packages/@vue/cli-service/generator/index.js
As Vue 3 does not, and likely will not support IE11.
https://github.com/vuejs/rfcs/pull/294
=> fix: should not include IE11 target in Vue 3 projects

packages/@vue/cli-ui-addon-webpack/package.json, packages/@vue/cli-ui-addon-widgets/.browserslistrc, packages/@vue/cli-ui/package.json
1. Saves a lot of build time.
2. Somehow the modern mode bundle fails Cypress tests **only in electron headless mode**. I never reproduced the error in real browsers. Dropping the legacy bundle fixes the CI issue.
=> feat!: drop IE11 support in CLI UI

docs/migrations/migrate-from-v4.md
=> docs: add modern mode changes to the migration guide

.circleci/config.yml, packages/@vue/cli-ui/tests/e2e/specs/g1-projects.js, packages/@vue/cli-ui/tests/e2e/specs/g2-plugins.js, packages/@vue/cli-ui/tests/e2e/support/index.js
=> ci: fix random failing ui tests

packages/@vue/cli-ui/apollo-server/connectors/projects.js, packages/@vue/cli-ui/package.json, packages/@vue/cli-ui/src/components/project-create/ProjectCreate.vue
Capital letters are no longer allowed.
Supersedes #5096 (see more reasoning in that PR)
closes #2547
closes #5032
closes #6436
=> fix!: keep project name validation rules in sync between UI and CLI

packages/@vue/cli-plugin-typescript/index.js, packages/@vue/cli-plugin-typescript/package.json
- The typescript plugin depends on `vue-template-compiler` when using Vue 2 but it isn't declared
- `@babel/core` isn't provided to `babel-loader`
- The compiler passed to `fork-ts-checker-webpack-plugin` isn't resolved making it rely on hoisting
=> fix(typescript): add missing dependencies and `require.resolve` compiler

docs/guide/deployment.md
https://github.com/github/renaming
=> replace master with main to reflect GH default

packages/@vue/cli-plugin-unit-mocha/generator/index.js, packages/@vue/cli-plugin-unit-mocha/package.json, yarn.lock
mochapack 2.1.0 has added webpack 5 support
Closes #6412
=> feat: support webpack 5 in unit-mocha plugin

packages/@vue/cli-service/lib/webpack/SafariNomoduleFixPlugin.js, packages/@vue/cli-service/package.json
Writing plain objects to `compilation.assets` can cause the following error:
```
UnhandledPromiseRejectionWarning: TypeError: asset.map is not a function
at getTaskForFile (/home/kael/Documents/vuetifyjs/vuetify-next/packages/docs/node_modules/webpack/lib/SourceMapDevToolPlugin.js:88:47)
at /home/kael/Documents/vuetifyjs/vuetify-next/packages/docs/node_modules/webpack/lib/SourceMapDevToolPlugin.js:272:22
at /home/kael/Documents/vuetifyjs/vuetify-next/packages/docs/node_modules/webpack/lib/Cache.js:93:5
```
=> fix(SafariNomoduleFixPlugin): use RawSource instead of a plain object

packages/@vue/cli-service/lib/util/resolveUserConfig.js
Webpack 5 introduced an 'auto' publicPath feature in [webpack/pull/11258](https://github.com/webpack/webpack/pull/11258). The `ensureSlash` will currently add the slash regardless of the actual public path, so the feature would be obsolete.
I encountered the problem while creating a micro-frontend with the webpack 5's module federation. We want the public path to be the one micro frontend is deployed to, which webpack can automatically infer([module-federation/#infer-publicpath-from-script](https://webpack.js.org/concepts/module-federation/#infer-publicpath-from-script), there is a tip at the end of the paragraph).
=> fix(webpack): slash on publicPath: 'auto'

docs/guide/deployment.md
=> Fixed some minor typos

packages/@vue/cli-plugin-typescript/__tests__/tsGenerator.spec.js, packages/@vue/cli-plugin-typescript/generator/index.js, packages/@vue/cli-service/__tests__/Service.spec.js, packages/@vue/cli-service/lib/Service.js, packages/@vue/cli-shared-utils/__tests__/pluginOrder.spec.js, packages/@vue/cli-shared-utils/index.js, packages/@vue/cli-shared-utils/lib/pluginOrder.js, packages/@vue/cli/__tests__/Generator.spec.js, packages/@vue/cli/lib/Creator.js, packages/@vue/cli/lib/Generator.js
If there is nothing wrong with the code and design, I can try to add documentation
By default, the plugins are executed in the same order as before I believe
related to #5106, #6251
```ts
interface Plugin {
(): any
after?: string|Array<string>
}
```
**vue-cli-plugin-foo/generator/index.js**
```js
module.exports = api => {
api.render('./template')
}
```
**vue-cli-plugin-bar/generator/index.js**
```js
module.exports = api => {
api.render('./template')
}
module.exports.after = 'vue-cli-plugin-bar'
```
the 'after' can be used to fine-tune the execution order
Topological Sort Algorithm sorts the plugins by 'after'. see [leetcode …
=> feat: implement plugin execution order

packages/@vue/cli-service/lib/commands/build/resolveWcEntry.js, packages/@vue/cli-service/lib/config/base.js, packages/@vue/cli-service/lib/config/vue-loader-v15-resolve-compat/vue-loader.js, packages/@vue/cli-service/package.json, yarn.lock
So that users won't refer to random third-party packages when they see
error messages from the aliased package.
=> chore: use scoped package names for aliases

packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
HtmlWebpackPlugin has a `voidTag` parameter that needs to be set to true
so that both `<link>` and `<meta>` are treated as void elements (with no
contents). The `closeTag` parameter doesn't exist anymore since HtmlWebpackPlugin 4.
https://github.com/jantimon/html-webpack-plugin/blob/570f735c237d4a03a65622cfe64652431aca4132/typings.d.ts#L280
https://html.spec.whatwg.org/multipage/syntax.html#void-elements
=> fix(pwa): Replace closeTag parameter with voidTag for HtmlWebpackPlugin

packages/@vue/cli-plugin-unit-jest/generator/index.js, packages/@vue/cli-plugin-unit-jest/migrator/index.js, packages/@vue/cli-plugin-unit-jest/package.json
Eventually, we need to update to Jest 27 + vue2-jest / vue3-jest
So let's make it a peer dependency to ease the pain of breaking changes.
To not surprise existing beta users, jest 26 is still listed as a direct
dependency in the next release.
=> feat(unit-jest): add jest as a peer dependency

packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js
the value of `isModuleBuild` is false here, so you can write anything for the property, but it's better to write it correctly.
```js
config
.plugin('modern-mode-legacy')
.use(ModernModePlugin, [{
targetDir,
TYPO_PROP: false
}])
class ModernModePlugin {
constructor ({ targetDir, isModuleBuild }) {
this.targetDir = targetDir
this.isModuleBuild = isModuleBuild
}
// ...
}
```
=> fix(cli-service): wrong property name (typo)

packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js, packages/@vue/cli-service/lib/commands/build/resolveWcConfig.js, packages/@vue/cli-service/lib/config/app.js, packages/@vue/cli-service/lib/config/base.js
Since Webpack 4 support was dropped and Webpack 5 became the only supported version, there is no longer a need to check Webpack version for version-specific code. The code to support the older version has been removed.
This PR removes the Webpack version checks and older version-specific code.
=> refactor: remove redundant Webpack version checks

packages/@vue/cli-service/lib/config/app.js
By adding a placeholder plugin with the same name and options as
copy-webpack-plugin.
Fixes #6648
Addresses the concern raised by @tomica at https://github.com/vuejs/vue-cli/commit/cd783766755fcb6b7e8c558984c58e2b8b305c09#commitcomment-52141775
=> fix: avoid copy-webpack plugin errors in module mode

docs/migrations/migrate-from-v4.md, packages/@vue/cli-plugin-eslint/__tests__/eslintPlugin.spec.js, packages/@vue/cli-service/__tests__/multiPage.spec.js, packages/@vue/cli-service/__tests__/serve.spec.js, packages/@vue/cli-service/lib/commands/serve.js, packages/@vue/cli-service/package.json, packages/@vue/cli-test-utils/launchPuppeteer.js, yarn.lock
=> feat!: upgrade to webpack-dev-server v4

packages/@vue/cli-plugin-eslint/__tests__/eslintPlugin.spec.js, packages/@vue/cli-plugin-eslint/generator/index.js, packages/@vue/cli-plugin-eslint/index.js, packages/@vue/cli-plugin-eslint/lint.js, packages/@vue/cli-service/types/cli-service-test.ts, scripts/buildEditorConfig.js, scripts/release.js
This PR replaces CLIEngine with the ESLint class.
CLIEngine will be removed in eslint v8 and must be replaced with the ESLint class to support eslint v8.
Options may be affected by this change, but should not affect the options listed in the README.
https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-eslint#readme
=> feat(cli-plugin-eslint): use ESLint class instead of CLIEngine

packages/@vue/cli-plugin-e2e-webdriverio/generator/template/tests/e2e/pageobjects/app.page.js, packages/@vue/cli-plugin-e2e-webdriverio/generator/template/tests/e2e/specs/app.spec.js, packages/@vue/cli-plugin-e2e-webdriverio/index.js, packages/@vue/cli-plugin-e2e-webdriverio/migrator/index.js, packages/@vue/cli-plugin-e2e-webdriverio/package.json
[WebDriverIO's sync API has been deprecated](https://webdriver.io/blog/2021/07/28/sync-api-deprecation/) and doesn't work in Node.js v16.
If users still need it, they can install the dependency by themselves.
=> refactor(webdriverio)!: don't include sync API support by default

docs/guide/creating-a-project.md
The command output section was not up to date with the current `vue create --help` output missing `--merge` and `--skipGetStarted`.
Unfortunately, I can't provide zh and ru translations 🥲
If someone could provide the translations I could add them too
=> docs: update vue create --help output in "Basics/Creating a Project"

packages/@vue/cli-plugin-unit-jest/migrator/index.js
small fix for invalid semver, as indicated when running migrator:
🚀  Running migrator of @vue/cli-plugin-unit-jest
WARN  invalid version range for dependency "@vue/vue3-jest":
- ^27.0.0.alpha.1 injected by generator "@vue/cli-plugin-unit-jest"
📦  Installing additional dependencies...
=> fix(migrator): fix invalid semver

docs/migrations/migrate-from-v4.md, package.json, packages/@vue/cli-plugin-eslint/eslintDeps.js, packages/@vue/cli-ui-addon-webpack/package.json, packages/@vue/cli-ui-addon-webpack/src/main.js, packages/@vue/cli-ui-addon-widgets/package.json, packages/@vue/cli-ui-addon-widgets/src/main.js, packages/@vue/cli-ui/package.json, yarn.lock
=> feat(generator)!: bump eslint-plugin-vue to v8

packages/@vue/babel-preset-app/package.json, packages/@vue/cli-plugin-typescript/index.js, packages/@vue/cli-plugin-typescript/package.json, packages/@vue/cli-service/__tests__/generator.spec.js, packages/@vue/cli-service/generator/index.js, packages/@vue/cli-service/lib/config/base.js, packages/@vue/cli-service/package.json
Starting from vue 3.2.13, it's bundled into the main vue package,
accessible via `vue/compiler-sfc`
This commit is incompatible with Vue >= 3.0.0-alpha.0 < 3.2.13
=> feat!: remove `@vue/compiler-sfc` from peer dependencies

packages/@vue/cli/__tests__/Generator.spec.js, packages/@vue/cli/lib/util/__tests__/extendJSConfig.spec.js, packages/@vue/cli/lib/util/configTransforms.js, packages/@vue/cli/lib/util/extendJSConfig.js
So that users can have better IntelliSense by default.
=> feat: generate `vue.config.js` with `defineConfig` wrapper

package.json, packages/@vue/cli-plugin-babel/package.json, packages/@vue/cli-plugin-eslint/package.json, packages/@vue/cli-plugin-pwa/package.json, packages/@vue/cli-plugin-typescript/package.json, packages/@vue/cli-service/package.json, yarn.lock
Because `xxhash64` is only supported in 5.54+
Fixes issues like https://github.com/vuejs/vue-cli/issues/6806#issuecomment-963375201
=> fix: require webpack 5.54+

packages/@vue/cli-service/lib/config/assets.js
=> fix: [ext] in asset modules already contains a leading dot

packages/@vue/cli-plugin-vuex/generator/template-vue3/src/store/index.js, packages/@vue/cli-plugin-vuex/generator/template/src/store/index.js
=> Add `getters:{}` to cli-plugin-vuex template

packages/@vue/cli-service/package.json, yarn.lock
This allows to use the `reactivityTransform` option introduced in this version to enable Vue v3.2.26 new transform features.
=> chore: use vue-loader v17

docs/.vitepress/theme/AlgoliaSearchBox.vue, docs/.vitepress/theme/index.js, docs/.vitepress/theme/search.svg, package.json, yarn.lock
the CLI documentation search index hasn't been updated to the new version of docsearch (which vitepress requires).
So I migrated some of the code from the vuepress version to use docsearch.js 2.x instead.
=> docs(next): fix algolia search

packages/@vue/cli-service/lib/commands/serve.js
Closes https://github.com/vuejs/vue-cli/issues/6896
=> fix: use `setupMiddlewares`, avoid dev server deprecation warnings

packages/@vue/cli-ui/tests/e2e/specs/g1-projects.js, packages/@vue/cli/__tests__/Creator.spec.js, packages/@vue/cli/lib/Creator.js, packages/@vue/cli/lib/options.js, packages/@vue/cli/lib/promptModules/vueVersion.js
=> feat!: make Vue 3 the default version for `vue create`

packages/@vue/cli-service/package.json
Workaround for https://github.com/vuejs/vue-cli/discussions/6943
Source cause https://github.com/webpack-contrib/mini-css-extract-plugin/issues/896
=> fix: set mini-css-extract-plugin to 2.4.5

packages/@vue/cli-ui/public/index.html
`shortcut` is used by IE6 which is dead and not supported anymore https://github.com/vuejs/vue-cli/issues/5232
=> fix: remove non standard rel=shortcut

packages/@vue/cli-service/package.json, yarn.lock
Reason: webpack-dev-server now provides its own type definitions.
This PR will stop npm from warning about a deprecated package when installing `@vue/cli-service` as a dependency.
=> chore: remove dep @types/webpack-dev-server (no longer required)

packages/@vue/cli-plugin-typescript/index.js, packages/@vue/cli-plugin-typescript/package.json, packages/@vue/cli-service/lib/config/base.js, packages/@vue/cli-service/package.json
To get rid of the annoying peer dependency warning.
This might slightly affect the build performance so users can still install it on their own by running `npm add -D cache-loader`
=> feat!: make `cache-loader` optional

packages/@vue/cli-service/package.json
Basically, just removing the temporary workaround introduced in https://github.com/vuejs/vue-cli/pull/6944 (`v5.0.0-rc.2`) due to an accidental breaking change added in `mini-css-extract-plugin v2.5.0`. This was fixed in `v2.5.1` https://github.com/webpack-contrib/mini-css-extract-plugin/issues/896#issuecomment-1014458314.
=> fix: update mini-css-extract-plugin to ^2.5.3

docs/guide/cli-service.md, packages/@vue/cli-service/__tests__/Service.spec.js, packages/@vue/cli-service/lib/Service.js
Remove `--skip-plugins` from arguments that are passed to the plugins.
Fixes https://github.com/vuejs/vue-cli/issues/6971
=> Remove --skip-plugin from arguments
